/**
 * Add order_number (unique human-readable), tracker_stage, and forwarding_address to orders table.
 * order_number is generated by application code as LF-YYYYMMDD-NNNN.
 */
module.exports = {
  name: 'add_order_number_tracker',
  up: async (client) => {
    await client.query(`
      ALTER TABLE orders
        ADD COLUMN IF NOT EXISTS order_number VARCHAR(30),
        ADD COLUMN IF NOT EXISTS tracker_stage VARCHAR(50) DEFAULT 'order_received',
        ADD COLUMN IF NOT EXISTS forwarding_address TEXT
    `);

    // Back-fill order_number for any existing rows
    await client.query(`
      UPDATE orders
      SET order_number = 'LF-' || TO_CHAR(created_at, 'YYYYMMDD') || '-' || LPAD(id::text, 4, '0')
      WHERE order_number IS NULL
    `);

    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS orders_order_number_idx ON orders (order_number) WHERE order_number IS NOT NULL`);
    await client.query(`CREATE INDEX IF NOT EXISTS orders_tracker_stage_idx ON orders (tracker_stage)`);
  },

  down: async (client) => {
    await client.query(`DROP INDEX IF EXISTS orders_order_number_idx`);
    await client.query(`DROP INDEX IF EXISTS orders_tracker_stage_idx`);
    await client.query(`ALTER TABLE orders DROP COLUMN IF EXISTS order_number`);
    await client.query(`ALTER TABLE orders DROP COLUMN IF EXISTS tracker_stage`);
    await client.query(`ALTER TABLE orders DROP COLUMN IF EXISTS forwarding_address`);
  },
};
