/**
 * Seed categories and flower arrangement products for Sugar Oak Lane.
 * Products inspired by same-day delivery competitors (FTD, Teleflora, FromYouFlowers).
 * Images: Unsplash royalty-free flower photography.
 * Idempotent: skips insert if slug already exists.
 */
module.exports = {
  name: 'seed_flower_products',
  up: async (client) => {

    // ──────────────────────────────────────────────────────────────────
    // CATEGORIES
    // ──────────────────────────────────────────────────────────────────
    const categories = [
      { name: 'Roses',           slug: 'roses',           icon: '🌹', desc: 'Classic and premium rose bouquets — single color, mixed, and long-stem.', sort: 1 },
      { name: 'Birthday',        slug: 'birthday',        icon: '🎂', desc: 'Bright, celebratory arrangements delivered same day for any birthday.', sort: 2 },
      { name: 'Sympathy',        slug: 'sympathy',        icon: '🕊️', desc: 'Elegant white and soft arrangements to express deepest condolences.', sort: 3 },
      { name: 'Romance',         slug: 'romance',         icon: '💕', desc: 'Romantic bouquets for anniversaries, Valentine\'s Day, and date nights.', sort: 4 },
      { name: 'Get Well',        slug: 'get-well',        icon: '🌻', desc: 'Cheerful arrangements to brighten anyone\'s day during recovery.', sort: 5 },
      { name: 'Congratulations', slug: 'congratulations', icon: '🎉', desc: 'Festive blooms to celebrate promotions, graduations, new babies, and milestones.', sort: 6 },
      { name: 'Just Because',    slug: 'just-because',    icon: '💐', desc: 'No occasion needed — send beauty any day of the week.', sort: 7 },
      { name: 'Seasonal',        slug: 'seasonal',        icon: '🌸', desc: 'Arrangements that celebrate the season in fresh, locally-inspired blooms.', sort: 8 },
    ];

    const catIds = {};
    for (const c of categories) {
      const res = await client.query(
        `INSERT INTO categories (name, slug, description, icon, sort_order)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
         RETURNING id`,
        [c.name, c.slug, c.desc, c.icon, c.sort]
      );
      catIds[c.slug] = res.rows[0].id;
    }

    // ──────────────────────────────────────────────────────────────────
    // PRODUCTS
    // ──────────────────────────────────────────────────────────────────
    const products = [

      // ── ROSES ──────────────────────────────────────────────────────
      {
        name: 'Classic Red Dozen Roses',
        slug: 'classic-red-dozen-roses',
        category: 'roses',
        short_desc: 'One dozen long-stem red roses, the timeless symbol of love and admiration.',
        description: 'Nothing says it better than a dozen deep-red roses. Hand-selected long-stem blooms arranged with lush greenery and a satin ribbon, delivered fresh to your door within 4 hours anywhere in Loganville, Grayson, Lawrenceville, or Snellville.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&q=80',
        tags: ['romance', 'birthday', 'anniversary'],
        featured: true,
        seo_title: 'Classic Red Dozen Roses | Sugar Oak Lane Same-Day Delivery Loganville GA',
        seo_desc: 'Order a classic dozen red roses with same-day delivery in Loganville, Grayson, Lawrenceville & Snellville GA. Fresh-cut, hand-arranged, delivered in 4 hours.',
      },
      {
        name: 'Pink Paradise Rose Bouquet',
        slug: 'pink-paradise-roses',
        category: 'roses',
        short_desc: 'Soft, blushing pink roses in a lush garden-style arrangement.',
        description: 'Soft pink roses paired with white waxflower and eucalyptus. A feminine, garden-fresh look that\'s perfect for mothers, friends, or anyone who deserves a touch of elegance. Available for same-day delivery in Gwinnett County.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=600&q=80',
        tags: ['romance', 'birthday', 'just-because'],
        featured: true,
        seo_title: 'Pink Rose Bouquet | Same-Day Flower Delivery Loganville GA',
        seo_desc: 'Pink paradise roses delivered same day in Loganville & Grayson GA. Order by 2PM for 4-hour delivery from your local florist.',
      },
      {
        name: 'White Elegance Rose Bouquet',
        slug: 'white-elegance-roses',
        category: 'roses',
        short_desc: 'Pure white roses with a sophisticated, understated beauty.',
        description: 'Pristine white roses with sprigs of baby\'s breath and silver-dollar eucalyptus. Classic, modern, and versatile — perfect for weddings, sympathy, or any occasion calling for quiet sophistication.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=600&q=80',
        tags: ['sympathy', 'romance', 'just-because'],
        featured: false,
        seo_title: 'White Rose Bouquet | Local Florist Near Loganville GA',
        seo_desc: 'Beautiful white rose arrangements delivered same-day in Loganville, Snellville & Lawrenceville GA. Order your local florist online.',
      },
      {
        name: 'Mixed Garden Rose Medley',
        slug: 'mixed-garden-roses',
        category: 'roses',
        short_desc: 'A lush mix of cream, blush, and coral roses in a garden-picked style.',
        description: 'Garden roses in cream, blush, and warm coral arranged in a loose, romantic style. Like freshly picked from an English garden. Comes in a keepsake vase with seasonal foliage.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1490750967868-88df5691166b?w=600&q=80',
        tags: ['birthday', 'just-because', 'romance'],
        featured: true,
        seo_title: 'Mixed Garden Rose Arrangement | Sugar Oak Lane Loganville GA',
        seo_desc: 'Mixed garden rose bouquets with same-day delivery in Loganville, Grayson, Lawrenceville & Snellville GA. Order online from your local florist.',
      },
      {
        name: '18 Long-Stem Red Roses',
        slug: 'long-stem-red-roses-18',
        category: 'roses',
        short_desc: 'Eighteen premium long-stem red roses — for the grand gesture.',
        description: 'When a dozen isn\'t enough. Eighteen premium long-stem red roses hand-tied in a generous bouquet with satin ribbon. This is the arrangement that makes a statement — birthdays, anniversaries, proposals.',
        standard: 89.99, deluxe: 114.99, premium: 144.99,
        img: 'https://images.unsplash.com/photo-1533616688419-b7a585564566?w=600&q=80',
        tags: ['romance', 'anniversary', 'birthday'],
        featured: false,
        seo_title: '18 Long-Stem Red Roses | Same-Day Delivery Gwinnett County GA',
        seo_desc: '18 premium long-stem red roses delivered same-day in Loganville, Grayson & Snellville GA. Your local 4-hour flower delivery florist.',
      },
      {
        name: 'Sunshine Yellow Rose Bunch',
        slug: 'yellow-sunshine-roses',
        category: 'roses',
        short_desc: 'Bright yellow roses bursting with warmth and cheerfulness.',
        description: 'Cheerful yellow roses paired with sunflower accents and fresh greenery. Brightens any room instantly. The perfect "thinking of you" or friendship bouquet, ready for same-day delivery in Gwinnett and Walton counties.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1574671347-736c2e5ce14b?w=600&q=80',
        tags: ['friendship', 'birthday', 'just-because'],
        featured: false,
        seo_title: 'Yellow Rose Bouquet | 4-Hour Flower Delivery Loganville GA',
        seo_desc: 'Bright yellow rose bouquets for same-day delivery in Loganville, Grayson, Lawrenceville & Snellville GA.',
      },
      {
        name: 'Lavender Rose Dream',
        slug: 'lavender-rose-dream',
        category: 'roses',
        short_desc: 'Rare lavender roses with a delicate, enchanting fragrance.',
        description: 'Soft lavender roses accented with dusty miller and spray roses in coordinating shades. Lavender roses symbolize enchantment and love at first sight — truly unforgettable as a gift.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80',
        tags: ['romance', 'just-because', 'birthday'],
        featured: false,
        seo_title: 'Lavender Rose Bouquet | Local Florist Loganville GA',
        seo_desc: 'Unique lavender rose arrangements delivered same-day in Loganville & Snellville GA. Order by 2PM for 4-hour delivery.',
      },

      // ── BIRTHDAY ────────────────────────────────────────────────────
      {
        name: 'Happy Birthday Burst Bouquet',
        slug: 'happy-birthday-burst',
        category: 'birthday',
        short_desc: 'A vibrant explosion of multi-color blooms for a truly happy birthday.',
        description: 'Bold gerbera daisies, sunflowers, hot pink roses, and orange lilies come together in a burst of birthday joy. This arrangement practically sings "Happy Birthday" when it arrives at the door.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
        tags: ['birthday'],
        featured: true,
        seo_title: 'Birthday Flower Delivery Loganville GA | Sugar Oak Lane',
        seo_desc: 'Same-day birthday flower delivery in Loganville, Grayson, Lawrenceville & Snellville GA. Bright, cheerful bouquets delivered in 4 hours.',
      },
      {
        name: 'Birthday Sunflower Celebration',
        slug: 'birthday-sunflower-celebration',
        category: 'birthday',
        short_desc: 'Tall, bold sunflowers with festive accents — sunny as the day itself.',
        description: 'Giant sunflowers surrounded by purple statice, orange spray roses, and seasonal greenery. A rustic, warm arrangement that radiates joy. Ideal for milestone birthdays.',
        standard: 54.99, deluxe: 69.99, premium: 89.99,
        img: 'https://images.unsplash.com/photo-1543088434-4e2b31ef9fe6?w=600&q=80',
        tags: ['birthday', 'just-because'],
        featured: false,
        seo_title: 'Birthday Sunflower Bouquet | Flower Delivery Grayson GA',
        seo_desc: 'Bright sunflower birthday arrangements delivered same-day in Grayson, Loganville & Snellville GA.',
      },
      {
        name: 'Rainbow Birthday Bouquet',
        slug: 'rainbow-birthday-bouquet',
        category: 'birthday',
        short_desc: 'Every color of the rainbow in one glorious birthday arrangement.',
        description: 'From violet irises to red roses, orange marigolds to yellow daisies — this arrangement covers the full spectrum. Lively, playful, and impossible to miss. Perfect for kids or anyone young at heart.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600&q=80',
        tags: ['birthday'],
        featured: false,
        seo_title: 'Rainbow Birthday Flowers | Same-Day Delivery Lawrenceville GA',
        seo_desc: 'Colorful rainbow birthday bouquets delivered same-day in Lawrenceville, Loganville & Snellville GA from your local florist.',
      },
      {
        name: 'Birthday Orchid Delight',
        slug: 'birthday-orchid-delight',
        category: 'birthday',
        short_desc: 'Exotic purple orchids for the birthday gift they\'ll never forget.',
        description: 'Dendrobium orchids in deep purple and white, arranged in a sleek glass vase with tropical leaves. Orchids last weeks, so the birthday memory keeps going long after the day ends.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1566835084745-4cd5cfb30c7e?w=600&q=80',
        tags: ['birthday', 'romance'],
        featured: false,
        seo_title: 'Birthday Orchid Arrangement | Flower Delivery Snellville GA',
        seo_desc: 'Exotic orchid birthday arrangements delivered same-day in Snellville, Loganville & Lawrenceville GA.',
      },
      {
        name: 'Bright Birthday Garden Basket',
        slug: 'bright-birthday-garden-basket',
        category: 'birthday',
        short_desc: 'A cheerful garden basket overflowing with birthday color.',
        description: 'Gerberas, button poms, alstroemeria, and greenery arranged in a handled wicker basket. Easy to display anywhere — no vase required. A thoughtful, personal gift that looks homemade in the best possible way.',
        standard: 49.99, deluxe: 64.99, premium: 84.99,
        img: 'https://images.unsplash.com/photo-1550159930-40066082a4fc?w=600&q=80',
        tags: ['birthday', 'just-because'],
        featured: false,
        seo_title: 'Birthday Flower Basket | Local Florist Loganville GA',
        seo_desc: 'Same-day birthday flower baskets in Loganville, Grayson & Gwinnett County GA. Order online for 4-hour delivery.',
      },

      // ── SYMPATHY ────────────────────────────────────────────────────
      {
        name: 'Peaceful White Lily Bouquet',
        slug: 'peaceful-white-lily-bouquet',
        category: 'sympathy',
        short_desc: 'Pure white oriental lilies — a serene expression of sympathy.',
        description: 'Fragrant white oriental lilies with soft eucalyptus and white snapdragons. A classic sympathy arrangement that conveys peace and comfort in a time of loss. Same-day delivery available across Gwinnett and Walton counties.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1508787983720-2c6eef6b3fa2?w=600&q=80',
        tags: ['sympathy'],
        featured: true,
        seo_title: 'Sympathy Flowers Loganville GA | Sugar Oak Lane Same-Day Delivery',
        seo_desc: 'Sympathy flower delivery in Loganville, Grayson, Lawrenceville & Snellville GA. White lily arrangements delivered in 4 hours.',
      },
      {
        name: 'Comfort Garden Sympathy Basket',
        slug: 'comfort-garden-sympathy-basket',
        category: 'sympathy',
        short_desc: 'A generous garden basket to bring comfort and lasting beauty.',
        description: 'White roses, lilies, and hydrangeas arranged in a large wicker basket with a satin bow. This substantial arrangement is appropriate for the home or funeral service, and serves as a lasting tribute.',
        standard: 74.99, deluxe: 94.99, premium: 119.99,
        img: 'https://images.unsplash.com/photo-1578874691223-64558a3ca096?w=600&q=80',
        tags: ['sympathy'],
        featured: false,
        seo_title: 'Sympathy Flower Basket | Funeral Flowers Loganville GA',
        seo_desc: 'Sympathy baskets and funeral flowers with same-day delivery in Loganville, Grayson & Lawrenceville GA.',
      },
      {
        name: 'Serene White Garden Arrangement',
        slug: 'serene-white-arrangement',
        category: 'sympathy',
        short_desc: 'All-white blooms arranged with quiet dignity for moments of grief.',
        description: 'White spray roses, white alstroemeria, and white lisianthus in a clear glass cylinder vase. A simple, peaceful arrangement that speaks volumes without saying a word.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1520453803296-c39eabe2dab4?w=600&q=80',
        tags: ['sympathy'],
        featured: false,
        seo_title: 'White Sympathy Arrangement | Same-Day Flower Delivery Snellville GA',
        seo_desc: 'All-white sympathy arrangements delivered same-day in Snellville, Loganville & Lawrenceville GA.',
      },
      {
        name: 'Garden of Grace Sympathy Bouquet',
        slug: 'garden-of-grace-sympathy',
        category: 'sympathy',
        short_desc: 'Soft cream, blush, and sage — a graceful farewell tribute.',
        description: 'Cream dahlias, blush roses, sage green hydrangeas, and dusty miller arranged in a garden-gathered style. Beautiful for a home, church, or funeral home display.',
        standard: 69.99, deluxe: 89.99, premium: 114.99,
        img: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?w=600&q=80',
        tags: ['sympathy'],
        featured: false,
        seo_title: 'Sympathy Bouquet Loganville GA | Sugar Oak Lane Local Florist',
        seo_desc: 'Graceful sympathy bouquets delivered same-day in Loganville, Grayson, Lawrenceville & Snellville GA.',
      },

      // ── ROMANCE ─────────────────────────────────────────────────────
      {
        name: 'Red Passion Anniversary Bouquet',
        slug: 'red-passion-anniversary',
        category: 'romance',
        short_desc: 'Deep red roses and calla lilies — unapologetically romantic.',
        description: 'Deep crimson roses, red calla lilies, and black-center anemones in a sleek glass vase. Dramatic, bold, and intensely romantic. Perfect for anniversaries, Valentine\'s Day, and milestone moments.',
        standard: 74.99, deluxe: 94.99, premium: 124.99,
        img: 'https://images.unsplash.com/photo-1461354464878-ad92f492a5a0?w=600&q=80',
        tags: ['romance', 'anniversary'],
        featured: true,
        seo_title: 'Anniversary Flowers Loganville GA | Sugar Oak Lane Same-Day Delivery',
        seo_desc: 'Romantic anniversary flower delivery in Loganville, Grayson & Snellville GA. Red roses and calla lilies in 4 hours.',
      },
      {
        name: 'Romance in Bloom Bouquet',
        slug: 'romance-in-bloom',
        category: 'romance',
        short_desc: 'Pink, red, and peach roses in a romantically arranged keepsake vase.',
        description: 'A mix of hot pink roses, red spray roses, and peachy alstroemeria in a textured ceramic vase. Warm, romantic, and personal — ideal for anniversaries, date nights, or saying "I love you" any day.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1523694576729-dc99e9c0f9b4?w=600&q=80',
        tags: ['romance', 'anniversary', 'birthday'],
        featured: false,
        seo_title: 'Romantic Flower Bouquet | Same-Day Delivery Grayson GA',
        seo_desc: 'Romantic flower bouquets delivered same-day in Grayson, Loganville & Lawrenceville GA. Perfect for anniversaries.',
      },
      {
        name: 'Love Story Bouquet',
        slug: 'love-story-bouquet',
        category: 'romance',
        short_desc: 'Lush red and blush roses for the chapter that never gets old.',
        description: 'Classic red roses softened with blush ranunculus and cascading greenery. A timeless love letter in flower form. Order by 2PM for same-day delivery anywhere in our service area.',
        standard: 64.99, deluxe: 84.99, premium: 109.99,
        img: 'https://images.unsplash.com/photo-1477512076069-d31cff2a82ba?w=600&q=80',
        tags: ['romance', 'anniversary'],
        featured: false,
        seo_title: 'Romantic Rose Bouquet | 4-Hour Flower Delivery Loganville GA',
        seo_desc: 'Beautiful love story bouquets with same-day delivery in Loganville, Grayson & Snellville GA.',
      },
      {
        name: 'Anniversary Orchid Garden',
        slug: 'anniversary-orchid-garden',
        category: 'romance',
        short_desc: 'Elegant phalaenopsis orchids for a truly memorable anniversary.',
        description: 'A stunning arrangement of white and purple phalaenopsis orchids with tropical foliage in a premium ceramic planter. Orchids represent luxury, strength, and long-lasting love — fitting for any anniversary.',
        standard: 79.99, deluxe: 99.99, premium: 129.99,
        img: 'https://images.unsplash.com/photo-1516205651411-aef33a44f7c2?w=600&q=80',
        tags: ['romance', 'anniversary'],
        featured: false,
        seo_title: 'Anniversary Orchid Arrangement | Local Florist Lawrenceville GA',
        seo_desc: 'Premium orchid anniversary arrangements delivered same-day in Lawrenceville, Loganville & Snellville GA.',
      },

      // ── GET WELL ────────────────────────────────────────────────────
      {
        name: 'Sunny Get Well Soon Bouquet',
        slug: 'sunny-get-well-soon',
        category: 'get-well',
        short_desc: 'Bright yellow sunflowers to lift spirits on any tough day.',
        description: 'Big, beaming sunflowers with yellow spray roses and orange alstroemeria. Scientifically proven to make people smile (we\'re florists, we know). Perfect for hospitals, home recovery, or anyone needing a mood boost.',
        standard: 49.99, deluxe: 64.99, premium: 84.99,
        img: 'https://images.unsplash.com/photo-1595351875957-5dde5832e30f?w=600&q=80',
        tags: ['get-well'],
        featured: true,
        seo_title: 'Get Well Flowers Loganville GA | Same-Day Delivery Sugar Oak Lane',
        seo_desc: 'Get well soon flowers delivered same-day in Loganville, Grayson & Snellville GA. Bright bouquets in 4 hours.',
      },
      {
        name: 'Healing Garden Basket',
        slug: 'healing-garden-basket',
        category: 'get-well',
        short_desc: 'A cheerful garden basket packed with get-well wishes.',
        description: 'Daisies, pom-poms, pink roses, and bupleurum in a rustic handled basket. Easy to display anywhere — bedside table, kitchen counter, hospital room. No water change needed for 10+ days.',
        standard: 54.99, deluxe: 69.99, premium: 89.99,
        img: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=600&q=80',
        tags: ['get-well', 'birthday'],
        featured: false,
        seo_title: 'Get Well Flower Basket | Flower Delivery Grayson GA',
        seo_desc: 'Get well flower baskets with same-day delivery in Grayson, Loganville & Lawrenceville GA.',
      },
      {
        name: 'Bright Daisy Cheer Bouquet',
        slug: 'bright-daisy-cheer',
        category: 'get-well',
        short_desc: 'Happy gerbera daisies in every color — instant mood uplift.',
        description: 'Oversized gerbera daisies in pink, orange, yellow, and red arranged with fresh greenery. Simple, unpretentious, and genuinely joyful. The flower equivalent of a warm hug.',
        standard: 44.99, deluxe: 59.99, premium: 79.99,
        img: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&q=80',
        tags: ['get-well', 'birthday', 'just-because'],
        featured: false,
        seo_title: 'Gerbera Daisy Bouquet | Same-Day Delivery Snellville GA',
        seo_desc: 'Bright daisy bouquets delivered same-day in Snellville, Loganville & Lawrenceville GA from your local florist.',
      },
      {
        name: 'Uplifting Spring Mix',
        slug: 'uplifting-spring-mix',
        category: 'get-well',
        short_desc: 'Fresh pastel blooms to bring spring energy to any room.',
        description: 'Pastel roses, lavender poms, and yellow tulips in a light aqua vase. Soft, calming colors that promote rest and recovery. Same-day delivery throughout Gwinnett County and Walton County.',
        standard: 49.99, deluxe: 64.99, premium: 84.99,
        img: 'https://images.unsplash.com/photo-1548586196-aa5803b77379?w=600&q=80',
        tags: ['get-well', 'just-because'],
        featured: false,
        seo_title: 'Get Well Soon Bouquet | 4-Hour Flower Delivery Lawrenceville GA',
        seo_desc: 'Uplifting spring flower arrangements delivered same-day in Lawrenceville, Loganville & Grayson GA.',
      },

      // ── CONGRATULATIONS ─────────────────────────────────────────────
      {
        name: 'Celebration Burst Bouquet',
        slug: 'celebration-burst-bouquet',
        category: 'congratulations',
        short_desc: 'A bold, festive arrangement worthy of any big achievement.',
        description: 'Hot pink gerberas, purple lisianthus, orange roses, and yellow button mums — every color turned up to celebrate. Ideal for graduations, promotions, new jobs, and any life win.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=600&q=80',
        tags: ['congratulations', 'birthday'],
        featured: true,
        seo_title: 'Congratulations Flowers | Same-Day Delivery Loganville GA',
        seo_desc: 'Same-day congratulations flowers in Loganville, Grayson, Lawrenceville & Snellville GA. Delivered in 4 hours.',
      },
      {
        name: 'Achievement Bouquet',
        slug: 'achievement-bouquet',
        category: 'congratulations',
        short_desc: 'Sophisticated blooms for the graduate or newly promoted.',
        description: 'White and gold tones — cream roses, champagne spray roses, and soft yellow solidago — for a celebration that feels refined and deserved. Great for graduations, promotions, and professional milestones.',
        standard: 59.99, deluxe: 79.99, premium: 99.99,
        img: 'https://images.unsplash.com/photo-1537530360953-3b8b369e01fe?w=600&q=80',
        tags: ['congratulations'],
        featured: false,
        seo_title: 'Graduation Flowers Loganville GA | Sugar Oak Lane Delivery',
        seo_desc: 'Graduation and achievement flower bouquets with same-day delivery in Loganville, Snellville & Lawrenceville GA.',
      },
      {
        name: 'New Baby Pink Bundle',
        slug: 'new-baby-pink-bundle',
        category: 'congratulations',
        short_desc: 'Soft pink roses and carnations to welcome a baby girl.',
        description: 'Soft pink roses, pale pink carnations, and white alstroemeria in a pink-accent vase with a "It\'s a Girl!" ribbon. A sweet way to say hello to the newest member of the family.',
        standard: 54.99, deluxe: 69.99, premium: 89.99,
        img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&q=80',
        tags: ['congratulations', 'new-baby'],
        featured: false,
        seo_title: 'New Baby Girl Flowers | Same-Day Delivery Grayson GA',
        seo_desc: 'New baby girl flower arrangements delivered same-day in Grayson, Loganville & Lawrenceville GA.',
      },
      {
        name: 'New Baby Blue Bundle',
        slug: 'new-baby-blue-bundle',
        category: 'congratulations',
        short_desc: 'Sky blue iris and white blooms to welcome a baby boy.',
        description: 'Blue iris, white carnations, and cream spray roses in a blue-accented vase with a "It\'s a Boy!" ribbon. The perfect way to celebrate a new arrival with natural beauty.',
        standard: 54.99, deluxe: 69.99, premium: 89.99,
        img: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=600&q=80',
        tags: ['congratulations', 'new-baby'],
        featured: false,
        seo_title: 'New Baby Boy Flowers | Flower Delivery Snellville GA',
        seo_desc: 'New baby boy flower arrangements delivered same-day in Snellville, Loganville & Lawrenceville GA.',
      },

      // ── JUST BECAUSE ────────────────────────────────────────────────
      {
        name: 'Garden Fresh Mixed Bouquet',
        slug: 'garden-fresh-mix',
        category: 'just-because',
        short_desc: 'A fresh, seasonal mix — the "just because I was thinking of you" bouquet.',
        description: 'Seasonal flowers chosen by our florists for peak freshness — whatever\'s most beautiful that day. Always a surprise, always stunning. The most honest arrangement we make.',
        standard: 44.99, deluxe: 59.99, premium: 79.99,
        img: 'https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?w=600&q=80',
        tags: ['just-because', 'birthday'],
        featured: true,
        seo_title: 'Fresh Mixed Flower Bouquet | Sugar Oak Lane Local Florist Loganville',
        seo_desc: 'Fresh, seasonal mixed bouquets delivered same-day in Loganville, Grayson, Snellville & Lawrenceville GA.',
      },
      {
        name: 'Wildflower Wonder Bouquet',
        slug: 'wildflower-wonder',
        category: 'just-because',
        short_desc: 'A loose, organic wildflower arrangement — like a walk through the Georgia countryside.',
        description: 'Queen Anne\'s lace, waxflower, lavender poms, and seasonal wildflowers loosely arranged for a natural, unstructured look. Perfect for free spirits who prefer beauty without formality.',
        standard: 49.99, deluxe: 64.99, premium: 84.99,
        img: 'https://images.unsplash.com/photo-1490750967868-88df5691166b?w=600&q=80',
        tags: ['just-because', 'birthday'],
        featured: false,
        seo_title: 'Wildflower Bouquet | Same-Day Flower Delivery Loganville GA',
        seo_desc: 'Wildflower arrangements delivered same-day in Loganville, Grayson & Gwinnett County GA.',
      },
      {
        name: 'Lavender Dreams Arrangement',
        slug: 'lavender-dreams',
        category: 'just-because',
        short_desc: 'Calming purple and lavender blooms for peace and serenity.',
        description: 'Lavender, purple lisianthus, and lilac waxflower in a soft purple-tinted vase. Calming, fragrant, and genuinely beautiful. Send it without a reason — they\'ll appreciate it more that way.',
        standard: 49.99, deluxe: 64.99, premium: 84.99,
        img: 'https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=600&q=80',
        tags: ['just-because', 'romance'],
        featured: false,
        seo_title: 'Lavender Flower Arrangement | Same-Day Delivery Loganville GA',
        seo_desc: 'Lavender and purple flower arrangements delivered same-day in Loganville, Snellville & Grayson GA.',
      },
      {
        name: 'Cottage Garden Charm Bouquet',
        slug: 'cottage-garden-charm',
        category: 'just-because',
        short_desc: 'English cottage style with peonies, roses, and delicate blooms.',
        description: 'When available, blush peonies anchored with white ranunculus, spray roses, and sweet William — an arrangement that looks like it came from a proper English cottage garden. A completely generous, unconditional gift.',
        standard: 54.99, deluxe: 69.99, premium: 89.99,
        img: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&q=80',
        tags: ['just-because', 'romance', 'birthday'],
        featured: false,
        seo_title: 'Cottage Garden Bouquet | Local Florist Near Me Loganville GA',
        seo_desc: 'Cottage-style flower arrangements delivered same-day near Loganville, Grayson & Lawrenceville GA.',
      },

      // ── SEASONAL ────────────────────────────────────────────────────
      {
        name: 'Spring Awakening Bouquet',
        slug: 'spring-awakening',
        category: 'seasonal',
        short_desc: 'Tulips, hyacinths, and daffodils — everything spring in one vase.',
        description: 'Bright tulips in orange and yellow, fragrant white hyacinths, and cheerful daffodils arranged in a clean glass vase. The scent alone is worth it. Available spring months.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1548586196-aa5803b77379?w=600&q=80',
        tags: ['seasonal', 'just-because', 'birthday'],
        featured: false,
        seo_title: 'Spring Flowers Loganville GA | Sugar Oak Lane Same-Day Delivery',
        seo_desc: 'Spring tulip and hyacinth arrangements delivered same-day in Loganville, Grayson & Snellville GA.',
      },
      {
        name: 'Summer Medley Bouquet',
        slug: 'summer-medley',
        category: 'seasonal',
        short_desc: 'The full brightness of a Georgia summer — zinnias, sunflowers, dahlias.',
        description: 'Dahlias, zinnias, sunflowers, and garden roses in saturated summer colors. This is the arrangement for Georgia summers — bold, warm, and overflowing. Cut fresh daily from local Georgia growers when available.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600&q=80',
        tags: ['seasonal', 'birthday'],
        featured: false,
        seo_title: 'Summer Flower Bouquet | Flower Delivery Snellville Loganville GA',
        seo_desc: 'Beautiful summer flower arrangements delivered same-day in Snellville, Loganville & Grayson GA.',
      },
      {
        name: 'Fall Harvest Arrangement',
        slug: 'fall-harvest-arrangement',
        category: 'seasonal',
        short_desc: 'Burnt orange, burgundy, and deep rust — the colors of Georgia fall.',
        description: 'Rust dahlias, burgundy spray roses, orange alstroemeria, and warm yellow goldenrod in an earthy terracotta vase. The fall arrangement that makes people ask who your florist is.',
        standard: 54.99, deluxe: 74.99, premium: 94.99,
        img: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600&q=80',
        tags: ['seasonal', 'birthday', 'just-because'],
        featured: false,
        seo_title: 'Fall Flower Arrangement | Same-Day Delivery Loganville GA',
        seo_desc: 'Autumn flower arrangements delivered same-day in Loganville, Lawrenceville & Grayson GA.',
      },
    ];

    // Insert products (idempotent)
    for (const p of products) {
      const catId = catIds[p.category];
      await client.query(
        `INSERT INTO products (
          name, slug, category_id, short_description, description,
          price_standard, price_deluxe, price_premium,
          image_url, occasion_tags, is_featured,
          seo_title, seo_description, sort_order
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
        ON CONFLICT (slug) DO UPDATE
          SET name = EXCLUDED.name,
              short_description = EXCLUDED.short_description,
              description = EXCLUDED.description,
              price_standard = EXCLUDED.price_standard,
              price_deluxe = EXCLUDED.price_deluxe,
              price_premium = EXCLUDED.price_premium,
              image_url = EXCLUDED.image_url,
              updated_at = NOW()`,
        [
          p.name,
          p.slug,
          catId,
          p.short_desc,
          p.description,
          p.standard,
          p.deluxe,
          p.premium,
          p.img,
          p.tags,
          p.featured || false,
          p.seo_title || p.name,
          p.seo_desc || p.short_desc,
          products.indexOf(p),
        ]
      );
    }

    console.log(`Seeded ${categories.length} categories and ${products.length} products.`);
  }
};
