/**
 * Migration: Seed products catalog part 4 — sorts 55–70
 * Salvia (3), Hibiscus, Bachelor Button (4), Bee's Friend, Craspedia,
 * Bupleurum, Corncockle (3), Baby's Breath, Pearl Millet
 */

const products = [
  // ─── Salvia ────────────────────────────────────────────────────────────────
  {
    name: 'Pink Sundae Salvia',
    slug: 'salvia-pink-sundae',
    sol_category: 'seeds-bulbs',
    subcategory: 'Salvia',
    flower_name: 'Salvia',
    flower_type: 'Annual',
    short_description: 'Tall rose-pink salvia spikes with deep pink calyces — a heat-tolerant cut flower that blooms all summer.',
    description: `Pink Sundae Salvia is a heat-tolerant annual salvia that delivers tall, densely packed rose-pink flower spikes on strong upright stems from early summer through fall — one of the most reliable and prolific summer cut flowers available for Georgia gardens. The two-toned effect of bright rose-pink petals emerging from deep pink-burgundy calyces creates a rich, layered texture that adds depth and interest to summer bouquets far beyond what simpler solid-color flowers can provide.\n\nAs a member of the sage family (Lamiaceae), Pink Sundae has a subtly aromatic foliage quality and produces sturdy, square stems that hold beautifully in arrangements without wilting. The flower spikes reach 18–24 inches in length, providing excellent stem length for mixed bouquets and flower shares. Plants continue producing new flower spikes throughout the season with regular harvesting, making Pink Sundae one of the most continuously productive summer cut flowers in the cutting garden.\n\nBees, bumblebees, and hummingbirds visit Pink Sundae salvia continuously throughout the blooming season, drawn by the abundant nectar in the tubular flowers. Planting a dedicated salvia cutting patch near vegetable gardens enhances crop pollination while providing steady cutting material from July through October in Georgia's climate.\n\nStart seeds indoors 8–10 weeks before the last frost date for earliest blooms, or direct sow after all frost danger has passed. Pinch growing tips early to encourage branching and more flower spikes per plant. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'long-blooming', 'filler'],
    is_featured: false,
    sort_order: 55,
    seo_title: 'Pink Sundae Salvia Seeds | Summer Cut Flower Spike | Sugar Oak Lane',
    seo_description: 'Grow Pink Sundae Salvia for tall rose-pink flower spikes all summer. Heat-tolerant, pollinator-friendly annual cut flower for Georgia cutting gardens.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Start indoors 8–10 weeks before last frost at 70–75°F. Barely cover seeds — need light to germinate. Transplant after last frost 12 inches apart. Pinch for bushiness. Deadhead spent spikes to encourage new growth.',
      days_to_maturity: '80–100 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining, moderately fertile soil; pH 6.0–7.0; drought-tolerant once established',
      spacing: '12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flowers', 'Summer bouquets', 'Pollinator gardens', 'Vertical filler', 'Farmers markets'],
      harvest_tips: 'Cut when lower 1/3–1/2 of spike is open. Condition in warm water overnight. Deep pink calyces continue to add color even after petals drop.',
      vase_life: '7–10 days',
      special_notes: 'Calyces retain color after petals drop. Excellent dried. Attracts hummingbirds. Heat and drought tolerant once established.'
    }
  },
  {
    name: 'Blue Monday Salvia',
    slug: 'salvia-blue-monday',
    sol_category: 'seeds-bulbs',
    subcategory: 'Salvia',
    flower_name: 'Salvia',
    flower_type: 'Annual',
    short_description: 'Deep violet-blue salvia spikes with purple calyces — true blue is rare in the summer garden and invaluable in the vase.',
    description: `Blue Monday Salvia delivers something rare and precious in the summer cutting garden: a true, deep violet-blue that has no equal in summer annuals. The tall, densely packed spikes of rich blue-violet flowers with deep purple calyces provide a jewel-toned intensity that immediately elevates any arrangement and creates strong contrast against the golds, oranges, and pinks of typical summer bouquets.\n\nTrue blue is notoriously difficult to achieve in garden flowers — most "blue" varieties resolve to purple or lavender in the garden and vase. Blue Monday salvia comes remarkably close to a genuine blue, making it one of the most sought-after cut flowers among florists designing in blue-and-white palettes, blue-and-gold arrangements for graduation events, and the classic navy-and-white combinations popular for summer weddings in coastal and traditional settings.\n\nFor Georgia cut flower growers, Blue Monday fills a critical market gap — few other summer annuals provide this blue tone. Combining Blue Monday with white baby's breath, golden rudbeckia, and orange celosia creates a complete summer harvest bouquet palette with dramatic visual impact. The blue tones are also exceptional in dried arrangements, where they hold their color better than many other dried botanicals.\n\nBlue Monday is as productive as it is beautiful — plants bloom continuously from midsummer through frost when harvested regularly. Start seeds indoors 8–10 weeks before last frost or direct sow after frost danger passes. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'blue', 'pollinator', 'dried-flower'],
    is_featured: true,
    sort_order: 56,
    seo_title: 'Blue Monday Salvia Seeds | Deep Blue Summer Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Blue Monday Salvia for rare deep violet-blue flower spikes. Heat-tolerant true-blue cut flower for Georgia summer gardens — exceptional for bouquets and dried arrangements.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Start indoors 8–10 weeks before last frost at 70–75°F. Surface sow — needs light to germinate. Transplant 12 inches apart after last frost. Pinch for more stems. Regular harvest encourages continuous bloom.',
      days_to_maturity: '80–100 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining, moderately fertile; pH 6.0–7.0; drought-tolerant when established',
      spacing: '12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flowers', 'Blue-white arrangements', 'Dried flowers', 'Pollinator gardens', 'Summer bouquets'],
      harvest_tips: 'Cut when lower 1/3 of spike is open. Calyces hold blue-purple color after petals drop. Air-dry upright or hanging for dried arrangements.',
      vase_life: '7–10 days',
      special_notes: 'True blue — rare in summer annuals. Excellent dried. Attracts bees and hummingbirds. Purple calyces maintain color after fresh petals drop.'
    }
  },
  {
    name: 'White Swan Salvia',
    slug: 'salvia-white-swan',
    sol_category: 'seeds-bulbs',
    subcategory: 'Salvia',
    flower_name: 'Salvia',
    flower_type: 'Annual',
    short_description: 'Elegant white salvia spikes with soft green calyces — the most versatile salvia for summer arrangements.',
    description: `White Swan Salvia brings clean, luminous elegance to the summer cutting garden with its tall spires of pure white flowers emerging from delicate green calyces — a two-toned freshness that provides a cooling counterpoint to the bold colors of high summer. White salvias are among the most versatile of all summer cut flowers, working seamlessly as a neutral filler in any color palette from the boldest tropical to the softest romantic pastel.\n\nThe tall, branching plants of White Swan produce an abundance of flower spikes from midsummer through frost, maintaining productive cutting performance through Georgia's heat and humidity far better than many other white summer flowers. The white flowers with green calyx combination provides a crisper, more modern aesthetic than typical filler flowers like baby's breath, making White Swan popular with florists designing in contemporary and garden-natural styles.\n\nWhite salvia is a natural companion for blue salvia varieties in blue-and-white arrangements, and pairs beautifully with pink zinnias, blush cosmos, and peach celosia for a soft summer palette with natural depth and movement. In wedding bouquets and event centerpieces, White Swan provides a graceful, airy structure without the stiffness of traditional white flowers.\n\nBees, bumblebees, and hummingbirds visit White Swan continuously through the season, making it valuable as both a cutting crop and a pollinator support plant in the Georgia garden. Start seeds 8–10 weeks before last frost indoors, or direct sow after frost. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'white', 'filler', 'pollinator', 'wedding'],
    is_featured: false,
    sort_order: 57,
    seo_title: 'White Swan Salvia Seeds | White Summer Cut Flower Spike | Sugar Oak Lane',
    seo_description: 'Grow White Swan Salvia — pure white flower spikes, the most versatile summer cut flower filler for Georgia gardens. Heat-tolerant, pollinator-friendly, and wedding-ready.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Start indoors 8–10 weeks before last frost at 70–75°F. Surface sow — needs light for germination. Transplant after last frost 12 inches apart. Pinch tips for more branching.',
      days_to_maturity: '80–100 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining, moderately fertile; pH 6.0–7.0; consistent moisture for best performance',
      spacing: '12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flowers', 'Wedding florals', 'Blue-white arrangements', 'Filler', 'Pollinator gardens'],
      harvest_tips: 'Cut when lower 1/3 of spike is in bloom. Green calyces remain attractive as florets drop, extending vase display. Condition in cool water.',
      vase_life: '7–10 days',
      special_notes: 'Most versatile salvia for floral design — white works with any palette. Green calyx remains attractive after petals drop. Excellent hummingbird plant.'
    }
  },

  // ─── Hibiscus ──────────────────────────────────────────────────────────────
  {
    name: 'Rozelle Hibiscus',
    slug: 'hibiscus-rozelle',
    sol_category: 'seeds-bulbs',
    subcategory: 'Hibiscus',
    flower_name: 'Hibiscus',
    flower_type: 'Annual',
    short_description: 'Tropical hibiscus grown for ornamental calyces and edible sour berries — a striking specialty botanical for growers.',
    description: `Rozelle Hibiscus (Hibiscus sabdariffa) is a remarkable dual-purpose tropical annual grown for two entirely different products: its ornamental dark-red fleshy calyces — which are harvested after bloom and used fresh or dried as a specialty botanical for arrangements — and the tart, cranberry-like calyces used to brew the beloved hibiscus tea (agua de Jamaica) consumed throughout the Caribbean, Central America, and increasingly across the American South.\n\nFor specialty cut flower growers and farmers market vendors in Georgia, Rozelle hibiscus represents a unique market opportunity — the dark-red star-shaped calyces are visually stunning as fresh botanical accents and dry beautifully for long-lasting wreath-making and dried arrangements. The flowers themselves (large, pale yellow with dark centers) are also edible and gorgeous as single-day blooms in floral design, though each flower lasts only one day.\n\nAs a warm-season tropical annual, Rozelle thrives in Georgia's hot, humid summers — it truly comes into its element during the months that challenge other crops. Plants grow to impressive size (5–7 feet) with handsome maple-like foliage and begin producing calyces in late summer through fall as day length shortens. The harvest period coincides perfectly with fall farmers markets, where the exotic crimson calyces attract immediate attention from customers who recognize them from herbal tea blends.\n\nDirect sow after all frost danger has passed and soil is warm, or start indoors 4–6 weeks early. Each packet contains approximately 25 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['specialty', 'edible', 'dried-flower', 'tropical', 'unique'],
    is_featured: false,
    sort_order: 58,
    seo_title: 'Rozelle Hibiscus Seeds | Specialty Edible Botanical | Sugar Oak Lane',
    seo_description: 'Grow Rozelle Hibiscus for stunning dark-red calyces used in arrangements, wreaths, and hibiscus tea. A tropical specialty botanical for Georgia gardens.',
    packet_quantity: 25,
    seed_details: {
      growing_instructions: 'Sow indoors 4–6 weeks before last frost at 70–75°F. Or direct sow after last frost when soil is warm (65°F+). Sow 1/2 inch deep. Plant in full sun with rich soil. Space 24–36 inches apart — plants get large.',
      days_to_maturity: '150–180 days from sowing; calyx harvest begins in late summer',
      plant_height: '5–7 feet',
      plant_spread: '24–36 inches',
      sun_requirements: 'Full sun (6+ hours daily) — thrives in heat',
      soil_preferences: 'Rich, well-draining soil with ample organic matter; pH 6.0–7.5; consistent moisture',
      spacing: '24–36 inches apart',
      sow_method: 'Transplant or direct sow after last frost',
      hardiness_zones: 'Annual — all zones; requires long, hot season (120+ frost-free days)',
      best_uses: ['Specialty botanical', 'Dried arrangements', 'Hibiscus tea', 'Wreaths', 'Farmers market specialty'],
      harvest_tips: 'Harvest calyces 2–3 weeks after flowers drop, when they are plump, firm, and deep red. Twist off easily when ready. Dry at low heat or air-dry for wreath-making.',
      vase_life: 'Fresh calyces: 5–7 days; dried: months to years',
      special_notes: 'Edible calyces — tart cranberry flavor. Flowers edible but last only one day. Grows large — allow ample space. Excellent fall farmers market specialty item.'
    }
  },

  // ─── Bachelor Button ───────────────────────────────────────────────────────
  {
    name: 'Black Bachelor Button',
    slug: 'bachelor-button-black',
    sol_category: 'seeds-bulbs',
    subcategory: 'Bachelor Button',
    flower_name: 'Bachelor Button',
    flower_type: 'Cool Season Annual',
    short_description: 'Deep burgundy-black bachelor buttons that trend at weddings and specialty markets — a moody, sophisticated cool-season cut.',
    description: `Black Bachelor Button (Centaurea cyanus) is one of the most talked-about specialty cut flowers in the current floral design community — its deeply saturated burgundy-black blooms with midnight-blue undertones occupy a dramatic, brooding aesthetic space that no other cool-season flower can match. Florists designing in the currently popular "moody" and "wild foraged" styles request dark bachelor buttons specifically for their ability to add depth, shadow, and sophistication to arrangements that would otherwise read as ordinary.\n\nDespite the common name, "black" bachelor buttons are actually a very deep wine-burgundy with black-purple undertones that appear nearly black in low light and photography — an effect that makes them especially striking in photographs and highly sought-after for photographed events like weddings, styled shoots, and social media content. The intricate, finely fringed petals characteristic of all centaureas add a delicate, lacey texture that contrasts beautifully with broader, smoother blooms.\n\nFor Georgia cut flower growers, black bachelor buttons are a specialty crop that commands premium attention at farmers markets — customers who see them for the first time invariably stop to look, ask about them, and purchase. Growing a dedicated row of black bachelor buttons alongside standard blue and classic magic varieties creates a complete bachelor button collection that drives significant market traffic.\n\nDirect sow in fall or early spring as soon as soil can be worked. Bachelor buttons thrive in cool weather and decline in summer heat. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'dark-tones', 'specialty', 'wedding', 'unique'],
    is_featured: true,
    sort_order: 59,
    seo_title: 'Black Bachelor Button Seeds | Dark Moody Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Black Bachelor Button for deep burgundy-black blooms — a trending specialty cut flower for moody wedding designs. Cool-season annual for Georgia spring gardens.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring as soon as soil can be worked. Sow 1/4 inch deep. Thin to 6–9 inches. Tolerates light frost. Does NOT like transplanting — direct sow is strongly preferred.',
      days_to_maturity: '70–90 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '9–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (strongly preferred — dislikes transplanting)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Dark arrangements', 'Wedding florals', 'Specialty bouquets', 'Styled shoots'],
      harvest_tips: 'Cut when outer petals are just unfurling but before fully open. Opens further in vase. Condition in cool water overnight. Avoid wetting blooms.',
      vase_life: '7–10 days',
      special_notes: 'Deep burgundy-black — appears nearly black in photos. Self-sows in mild climates. Edible flowers. One of the most sought-after dark specialty cut flowers.'
    }
  },
  {
    name: 'Blue Bachelor Button',
    slug: 'bachelor-button-blue',
    sol_category: 'seeds-bulbs',
    subcategory: 'Bachelor Button',
    flower_name: 'Bachelor Button',
    flower_type: 'Cool Season Annual',
    short_description: 'Classic cornflower blue — the original bachelor button that brings timeless cottage charm to spring bouquets.',
    description: `Blue Bachelor Button (Centaurea cyanus) is the original wildflower that inspired the common name "cornflower" — once so abundant in European grain fields that farmers considered it a weed, it was nonetheless beloved for its pure, brilliant blue that was (and remains) one of the truest blues achievable in a garden flower. The classic cornflower blue of this standard variety has been beloved by gardeners, florists, and flower lovers for centuries, and it remains one of the most timeless and versatile cut flowers available for the spring cutting garden.\n\nThe intricate, fringed petals of bachelor buttons create a delicate, lacey texture that adds fine detail to mixed bouquets, working beautifully as both a focal flower in small arrangements and a textural filler in large mixed compositions. The clear, bright blue tone is equally at home in casual farmhouse bouquets and sophisticated event designs — it's a flower that transcends aesthetic categories and feels simultaneously classic and fresh.\n\nFor Georgia cut flower growers, blue bachelor buttons offer exceptional value: they're easy to grow from direct-seeded seed, perform beautifully in cool weather (October through May in zones 7–8), produce abundantly with minimal inputs, and command a premium in spring farmers market bouquets where true blue is rare. A mass planting of blue cornflowers alongside white sweet alyssum and pink sweet williams creates a spring market display that stops traffic.\n\nDirect sow in fall or early spring. Bachelor buttons prefer cool weather and decline as summer heat builds. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'blue', 'cottage-garden', 'edible'],
    is_featured: false,
    sort_order: 60,
    seo_title: 'Blue Bachelor Button Seeds | Classic Cornflower Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow classic Blue Bachelor Button (cornflower) for timeless blue blooms in spring. Easy direct-sow cool-season cut flower for Georgia gardens and farmers markets.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow in fall or very early spring — seeds need a period of cold to germinate well. Sow 1/4 inch deep. Thin to 6–9 inches. Does not transplant well. Tolerates light frost once established.',
      days_to_maturity: '70–90 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '9–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (strongly preferred)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Cottage arrangements', 'Edible flowers', 'Wildflower meadows'],
      harvest_tips: 'Cut when outer petals are just unfurling. Opens fully in the vase. Condition overnight in cool water. One of the best long-lasting spring cut flowers.',
      vase_life: '7–10 days',
      special_notes: 'True cornflower blue — one of the most genuine blues in garden flowers. Edible flowers with mild flavor. Self-sows readily. Historically used as natural blue dye.'
    }
  },
  {
    name: 'Classic Magic Bachelor Button',
    slug: 'bachelor-button-classic-magic',
    sol_category: 'seeds-bulbs',
    subcategory: 'Bachelor Button',
    flower_name: 'Bachelor Button',
    flower_type: 'Cool Season Annual',
    short_description: 'A stunning mix of blue, purple, pink, white, and red bachelor buttons for vibrant spring cutting bouquets.',
    description: `Classic Magic Bachelor Button is the most versatile mix in the centaurea world — a carefully curated blend of blue, rich purple, soft pink, snowy white, and deep wine-red that provides a complete spectrum of bachelor button colors in a single planting. For cut flower growers who want maximum color variety for spring farmers market bouquets, CSA flower shares, and mixed arrangements, Classic Magic delivers unmatched range from a single packet of seed.\n\nThe mix produces all the beloved characteristics that make bachelor buttons exceptional cut flowers: the intricate fringed petals, the strong straight stems, the long vase life, and the cool-season resilience that allows them to perform beautifully in Georgia from November through May. Mixed plantings of Classic Magic create a visually dynamic cutting bed that provides variety with every harvest, ensuring that no two bouquets look exactly alike — a quality that customers and florists prize in garden-style flowers.\n\nPractical advantages of growing the Classic Magic mix include efficient use of garden space, reduced seed purchasing complexity, and the natural color harmony that well-curated seed mixes provide. The colors in Classic Magic were selected to complement each other in mixed bouquets, so any combination of stems pulled from the row will create a harmonious, professional-looking arrangement without careful color planning.\n\nFor growers new to bachelor buttons, Classic Magic is the ideal starting point — grow it first, then select your favorite individual colors from our single-color varieties (blue, black, pink) for focused plantings in subsequent seasons. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'mixed-colors', 'cottage-garden', 'versatile'],
    is_featured: false,
    sort_order: 61,
    seo_title: 'Classic Magic Bachelor Button Mix Seeds | Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Classic Magic Bachelor Button mix — blue, purple, pink, white, and red blooms for spring cutting gardens in Georgia. Easy direct-sow cool-season cut flower.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring as soon as soil can be worked. Sow 1/4 inch deep. Thin to 6–9 inches. Does not like transplanting. Fall sowing in zones 7–9 produces the best spring display.',
      days_to_maturity: '70–90 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '9–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor soil; moderate water',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (strongly preferred)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Mixed bouquets', 'Spring farmers markets', 'Flower CSAs', 'Cottage borders'],
      harvest_tips: 'Cut individual stems as outer petals begin to unfurl. Mix colors for instant bouquet variety. Condition in cool water overnight for longest vase life.',
      vase_life: '7–10 days',
      special_notes: 'Curated color mix with excellent harmony. Colors include blue, purple, pink, white, and deep wine-red. All colors edible. Self-sows readily for naturalized plantings.'
    }
  },
  {
    name: 'Pink Bachelor Button',
    slug: 'bachelor-button-pink',
    sol_category: 'seeds-bulbs',
    subcategory: 'Bachelor Button',
    flower_name: 'Bachelor Button',
    flower_type: 'Cool Season Annual',
    short_description: 'Soft rose-pink bachelor buttons with creamy centers — a sweet, feminine cool-season cut flower for spring bouquets.',
    description: `Pink Bachelor Button brings the beloved intricate, fringed texture of cornflowers to a soft, romantic rose-pink color palette that works beautifully in spring arrangements aimed at the wedding and gift market. The clear, warm pink tone with a lighter center has an old-fashioned cottage quality that resonates strongly with customers seeking natural, unstructured flower beauty — the opposite of the stiff, perfect roses that dominate conventional florist offerings.\n\nFor Georgia cut flower growers building a spring farmers market presence, offering pink bachelor buttons alongside the classic blue variety immediately doubles the color palette available for mixed spring bouquets. Pink cornflowers pair naturally with white sweet williams, blue bachelor buttons, and soft-toned ranunculus for a pastel spring arrangement that photographs beautifully and sells out quickly at spring markets.\n\nLike all centaureas, pink bachelor buttons are remarkably easy to grow from directly sown seed — they germinate and establish quickly in cool weather and begin blooming prolifically from March through May in Georgia's zone 7–8 climate. The plants produce an abundance of stems that can be harvested continuously over 4–6 weeks before summer heat causes them to decline.\n\nFor bridal and spring event work, pink bachelor buttons are an exceptional value — delicate, romantic, and long-lasting in the vase at a fraction of the cost of comparable florist flowers. Direct sow in fall or very early spring. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'pink', 'cottage-garden', 'wedding'],
    is_featured: false,
    sort_order: 62,
    seo_title: 'Pink Bachelor Button Seeds | Rose Pink Cornflower Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Pink Bachelor Button for soft rose-pink blooms in spring. A sweet cottage cut flower for Georgia gardens — direct sow in fall for spring markets and wedding work.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring as soon as soil can be worked. Sow 1/4 inch deep. Thin to 6–9 inches. Tolerates light frost. Direct sowing strongly preferred over transplanting.',
      days_to_maturity: '70–90 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '9–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (strongly preferred)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Spring bridal bouquets', 'Pastel arrangements', 'Farmers markets', 'Cottage borders'],
      harvest_tips: 'Cut when outer petals just begin to unfurl. Stems continue to open in the vase. Condition in cool water overnight for best vase life.',
      vase_life: '7–10 days',
      special_notes: 'Warm rose-pink — excellent companion to blue bachelor buttons. Edible flowers with mild flavor. Self-sows in mild climates for naturalized plantings.'
    }
  },

  // ─── Bee's Friend ──────────────────────────────────────────────────────────
  {
    name: "Bee's Friend",
    slug: 'bees-friend',
    sol_category: 'seeds-bulbs',
    subcategory: "Bee's Friend",
    flower_name: "Phacelia / Bee's Friend",
    flower_type: 'Cool Season Annual',
    short_description: 'Delicate lavender-blue phacelia blooms loved by bees — a cool-season specialty cut flower with exceptional pollinator value.',
    description: `Bee's Friend (Phacelia tanacetifolia) earns its name enthusiastically — few flowers in the garden attract and feed bees as powerfully as this lacy, lavender-blue annual. Beekeepers actively plant phacelia near hives as a premier honey and pollen source, but for cut flower growers, Bee's Friend is equally valued for its delicate, ferny foliage and graceful lavender-blue flower clusters that add a wild, naturalistic quality to arrangements unlike anything else in the spring garden.\n\nThe finely divided, almost fern-like foliage and curling scorpioid cyme flower clusters (botanical curling clusters that uncurl as blooms open, much like a fiddle fern) give Bee's Friend a wild, foraged aesthetic that resonates powerfully in the currently popular "just picked from the meadow" style of floral design. Wedding florists and farmers market customers who encounter it immediately ask what it is — which is exactly the conversation a specialty grower wants to have.\n\nFor Georgia cut flower growers, Bee's Friend fills a specific market niche as an unusual specialty filler — it's not something customers can easily find elsewhere, which makes it a signature item that differentiates your offering. Direct sow in fall or early spring in well-prepared beds. It grows quickly in cool weather and blooms heavily for several weeks before summer heat causes it to decline. The bees will thank you, too — often arriving in such numbers that a planting becomes almost audible with buzzing on warm spring mornings.\n\nEach packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'pollinator', 'specialty', 'filler', 'unique'],
    is_featured: false,
    sort_order: 63,
    seo_title: "Bee's Friend Phacelia Seeds | Specialty Pollinator Cut Flower | Sugar Oak Lane",
    seo_description: "Grow Bee's Friend Phacelia for lacy lavender-blue blooms loved by bees. A specialty cool-season cut flower for Georgia gardens — rare and beautiful for natural arrangements.",
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring — tolerates frost well. Sow seeds on surface and press in lightly. Thin to 6 inches. Very fast grower in cool weather. Does not transplant well.',
      days_to_maturity: '50–70 days from sowing',
      plant_height: '18–30 inches',
      plant_spread: '10–14 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Average to moderately fertile, well-draining soil; pH 6.0–7.5; consistent moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (strongly preferred)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 7+',
      best_uses: ['Cut flowers', 'Natural filler', 'Pollinator gardens', 'Specialty bouquets', 'Wildflower meadows'],
      harvest_tips: 'Cut when first flowers in each curling cluster are open. Clusters continue to unfurl in the vase. Condition in cool water overnight. Foliage may cause skin irritation for some — handle with gloves if sensitive.',
      vase_life: '6–9 days',
      special_notes: 'Premier bee and butterfly plant. Foliage may irritate sensitive skin — handle with care. Self-sows readily. Edible flowers occasionally used as garnish.'
    }
  },

  // ─── Craspedia ─────────────────────────────────────────────────────────────
  {
    name: 'Craspedia Billy Balls',
    slug: 'craspedia-billy-balls',
    sol_category: 'seeds-bulbs',
    subcategory: 'Craspedia',
    flower_name: 'Craspedia',
    flower_type: 'Annual',
    short_description: 'Perfect golden-yellow spheres on long straight stems — the most distinctive and long-lasting specialty dried flower available.',
    description: `Craspedia, known affectionately as "Billy Balls" or "Billy Buttons," is one of the most distinctive specialty flowers in the cut flower world — its perfect, golf ball-sized spheres of tiny golden-yellow florets sit atop long, straight stems like botanical lollipops, creating an immediately recognizable and utterly unique visual statement that no other flower can replicate. There is nothing else quite like craspedia, which makes it simultaneously one of the most sought-after and most recognizable specialty flowers at farmers markets, florists, and wedding fairs.\n\nFor the cut flower grower, craspedia offers exceptional advantages beyond its visual impact: the blooms dry flawlessly without losing their shape, color, or structure, and dried craspedia stems are virtually indistinguishable from fresh — they simply last indefinitely rather than weeks. This means craspedia can be sold at premium prices year-round as a dried specialty botanical, with none of the perishability concerns of typical cut flowers. Many growers specifically cultivate craspedia for its dried product value rather than (or in addition to) fresh cutting.\n\nGrowing craspedia from seed requires patience — it's a slow grower that needs 12–14 weeks from sowing to transplanting, followed by several more weeks to first bloom. In Georgia, start seeds in late summer for fall transplanting, or very early indoors (January–February) for spring planting. The effort is well rewarded with stems that command $1.50–$3.00 each at specialty floral markets.\n\nEach packet contains approximately 50 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'dried-flower', 'specialty', 'unique', 'long-lasting'],
    is_featured: true,
    sort_order: 64,
    seo_title: 'Craspedia Billy Balls Seeds | Golden Sphere Specialty Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Craspedia Billy Balls for perfect golden spheres on long stems — the most distinctive specialty cut and dried flower. Premium specialty botanical for Georgia cutting gardens.',
    packet_quantity: 50,
    seed_details: {
      growing_instructions: 'Start indoors 12–14 weeks before transplanting. Sow 1/8 inch deep at 60–70°F. Germination is slow (2–4 weeks) and uneven. Transplant after last frost in cool conditions. Space 12 inches apart.',
      days_to_maturity: '120–150 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '10–14 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining, sandy to loamy soil; pH 6.0–7.0; on the drier side — do not overwater',
      spacing: '12 inches apart',
      sow_method: 'Transplant (long lead time required)',
      hardiness_zones: 'Annual in zones 7 and below; perennial in zones 8–11',
      best_uses: ['Fresh cut stems', 'Dried arrangements', 'Wedding bouquets', 'Wreaths', 'Specialty florals'],
      harvest_tips: 'Cut when sphere is fully formed and bright golden-yellow. For drying, hang upside down in a warm, airy location. Dried stems look identical to fresh and last indefinitely.',
      vase_life: '14–21 days fresh; indefinitely when dried',
      special_notes: 'One of the most long-lasting cut flowers — fresh vase life 2–3 weeks. Dries perfectly without color loss. Premium specialty item commanding higher prices. Slow to grow but worth every week.'
    }
  },

  // ─── Bupleurum ─────────────────────────────────────────────────────────────
  {
    name: 'Bupleurum Griffithii',
    slug: 'bupleurum-griffithii',
    sol_category: 'seeds-bulbs',
    subcategory: 'Bupleurum',
    flower_name: 'Bupleurum',
    flower_type: 'Annual',
    short_description: 'Airy chartreuse-green foliage and tiny yellow-green flowers — the ultimate natural foliage filler for mixed arrangements.',
    description: `Bupleurum griffithii is the green filler that florists and farmers market growers have been searching for — a graceful, airy annual with glaucous blue-green oval leaves and clusters of tiny chartreuse-yellow flowers that provide exactly the naturalistic, foraged foliage quality that garden-style floral design demands. Unlike standard foliage fillers, bupleurum contributes both texture and subtle color — the blue-green leaves with yellow-green flower clusters create a layered tonal complexity that elevates arrangements without competing with focal flowers.\n\nFor the cut flower grower, bupleurum is invaluable as a cash crop and value-added component — a few stems of quality foliage can transform a simple bouquet into a full, lush composition that customers perceive as more sophisticated and complete. Bupleurum specifically provides a soft, airy structure that acts as a transitional element between bold focal flowers and fine fillers like baby's breath, giving mixed bouquets a natural depth and movement that's hard to achieve with other materials.\n\nIn Georgia's climate, bupleurum grows best as a cool-season crop, producing its best quality stems in spring and early summer before summer heat causes it to bolt. Direct sow in fall or very early spring for best results — once established, it grows quickly and begins producing harvestable stems within 60–70 days. A fall-sown planting in Georgia can provide cutting material from February through May, filling the cutting garden during the months when fresh foliage is most valuable.\n\nEach packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'foliage', 'filler', 'cool-season', 'specialty'],
    is_featured: false,
    sort_order: 65,
    seo_title: 'Bupleurum Griffithii Seeds | Green Foliage Filler Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Bupleurum Griffithii for airy chartreuse-green foliage filler. The ultimate natural foliage for garden-style arrangements and farmers market bouquets in Georgia.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring — prefers cool weather. Sow 1/4 inch deep. Thin to 6 inches. Can transplant if started indoors 4–6 weeks early, but direct sow is preferred. Tolerates light frost.',
      days_to_maturity: '60–80 days from sowing',
      plant_height: '18–30 inches',
      plant_spread: '10–14 inches',
      sun_requirements: 'Full sun to part shade (4–6+ hours daily)',
      soil_preferences: 'Average to moderately fertile, well-draining soil; pH 6.0–7.5; moderate moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow (preferred) or transplant',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Foliage filler', 'Mixed bouquets', 'Wedding arrangements', 'Farmers markets', 'Natural-style designs'],
      harvest_tips: 'Cut when flower clusters are in bud to open stage. Long vase life. Remove lower foliage below waterline. Condition in cool water overnight.',
      vase_life: '10–14 days',
      special_notes: 'One of the most valued foliage fillers in specialty florals. Blue-green leaves with chartreuse flowers are architectural and unique. Tolerates light frosts well.'
    }
  },

  // ─── Corncockle ────────────────────────────────────────────────────────────
  {
    name: 'Blush Corncockle',
    slug: 'corncockle-blush',
    sol_category: 'seeds-bulbs',
    subcategory: 'Corncockle',
    flower_name: 'Corncockle',
    flower_type: 'Cool Season Annual',
    short_description: 'Soft blush-pink five-petaled blooms on tall wispy stems — a delicate, romantic cool-season cut flower.',
    description: `Blush Corncockle (Agrostemma githago) is a wildflower cut flower with an ancient history and a thoroughly modern appeal — its delicate five-petaled blooms in soft blush-pink with darker pink veining have the handmade, natural quality that drives current floral design trends toward wild-foraged and garden-picked aesthetics. The long, thin stems and ethereal quality of the flowers give corncockle an airy grace that adds visual lightness to mixed arrangements in a way that larger, heavier flowers cannot.\n\nOnce common as a field weed across Europe, corncockle has been refined through selection into the beautiful cut flower varieties now prized by specialty growers. The blush color of this variety is particularly sought-after for spring weddings and romantic garden-style arrangements — a soft, warm pink that photographs beautifully and pairs naturally with ranunculus, sweet peas, clarkia, and other cool-season favorites.\n\nFor Georgia cut flower growers, corncockle is a direct-sow, minimal-input crop that thrives in cool weather and produces prolifically from March through May. A single direct-sowed row produces hundreds of harvestable stems that sell easily at spring farmers markets to customers who recognize the romantic, old-fashioned beauty immediately. Succession sow every 3–4 weeks through late winter to extend the harvest.\n\nImportant note: while the flowers are edible and beautiful, corncockle seeds are toxic if ingested. This is relevant for growers with children or livestock. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'pastel', 'cottage-garden', 'wildflower'],
    is_featured: false,
    sort_order: 66,
    seo_title: 'Blush Corncockle Seeds | Romantic Cool Season Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Blush Corncockle for soft pink wildflower blooms on wispy stems. A delicate, romantic cool-season cut flower for Georgia spring gardens — direct sow for easy growing.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring as soon as soil can be worked. Sow 1/4 inch deep. Thin to 6–9 inches. Tolerates light frost. Does not like transplanting — direct sow only.',
      days_to_maturity: '60–80 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '8–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate water',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow only (dislikes transplanting)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Romantic arrangements', 'Wedding florals', 'Wildflower meadows'],
      harvest_tips: 'Cut when blooms are fully open — corncockle does not continue opening after cutting. Condition in cool water. Vase life improved by recutting stems and changing water daily.',
      vase_life: '5–7 days',
      special_notes: 'IMPORTANT: Seeds are toxic if ingested — keep away from children and livestock. Flowers are safe for arrangements. Self-sows readily in mild climates.'
    }
  },
  {
    name: 'Rose Corncockle',
    slug: 'corncockle-rose',
    sol_category: 'seeds-bulbs',
    subcategory: 'Corncockle',
    flower_name: 'Corncockle',
    flower_type: 'Cool Season Annual',
    short_description: 'Vibrant rose-pink corncockle with deeper veining — bold and beautiful on tall wispy stems for spring cutting gardens.',
    description: `Rose Corncockle delivers the same delicate, wildflower beauty of blush corncockle in a more saturated, vibrant rose-pink that makes a bolder statement in mixed spring bouquets. The deeper rose-pink tones with dark burgundy veining create a richer, more saturated effect than the blush variety while retaining all the wispy, ethereal grace that makes corncockle one of the most beloved specialty cool-season cut flowers among florists designing in naturalistic and cottage styles.\n\nFor Georgia cut flower growers, offering multiple corncockle colors provides natural upsell opportunities — a mixed handful of blush and rose corncockle stems already creates a harmonious pastel bouquet that demonstrates sophisticated color knowledge and drives higher perceived value. The rose tones also pair beautifully with the deeper pinks and wines of spring tulips, ranunculus, and sweet william for rich, garden-style spring compositions.\n\nRose corncockle is as easy to grow as the blush variety — direct sow in fall or early spring and thin to 6–9 inches for best stem production. The plants are remarkably unfussy about soil quality, tolerating average to poor soils as long as drainage is good, making them an ideal crop for new flower farm plots that haven't yet been improved with years of compost additions.\n\nSelf-sowing is vigorous in mild climates — once established, rose corncockle will return each spring with minimal intervention, slowly naturalizing into a perennial-like presence that requires only occasional thinning. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'pink', 'cottage-garden', 'wildflower'],
    is_featured: false,
    sort_order: 67,
    seo_title: 'Rose Corncockle Seeds | Pink Wildflower Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Rose Corncockle for vibrant rose-pink blooms on wispy stems. A striking cool-season cut flower for Georgia spring cutting gardens — direct sow for effortless growing.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring — cool soil preferred. Sow 1/4 inch deep. Thin to 6–9 inches. Does not like transplanting. Tolerates light frost well.',
      days_to_maturity: '60–80 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '8–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate water',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow only',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Mixed arrangements', 'Farmers markets', 'Cottage borders'],
      harvest_tips: 'Cut when blooms are fully open. Condition in cool water with flower food. Change water daily for longest life. Recut stems every 2 days.',
      vase_life: '5–7 days',
      special_notes: 'IMPORTANT: Seeds are toxic if ingested. Flowers safe for arrangements. More saturated than blush variety — excellent for bold spring palettes. Self-sows freely.'
    }
  },
  {
    name: 'Ocean Pearls Corncockle',
    slug: 'corncockle-ocean-pearls',
    sol_category: 'seeds-bulbs',
    subcategory: 'Corncockle',
    flower_name: 'Corncockle',
    flower_type: 'Cool Season Annual',
    short_description: 'Pure white corncockle blooms on tall wispy stems — clean and luminous for elegant spring arrangements.',
    description: `Ocean Pearls Corncockle brings the delicate, wildflower elegance of corncockle to a pure white palette — its pristine five-petaled blooms with subtle gray-white veining glow with a luminous quality against the chartreuse and green of spring foliage, creating a sophisticated, clean aesthetic that works beautifully in minimalist designs, all-white wedding arrangements, and compositions where a sense of airy spaciousness is the primary design goal.\n\nWhite wildflower blooms are rarer than one might expect in the cool-season garden — most white spring flowers tend toward the heavy and formal (tulips, ranunculus) rather than the light and naturalistic. Ocean Pearls fills this specific aesthetic niche, providing an open, wispy white bloom that adds breathing room and elegant simplicity to mixed spring arrangements without the visual weight of more substantial white flowers.\n\nFor Georgia cut flower growers, Ocean Pearls is particularly valuable for the wedding and event market, where florists consistently request white flowers in multiple forms and scales. Offering white corncockle alongside white sweet williams, white lisianthus, and white gypsophila gives a florist client access to white stems at multiple price points and visual weights — making the flower farm a more complete and valuable supply source.\n\nGrow alongside blush and rose corncockle for a complete corncockle collection that covers the full pink-to-white spectrum. Direct sow in fall or early spring. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'white', 'wedding', 'wildflower', 'specialty'],
    is_featured: false,
    sort_order: 68,
    seo_title: 'Ocean Pearls White Corncockle Seeds | Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Ocean Pearls White Corncockle for luminous white wildflower blooms on wispy stems. An elegant cool-season cut flower for Georgia spring gardens and wedding work.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring in cool soil. Sow 1/4 inch deep. Thin to 6–9 inches. Does not like transplanting. Tolerates light frost once established.',
      days_to_maturity: '60–80 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '8–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 6.0–7.0; tolerates poor fertility; moderate moisture',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow only',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flowers', 'Wedding florals', 'All-white arrangements', 'Spring bouquets', 'Minimalist designs'],
      harvest_tips: 'Cut when blooms are fully open. White petals show bruising — handle gently. Condition in cool water. Recut and change water every 2 days.',
      vase_life: '5–7 days',
      special_notes: 'IMPORTANT: Seeds are toxic if ingested. Flowers are safe for arrangements. White petal luminosity is striking in photographs. Self-sows freely in mild climates.'
    }
  },

  // ─── Baby's Breath ─────────────────────────────────────────────────────────
  {
    name: "Baby's Breath Covent Garden",
    slug: 'babys-breath-covent-garden',
    sol_category: 'seeds-bulbs',
    subcategory: "Baby's Breath",
    flower_name: "Baby's Breath",
    flower_type: 'Annual',
    short_description: 'Classic airy white gypsophila clouds — the timeless filler that makes every bouquet feel complete and full.',
    description: `Baby's Breath Covent Garden (Gypsophila elegans) is the quintessential florist's filler — the airy cloud of tiny white blooms that makes every arrangement feel fuller, softer, and more complete. While trends in floral design have shifted toward more naturalistic and wild styles, baby's breath has retained its popularity because nothing else provides quite the same light, airy, cloud-like texture that harmonizes with virtually any other flower in any style of arrangement.\n\nThe annual Covent Garden variety is the classic white baby's breath grown by cut flower growers worldwide — it produces an abundance of fine-branched stems topped with tiny five-petaled white flowers on plants that grow to 24 inches and provide weeks of continuous cutting material. Unlike the perennial baby's breath that takes years to establish, annual gypsophila blooms in just 8–10 weeks from sowing and can be succession-planted every 3–4 weeks for continuous supply through the season.\n\nFor Georgia cut flower growers, baby's breath is an essential filler crop that adds volume and perceived value to every mixed bouquet sold at farmers markets, in CSA subscriptions, and to wholesale florist accounts. Even growers who focus primarily on specialty flowers benefit from maintaining a supply of baby's breath to fill out arrangements without using more expensive specialty stems.\n\nIn Georgia's warm climate, baby's breath performs best in cool weather — direct sow in fall for late winter and spring blooms, or in very early spring before summer heat builds. Succession planting extends the harvest window significantly. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'white', 'filler', 'wedding', 'classic'],
    is_featured: false,
    sort_order: 69,
    seo_title: "Baby's Breath Covent Garden Seeds | Classic White Filler | Sugar Oak Lane",
    seo_description: "Grow Baby's Breath Covent Garden for airy white clouds of tiny blooms — the classic filler for every bouquet. Easy cool-season cut flower for Georgia gardens.",
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow in fall or early spring (as soon as soil can be worked). Sow on surface and barely cover. Thin to 9–12 inches. Succession plant every 3–4 weeks for continuous supply. Does not like transplanting.',
      days_to_maturity: '50–70 days from sowing',
      plant_height: '18–24 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining soil; pH 6.5–7.5 (slightly alkaline preferred); moderate moisture; tolerates poor soils',
      spacing: '9–12 inches apart',
      sow_method: 'Direct sow (preferred)',
      hardiness_zones: 'Cool annual — all zones; fall sow in zones 6–9',
      best_uses: ['Cut flower filler', 'Mixed bouquets', 'Wedding florals', 'Dried arrangements', 'Farmers markets'],
      harvest_tips: 'Cut when 50–75% of tiny blooms on the branching stem are open. Condition in warm water with flower food overnight. Remove lower foliage.',
      vase_life: '7–14 days',
      special_notes: 'Prefer slightly alkaline soil — add garden lime if soil is acidic. Excellent dried — hang upside down, retains shape perfectly. Spray with hairspray to prevent petal drop when dried.'
    }
  },

  // ─── Pearl Millet ──────────────────────────────────────────────────────────
  {
    name: 'Purple Majesty Pearl Millet',
    slug: 'pearl-millet-purple-majesty',
    sol_category: 'seeds-bulbs',
    subcategory: 'Pearl Millet',
    flower_name: 'Pearl Millet',
    flower_type: 'Annual',
    short_description: 'Dramatic burgundy-purple ornamental grass with vertical architectural form — an exceptional foliage accent and dried flower.',
    description: `Purple Majesty Pearl Millet (Pennisetum glaucum) is one of the most dramatic ornamental grasses available for the cutting garden — its deep, rich burgundy-purple foliage and vertical architectural form make it an exceptional accent in summer and fall arrangements, adding a bold graphic presence that brings structure, depth, and a note of unexpected drama to bouquets that would otherwise rely entirely on flowering stems for interest.\n\nThe intensely saturated purple color of the foliage, stems, and developing seed heads is truly remarkable — almost black-purple in strong light, it creates striking contrast against golds, oranges, and creams of late summer harvest bouquets. As the season progresses and seed heads mature into full, substantial plumes, Purple Majesty millet transitions from a foliage accent to a focal botanical element — the thick, bristly seed plumes add architectural weight and textural interest unlike any flower.\n\nFor cut flower growers in Georgia, Purple Majesty is a heat-loving summer annual that thrives in exactly the conditions that challenge other crops — high temperatures, humidity, and intense summer sun are precisely what this ornamental grass needs to develop its best color and form. Direct sow after all frost danger passes and soil is warm, or transplant seedlings started 4–6 weeks earlier indoors.\n\nAs a dried botanical, Purple Majesty millet is exceptional — the seed plumes dry without any special treatment, retaining their form and dramatic color for months to years. Dried Purple Majesty stems are a premium specialty item in fall arrangements, harvest wreaths, and dried botanical bouquets. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'foliage', 'dried-flower', 'heat-loving', 'specialty', 'architectural'],
    is_featured: true,
    sort_order: 70,
    seo_title: 'Purple Majesty Pearl Millet Seeds | Ornamental Grass Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Purple Majesty Pearl Millet for dramatic burgundy-purple architectural foliage and seed plumes. A specialty summer cut flower and dried botanical for Georgia gardens.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Direct sow after last frost when soil is warm (65°F+), or transplant seedlings started 4–6 weeks indoors. Sow 1/4 inch deep. Thin to 18 inches. Requires warm conditions — does not tolerate cold.',
      days_to_maturity: '90–120 days from sowing for seed heads',
      plant_height: '4–5 feet',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun (6+ hours daily) — more sun = deeper purple color',
      soil_preferences: 'Average to moderately fertile, well-draining soil; pH 6.0–7.5; drought-tolerant once established',
      spacing: '18 inches apart',
      sow_method: 'Direct sow after last frost or transplant',
      hardiness_zones: 'Annual — all zones; requires long warm season (120+ days)',
      best_uses: ['Cut foliage', 'Architectural accent', 'Summer arrangements', 'Dried seed plumes', 'Fall harvest wreaths'],
      harvest_tips: 'Harvest foliage stems at any size — purple intensifies as season progresses. For seed plumes, cut when fully developed but before shattering. Air-dry upright for dried product.',
      vase_life: '10–14 days fresh; indefinitely when dried',
      special_notes: 'Color deepens with more sun and heat — best color in full sun. Seed plumes provide excellent dried product. Large, architectural plant — allow space. Edible seeds (traditional millet grain).'
    }
  }
];

module.exports = {
  name: 'seed_products_catalog_4',
  up: async (client) => {
    for (const p of products) {
      await client.query(
        `INSERT INTO sol_products (
          name, slug, sol_category, subcategory, short_description, description,
          price, price_label, images, availability, season_tags, type_tags,
          is_featured, sort_order, flower_name, flower_type,
          seo_title, seo_description, packet_quantity, seed_details, is_active
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,true)
        ON CONFLICT (slug) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          short_description = EXCLUDED.short_description,
          price = EXCLUDED.price,
          packet_quantity = EXCLUDED.packet_quantity,
          seed_details = EXCLUDED.seed_details,
          seo_title = EXCLUDED.seo_title,
          seo_description = EXCLUDED.seo_description,
          season_tags = EXCLUDED.season_tags,
          type_tags = EXCLUDED.type_tags,
          flower_name = EXCLUDED.flower_name,
          flower_type = EXCLUDED.flower_type,
          subcategory = EXCLUDED.subcategory,
          is_featured = EXCLUDED.is_featured,
          sort_order = EXCLUDED.sort_order,
          updated_at = NOW()`,
        [
          p.name, p.slug, p.sol_category, p.subcategory, p.short_description, p.description,
          p.price, p.price_label, JSON.stringify([]), p.availability,
          p.season_tags, p.type_tags, p.is_featured, p.sort_order,
          p.flower_name, p.flower_type, p.seo_title, p.seo_description,
          p.packet_quantity, JSON.stringify(p.seed_details)
        ]
      );
    }
    console.log(`Seeded ${products.length} products (sorts 55–70)`);
  },
  down: async (client) => {
    const slugs = products.map(p => p.slug);
    await client.query(`DELETE FROM sol_products WHERE slug = ANY($1)`, [slugs]);
    console.log(`Removed ${slugs.length} products (sorts 55–70)`);
  }
};
