// Migration part 2: Remaining zinnias + poppies + cosmos + celosia + amaranth

module.exports = {
  name: 'seed_products_catalog_2',
  up: async (client) => {
    const products = [

      // ─── ZINNIAS continued ────────────────────────────────────────────────

      {
        name: 'Benary Giant Orange Zinnia',
        slug: 'zinnia-benary-giant-orange',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Vivid tangerine-orange Benary Giant zinnia — bold, sunny, and one of the most reliable performers. ~50 seeds.',
        description: `Benary Giant Orange delivers the warmth of a Georgia summer in zinnia form — vivid tangerine-orange blooms measuring 4–5 inches across on long, strong stems. This is a classic zinnia color that sells confidently at farmers markets, works in virtually any arrangement, and pollinators find irresistible. The Benary series' disease resistance means your plants stay clean and productive through the Southeast's demanding summer humidity.\n\nDirect sow after last frost in full sun, spacing 12–15 inches apart. Pinch plants at 8–12 inches to encourage branching and longer stem production. Succession sow every 3 weeks for non-stop blooms from June through October. Orange zinnia pairs with yellow rudbeckia, chocolate amaranth, coral cosmos, and Sunrich sunflowers for warm-toned summer arrangements that feel abundant and celebratory.\n\nHarvest using the wiggle test — hold stem 8 inches below bloom; if firm, cut now. Slice above a leaf node to stimulate reblooming. Vase life runs a reliable 10–14 days. This is a must-grow for any cut flower gardener in the Southeast.\n\nKeywords: Benary Giant Orange zinnia seeds, orange zinnia, cut flower zinnia seeds, grow zinnia from seed, heat tolerant zinnia Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'pollinator'],
        is_featured: false,
        sort_order: 14,
        seo_title: 'Benary Giant Orange Zinnia Seeds | Vivid Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Orange zinnias from seed — vivid tangerine 4-5 inch blooms, disease-resistant, long-lasting cut flower. $3.95/packet Georgia.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches for branching. Succession sow every 3 weeks for continuous bloom.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (8+ hours)',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Mixed bouquets', 'Farmers market', 'Pollinator garden'],
          harvest_tips: 'Wiggle test for readiness. Cut above leaf node. Orange tones hold well in the vase without fading.',
          vase_life: '10–14 days',
          special_notes: 'Excellent mildew resistance. Pairs with sunflowers, rudbeckia, and chocolate amaranth for warm harvest palettes.'
        }
      },

      {
        name: 'Benary Giant Golden Yellow Zinnia',
        slug: 'zinnia-benary-giant-golden-yellow',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Pure golden yellow Benary Giant zinnia with classic large blooms. Versatile, cheerful, and always in demand. ~50 seeds.',
        description: `Benary Giant Golden Yellow is the clear, pure yellow that anchors summer bouquets and adds radiant warmth to any arrangement. Large 4–5 inch fully-double blooms in a clean golden tone — not orange, not green-yellow, but a true saturated gold — make this one of the most versatile zinnia colors for cut flower growers. It sells alongside sunflowers and rudbeckia for classic summer combinations that never go out of style.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches apart. Pinch at 8–12 inches tall to encourage multiple branching stems. Disease resistance is excellent across the Benary series, making this a reliable producer through Georgia's humid summers. Succession sow every 2–3 weeks for continuous blooms June through October.\n\nHarvest at the wiggle test stage — stem firm when held 8 inches below bloom. Cut above a leaf node to promote reblooming. Golden Yellow pairs with white, cream, blush, and soft green for fresh arrangements, or with orange, red, and rust for harvest palette work. Vase life 10–14 days.\n\nKeywords: Benary Giant Golden Yellow zinnia seeds, yellow zinnia, gold zinnia seeds, cut flower zinnia, grow zinnia from seed Georgia Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'pollinator'],
        is_featured: false,
        sort_order: 15,
        seo_title: 'Benary Giant Golden Yellow Zinnia Seeds | Bright Gold Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Golden Yellow zinnias — pure gold 4-5 inch blooms, disease-resistant, classic summer cut flower. $3.95/packet Georgia farm.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost. Full sun. Pinch at 8–12 inches. Avoid wetting foliage.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Mixed bouquets', 'Wedding flowers', 'Farmers market'],
          harvest_tips: 'Wiggle test for harvest. Cut above leaf node. Color holds beautifully — does not bleach.',
          vase_life: '10–14 days',
          special_notes: 'Excellent mildew resistance. Works in virtually any arrangement from rustic to formal.'
        }
      },

      {
        name: 'Benary Giant Wine Zinnia',
        slug: 'zinnia-benary-giant-wine',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Deep wine-maroon Benary Giant zinnia — rich, moody, and striking in late-summer arrangements. ~50 seeds.',
        description: `Benary Giant Wine occupies the darkest, most dramatic end of the zinnia spectrum — petals in deep wine-maroon with the sumptuous, velvety depth of a Bordeaux. This sophisticated color is especially prized for late-summer and fall arrangements, gothic and moody floral design, and any bouquet that needs a dark anchor color without using foliage. Florists who discover Wine don't go back.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches. Pinch at 8–12 inches to encourage branching. The Benary series' disease resistance keeps plants healthy through humid Georgia summers when other dark-colored zinnias often succumb to mildew. Succession plant April through July for blooms into October — the deepest, richest color develops in late summer's intense heat.\n\nHarvest at the wiggle test stage. Wine pairs with Benary Giant Coral, peach dahlias, blush lisianthus, and deep green foliage for an instantly sophisticated palette. It also anchors jewel-tone arrangements with purple, burgundy, and gold. Vase life 10–14 days — exceptional for a summer annual.\n\nKeywords: Benary Giant Wine zinnia seeds, dark zinnia, maroon zinnia seeds, wine-colored zinnia, cut flower zinnia seeds Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'unique-color'],
        is_featured: false,
        sort_order: 16,
        seo_title: 'Benary Giant Wine Zinnia Seeds | Deep Maroon Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Wine zinnias — deep wine-maroon 4-5 inch blooms, mildew-resistant, dramatic in fall arrangements. $3.95/packet from Georgia.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches. Best color develops in heat.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (8+ hours for deepest color)',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Fall arrangements', 'Moody floral design', 'Wedding flowers'],
          harvest_tips: 'Wiggle test. Color is richest when fully open. Pairs with coral and peach tones for striking contrast.',
          vase_life: '10–14 days',
          special_notes: 'Deepest color develops in full sun and hot temperatures. Use as a dark anchor in mixed arrangements.'
        }
      },

      {
        name: 'Benary Giant Coral Zinnia',
        slug: 'zinnia-benary-giant-coral',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Warm coral-peach Benary Giant zinnia — the perfect bridge color between pink and orange. ~50 seeds.',
        description: `Benary Giant Coral lives in the sweet spot between pink and orange — a warm coral-peach tone that bridges color palettes effortlessly and makes every arrangement around it look better. This is a professional florist's secret weapon: a color that works with both the warm and cool sides of a bouquet, softening oranges and warming pinks. Blooms reach 4–5 inches across in the characteristic Benary fully-double form on long, strong stems.\n\nGrow in full sun, direct sow after last frost, spacing 12–15 inches. Pinch at 8–12 inches for branching. Disease resistance throughout the Benary series keeps plants clean through Georgia's humid growing season. Succession sow every 3 weeks from last frost through July for blooms continuously through fall.\n\nHarvest at the wiggle test stage. Coral pairs with nearly everything — Benary Giant Wine for contrast, Queen Lime zinnias for modern combinations, sunflowers and cosmos for market bouquets. Vase life is the Benary standard of 10–14 days, making it one of the most cost-effective flowers you can grow.\n\nKeywords: Benary Giant Coral zinnia seeds, coral zinnia, peach zinnia seeds, cut flower zinnia seeds, warm-toned zinnia, Georgia flower seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'wedding'],
        is_featured: false,
        sort_order: 17,
        seo_title: 'Benary Giant Coral Zinnia Seeds | Warm Peach-Coral Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Coral zinnias — warm coral-peach 4-5 inch blooms, disease-resistant, the perfect bridge color. $3.95/packet Georgia farm.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches. Succession sow for continuous harvest.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Mixed bouquets', 'Subscription arrangements', 'Farmers market'],
          harvest_tips: 'Wiggle test. Color is most vibrant on freshly opened blooms. Excellent in mixed color bouquets.',
          vase_life: '10–14 days',
          special_notes: 'The ultimate bridge color — works with warm and cool palette sides. Excellent mildew resistance.'
        }
      },

      {
        name: 'Unicorn Zinnia',
        slug: 'zinnia-unicorn',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Unique green-tipped cream zinnia with quilled petals — unusual, beautiful, and a florist favorite. ~40 seeds.',
        description: `Unicorn zinnia is unlike anything else in the zinnia world — fully double blooms with quilled, tubular petals in cream to soft ivory edged with chartreuse-green tips. The effect is other-worldly and immediately eye-catching, which is exactly where the name comes from. This is a specialty zinnia that attracts attention at farmers markets and gives florists a unique element that can't be sourced from standard wholesale suppliers.\n\nGrow like standard cut zinnia varieties: direct sow after last frost in full sun, spacing 12–15 inches. Pinch at 8–12 inches to encourage branching. The quilled petals give Unicorn a longer fresh-looking period than flat-petaled zinnias. Start indoors 4 weeks before last frost for earlier blooms in Georgia's long growing season.\n\nHarvest at the wiggle test stage — the quilled petals hold firmly when the bloom is ready. The green tips are most vivid on freshly opened flowers and fade slightly as blooms age. Pairs magnificently with Queen Lime series, bupleurum, white cosmos, and any green foliage for modern, architectural arrangements. Vase life 8–12 days.\n\nKeywords: Unicorn zinnia seeds, green zinnia, quilled zinnia, unique zinnia varieties, specialty cut flower zinnia seeds, unusual zinnias Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'unique-color', 'specialty'],
        is_featured: true,
        sort_order: 18,
        seo_title: 'Unicorn Zinnia Seeds | Green-Tipped Quilled Specialty Zinnia | Sugar Oak Lane',
        seo_description: 'Grow Unicorn zinnia from seed — cream and green-tipped quilled petals, unique specialty cut flower. $3.95/packet. Sugar Oak Lane Georgia farm.',
        packet_quantity: 40,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost. Full sun. Pinch at 8–12 inches for branching. Start indoors 4 weeks before last frost for earlier blooms.',
          days_to_maturity: '75–80 days',
          plant_height: '2–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining fertile soil; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Specialty bouquets', 'Wedding flowers', 'Farmers market specialty', 'Modern arrangements'],
          harvest_tips: 'Harvest when quilled petals are fully extended and firm. Green tips are most vivid on freshly opened blooms. Wiggle test applies.',
          vase_life: '8–12 days',
          special_notes: 'Green tips fade as blooms age — harvest promptly for best effect. A guaranteed conversation starter at farmers markets.'
        }
      },

      {
        name: 'Queen Lime Peach Zinnia',
        slug: 'zinnia-queen-lime-peach',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Extraordinary Queen Lime zinnia in peach — blooms open lime-green then transform to warm peach. ~30 seeds.',
        description: `Queen Lime Peach is one of the most photographed and coveted zinnia varieties in modern floral design — blooms that open with distinctive lime-green outer petals and mature through apricot to warm peach tones, creating a complex, layered color that changes through the week in the vase. No two bouquets with Queen Lime Peach look exactly alike, which makes it endlessly interesting for florists and customers alike.\n\nThis is a more refined zinnia than standard Benary Giants — slightly smaller blooms (3–4 inches) with a more sophisticated color evolution. Grow in full sun with direct sow after last frost, spacing 12–15 inches. Pinch at 8–12 inches for branching. Queen Lime varieties perform best in Georgia's warm temperatures but benefit from afternoon shade in the hottest summer weeks. Start indoors 4–6 weeks before last frost for maximum season length.\n\nHarvest at the wiggle test stage when lime-green tints are still visible. The green fades over time in the vase but the peach deepens beautifully. Mix with other Queen Lime varieties, Benary Giant Coral, and green foliage for arrangements that command premium pricing. Vase life 8–12 days.\n\nKeywords: Queen Lime Peach zinnia seeds, lime green zinnia, peach zinnia, specialty zinnia seeds, cut flower zinnia, unique zinnia Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'unique-color', 'specialty', 'wedding'],
        is_featured: true,
        sort_order: 19,
        seo_title: 'Queen Lime Peach Zinnia Seeds | Lime to Peach Color-Shifting | Sugar Oak Lane',
        seo_description: 'Grow Queen Lime Peach zinnias — lime-green blooms shift to warm peach. Extraordinary specialty cut flower. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost or start indoors 4–6 weeks before. Full sun. Pinch at 8–12 inches. Provide afternoon shade in extreme heat.',
          days_to_maturity: '75–80 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun; light afternoon shade acceptable in peak summer',
          soil_preferences: 'Fertile, well-draining soil; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4–6 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Premium bouquets', 'Specialty market', 'Subscription arrangements'],
          harvest_tips: 'Harvest when lime-green tints are still visible on outer petals — wiggle test applies. Color continues evolving in the vase.',
          vase_life: '8–12 days',
          special_notes: 'Color evolution from lime-green to peach is the magic of this variety. Most valuable as a fresh-cut when still showing green tones.'
        }
      },

      {
        name: 'Queen Lime Blush Zinnia',
        slug: 'zinnia-queen-lime-blush',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Queen Lime zinnia opening lime-green, fading to the softest blush pink. Ethereal and extremely popular for weddings. ~30 seeds.',
        description: `Queen Lime Blush is the most romantic variety in the Queen Lime series — blooms that open with lime-green outer petals and soften to the palest, most delicate blush pink at their heart. The gradient effect across a single bloom is extraordinary, and in mixed arrangements with other Queen Lime varieties, the visual complexity is truly stunning. Wedding florists consistently rank Queen Lime Blush as one of their most-requested seasonal flowers.\n\nGrow in full sun, direct sow after last frost, spacing 12–15 inches. Start indoors 4–6 weeks before last frost for maximum season production. Pinch at 8–12 inches for branching. Queen Lime Blush performs best when given consistent moisture and light fertilization — a monthly application of balanced fertilizer keeps plants producing through the Georgia summer heat.\n\nHarvest when lime-green tones are still present on outer petals. The blush center is most visible at this stage and the color balance is at its most photogenic. Pairs with white ranunculus, cream lisianthus, soft lavender, and green foliage for wedding work that photographs like a dream. Vase life 8–12 days.\n\nKeywords: Queen Lime Blush zinnia seeds, blush zinnia, lime green zinnia seeds, wedding zinnia seeds, soft pink zinnia, specialty cut flower Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'unique-color', 'wedding', 'specialty'],
        is_featured: true,
        sort_order: 20,
        seo_title: 'Queen Lime Blush Zinnia Seeds | Lime to Blush Pink Wedding Flower | Sugar Oak Lane',
        seo_description: 'Grow Queen Lime Blush zinnias — lime-green blooms shift to softest blush pink. Top wedding flower. $3.95/packet. Sugar Oak Lane Georgia.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Start indoors 4–6 weeks before last frost or direct sow after. Full sun. Pinch at 8–12 inches. Fertilize monthly with balanced fertilizer.',
          days_to_maturity: '75–80 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun; some afternoon shade in extreme heat is acceptable',
          soil_preferences: 'Fertile, well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Start indoors 4–6 weeks before last frost for best results',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding bouquets', 'Premium cut flowers', 'Bridal arrangements', 'Specialty market'],
          harvest_tips: 'Harvest when lime-green tones still visible on outer petals. Blush center most vivid at this stage. Wiggle test applies.',
          vase_life: '8–12 days',
          special_notes: 'Mix with Queen Lime Peach and Orange for a stunning Queen Lime mixed arrangement. Consistently one of the most popular wedding zinnias.'
        }
      },

      {
        name: 'Queen Lime Orange Zinnia',
        slug: 'zinnia-queen-lime-orange',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Queen Lime zinnia shifting from lime-green to vivid warm orange — bold, modern, and striking. ~30 seeds.',
        description: `Queen Lime Orange brings the boldest energy to the Queen Lime series — blooms that open with characteristic lime-green outer petals and deepen through apricot to a vivid warm orange at the center. The transition is dramatic and produces one of the most visually complex single zinnia blooms available to cut flower growers. This variety photographs beautifully in flat-lay shots where the gradient across petals is fully visible.\n\nGrow in full sun, direct sow after last frost spacing 12–15 inches. Pinch at 8–12 inches for branching. For earliest blooms in Georgia, start indoors 4–6 weeks before last frost. The orange coloring develops more intensely in full, direct sun — partial shade produces a more muted palette. Succession sow every 3 weeks from last frost through mid-June for extended harvest.\n\nHarvest at the wiggle test stage when lime-green outer petals are still visible. The orange center is at its most vibrant at this point. Queen Lime Orange pairs with Queen Lime Peach, Sunrich Orange sunflowers, coral cosmos, and green foliage for a warm, sun-drenched summer palette. Vase life 8–12 days.\n\nKeywords: Queen Lime Orange zinnia seeds, lime orange zinnia, specialty zinnia seeds, unusual zinnia, cut flower zinnia seeds, Georgia farm flower seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'unique-color', 'specialty'],
        is_featured: false,
        sort_order: 21,
        seo_title: 'Queen Lime Orange Zinnia Seeds | Lime to Orange Specialty Zinnia | Sugar Oak Lane',
        seo_description: 'Grow Queen Lime Orange zinnias — lime-green blooms shift to vivid orange. Bold specialty cut flower. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow after last frost or start indoors 4–6 weeks before. Full sun required for deepest orange. Pinch at 8–12 inches.',
          days_to_maturity: '75–80 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (deepest color in maximum sun)',
          soil_preferences: 'Fertile, well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4–6 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Specialty bouquets', 'Warm-palette arrangements', 'Farmers market specialty', 'Cut flowers'],
          harvest_tips: 'Harvest when outer lime-green petals are still present. Wiggle test. Orange center most vivid at this stage.',
          vase_life: '8–12 days',
          special_notes: 'Boldest color develops in full sun. Beautiful mixed with other Queen Lime varieties in a mono-series bouquet.'
        }
      },

      {
        name: 'Queen Lime Red Zinnia',
        slug: 'zinnia-queen-lime-red',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Queen Lime zinnia with lime-green outer petals deepening to rich red — dramatic contrast in a single bloom. ~30 seeds.',
        description: `Queen Lime Red delivers the most dramatic contrast in the Queen Lime series — lime-green outer petals that intensify through crimson to deep red at the center of each fully-double bloom. The bicolor effect within a single flower is visually striking and immediately distinguishable from standard zinnias. This variety adds sophistication and complexity to any arrangement it enters.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches. Pinch plants at 8–12 inches tall to encourage multiple branching stems. Start indoors 4–6 weeks before last frost for Georgia's earliest possible harvest. The red coloring intensifies with heat, making this an excellent variety for summer production when the lime-green to red contrast is at its most vivid.\n\nHarvest at the wiggle test stage, when lime-green outer petals are still present. This is when the contrast is most dramatic. Queen Lime Red pairs with white, ivory, and the other Queen Lime varieties for sophisticated arrangements, or with deep burgundy and forest green for a jewel-toned fall palette. Vase life 8–12 days.\n\nKeywords: Queen Lime Red zinnia seeds, red lime zinnia, bicolor zinnia seeds, specialty zinnia, cut flower zinnia seeds Georgia Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'unique-color', 'specialty'],
        is_featured: false,
        sort_order: 22,
        seo_title: 'Queen Lime Red Zinnia Seeds | Lime to Red Bicolor Specialty | Sugar Oak Lane',
        seo_description: 'Grow Queen Lime Red zinnias — lime-green outer petals deepening to rich red. Dramatic specialty cut flower. $3.95/packet. Georgia farm.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow after last frost or start indoors 4–6 weeks before. Full sun. Pinch at 8–12 inches. Red deepens in heat.',
          days_to_maturity: '75–80 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Fertile, well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4–6 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Specialty arrangements', 'Fall bouquets', 'Cut flowers', 'Farmers market specialty'],
          harvest_tips: 'Harvest when lime-green outer petals are still visible for maximum contrast. Wiggle test applies.',
          vase_life: '8–12 days',
          special_notes: 'Red deepens with heat. Most dramatic contrast on freshly-opened blooms. Great in mixed Queen Lime collections.'
        }
      },

      {
        name: 'Luminosa Zinnia',
        slug: 'zinnia-luminosa',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Bright, neon-vivid zinnia mix with large blooms in electric colors. High-energy, fast-selling at farmers markets. ~40 seeds.',
        description: `Luminosa zinnia delivers neon-bright energy in a large-bloomed, freely-branching variety that produces an abundance of vivid flowers throughout the summer. Colors range across electric pink, orange, red, and gold in the fully-double zinnia form — not subtle, not romantic, just pure saturated joy in flower form. At farmers markets, Luminosa bouquets attract customers from across the aisle.\n\nGrow in full sun, direct sow after last frost spacing 12–15 inches. Pinch at 8–12 inches for branching. Luminosa's vigorous constitution handles Georgia's summer heat well and continues producing through high temperatures that slow some other zinnia varieties. Succession sow every 3 weeks from last frost through mid-July for continuous bloom through October.\n\nHarvest at the wiggle test stage. The bright mixed colors are most effective in full mixed arrangements or single-variety market bunches that showcase the color range. Luminosa pairs with any other warm-colored cut flower for a high-energy summer look. Vase life 10–14 days with proper care and regular water changes.\n\nKeywords: Luminosa zinnia seeds, bright zinnia, neon zinnia, vivid zinnia mix, cut flower zinnia, grow zinnia from seed Georgia summer.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'mixed-colors'],
        is_featured: false,
        sort_order: 23,
        seo_title: 'Luminosa Zinnia Seeds | Neon-Bright Cut Flower Mix | Sugar Oak Lane',
        seo_description: 'Grow Luminosa zinnias — neon-vivid large blooms in electric mixed colors, prolific cut flower. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 40,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches for more stems. Succession sow every 3 weeks.',
          days_to_maturity: '70–75 days',
          plant_height: '2–2.5 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Farmers market', 'Cheerful bouquets', 'Pollinator garden', 'Cut flowers'],
          harvest_tips: 'Wiggle test. Harvest across color range for mixed bunches. Regular harvesting keeps plants producing.',
          vase_life: '10–14 days',
          special_notes: 'Mixed colors — select stems for color-coordinated arrangements or embrace the full vivid mix.'
        }
      },

      {
        name: 'Isabellina Zinnia',
        slug: 'zinnia-isabellina',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Antique cream-ivory zinnia with a warm, whisper-soft tone — beloved by florists for its quiet elegance. ~40 seeds.',
        description: `Isabellina zinnia is named for the pale, warm ivory-cream tone called "isabelle" in the historic textile trade — a color that is simultaneously neutral and luminous, neither stark white nor fully yellow but a soft, honeyed cream. Florists prize Isabellina for its ability to soften arrangements without the stark contrast of white, working harmoniously alongside blush, peach, lavender, and warm green tones.\n\nGrow in full sun, direct sow after last frost spacing 12–15 inches. Pinch at 8–12 inches for branching. Isabellina's pale coloring is most accurate in full sun — partial shade can cause a greener-yellow cast. This is an excellent variety for the Georgia cut flower garden because it performs through summer heat while delivering a color that commands premium pricing at market and in subscription bouquets.\n\nHarvest at the wiggle test stage. Isabellina is the perfect complement to Benary Giant Lilac, Queen Lime Blush, Baby's Breath, and eucalyptus for soft, romantic bouquets. It's equally beautiful in monochromatic cream arrangements where texture from different flower forms — zinnia, cosmos, baby's breath — creates depth. Vase life 10–14 days.\n\nKeywords: Isabellina zinnia seeds, cream zinnia, ivory zinnia, antique zinnia, pale zinnia seeds, cut flower zinnia seeds Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'wedding', 'unique-color'],
        is_featured: false,
        sort_order: 24,
        seo_title: 'Isabellina Zinnia Seeds | Antique Cream-Ivory Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Isabellina cream-ivory zinnias — soft antique tone, beloved by florists, perfect for romantic bouquets. $3.95/packet from Sugar Oak Lane.',
        packet_quantity: 40,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches. Full sun maintains truest color.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun for truest cream color',
          soil_preferences: 'Well-draining fertile soil; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Romantic bouquets', 'Subscription arrangements', 'Specialty market'],
          harvest_tips: 'Wiggle test. Cream tones are most luminous on freshly opened blooms. Pairs with almost any color.',
          vase_life: '10–14 days',
          special_notes: 'Full sun maintains truest cream color. A grower favorite for premium market bouquets and wedding work.'
        }
      },

      // ─── POPPIES (3) ──────────────────────────────────────────────────────

      {
        name: 'Iceland Poppies',
        slug: 'poppy-iceland',
        sol_category: 'seeds-bulbs',
        subcategory: 'Poppies',
        flower_name: 'Poppy',
        flower_type: 'Cool Season Annual',
        short_description: 'Delicate crepe-paper poppies in coral, orange, yellow, pink, and white. Cool-season stars for Georgia winter gardens. ~500 seeds.',
        description: `Iceland poppies (Papaver nudicaule) are among the most ethereal flowers a gardener can grow — tissue-thin crepe-paper petals in a full range of coral, orange, golden yellow, soft pink, and white, held on graceful arching stems above rosettes of blue-green foliage. In Georgia and across the Southeast, Iceland poppies thrive as cool-season annuals, filling winter and spring gardens with color that feels impossibly delicate.\n\nThe key to success with Iceland poppies in the South is timing: sow seeds in fall (September through November) directly where they'll grow, or start indoors in late summer and transplant before frost. Cold nights and warm days through winter stimulate the compact rosette growth, and blooms begin appearing February through April — before the heat arrives. Seeds are extremely tiny; surface sow without covering and keep moist.\n\nFor cut flowers, harvest stems when the bud has just cracked open — before petals unfurl. Sear the cut end briefly in a flame or dip in boiling water for 5 seconds to prevent milky latex from fouling the vase water. Vase life is 5–7 days with this treatment. Iceland poppies are irreplaceable in spring arrangements for their translucent petal quality that no other flower replicates.\n\nKeywords: Iceland poppy seeds, Papaver nudicaule, cool season poppy, winter annual Georgia, spring cut flower seeds, grow poppies from seed Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['cool-season', 'winter', 'spring'],
        type_tags: ['cut-flower', 'cool-season', 'winter-annual', 'pollinator'],
        is_featured: true,
        sort_order: 25,
        seo_title: 'Iceland Poppy Seeds | Cool Season Cut Flower | Sugar Oak Lane Georgia',
        seo_description: 'Grow Iceland poppies from seed — delicate crepe-paper blooms in mixed colors. Fall-sow in Georgia for winter-spring cut flowers. $3.95/packet.',
        packet_quantity: 500,
        seed_details: {
          growing_instructions: 'Surface sow — do not cover seeds (need light to germinate). Sow in fall (Sept–Nov) in Georgia directly in garden or in cell trays. Keep moist. Transplant carefully before hard frost.',
          days_to_maturity: '90–120 days from fall sowing (blooms Feb–Apr)',
          plant_height: '15–18 inches',
          plant_spread: '8–12 inches',
          sun_requirements: 'Full sun to part shade',
          soil_preferences: 'Well-draining, fertile soil; pH 6.0–7.0. Do not over-fertilize.',
          spacing: '8–12 inches',
          sow_method: 'Direct sow in fall (surface sow, no cover) OR start indoors in late summer',
          hardiness_zones: 'Winter annual (zones 7–10 in the South; perennial in zones 5–7)',
          best_uses: ['Cut flowers', 'Spring arrangements', 'Garden display', 'Pollinator garden'],
          harvest_tips: 'Harvest when bud cracks open before petals unfurl. Sear cut end in flame or hot water for 5 seconds to seal latex. Do not skip this step.',
          vase_life: '5–7 days (with stem searing)',
          special_notes: 'Tiny seeds — surface sow, no cover. Do not disturb roots when transplanting. Does not tolerate Georgia summer heat — treat as winter annual.'
        }
      },

      {
        name: 'Breadseed Poppies',
        slug: 'poppy-breadseed',
        sol_category: 'seeds-bulbs',
        subcategory: 'Poppies',
        flower_name: 'Poppy',
        flower_type: 'Cool Season Annual',
        short_description: 'Large ornamental poppy with stunning seed pods — beautiful in the garden and as dried material. Mixed colors. ~500 seeds.',
        description: `Breadseed poppies (Papaver somniferum) are the gardener's poppy — tall, elegant plants bearing large single or double flowers in red, pink, purple, and white, followed by the decorative, glaucous blue-green seed pods that make such stunning dried arrangements. Florists prize both the fresh-cut flowers and the dried pods, which hold their color for months and add architectural interest to any dried arrangement.\n\nIn Georgia and the Southeast, direct sow breadseed poppies in fall (October through December) or in earliest spring — they need cold stratification that winter naturally provides, and the plants establish best with cool weather before bolting to bloom in spring. Scatter seeds over prepared soil, rake lightly, and press down. They will self-sow prolifically once established, naturalizing in the garden year after year.\n\nFor cut flowers, harvest blooms when petals are just unfurling from the bud. Sear stem ends immediately to prevent latex milkiness. Vase life is 5–7 days. For dried pods, wait until pods are fully mature and beginning to rattle with seeds — harvest on stems and hang upside down in bundles to dry. Breadseed poppies are irreplaceable for dried floral work.\n\nKeywords: Breadseed poppy seeds, Papaver somniferum, ornamental poppy seeds, dried flower seeds, cool season poppy, fall sow poppy Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['cool-season', 'spring', 'winter'],
        type_tags: ['cut-flower', 'cool-season', 'dried-flower', 'self-sowing'],
        is_featured: false,
        sort_order: 26,
        seo_title: 'Breadseed Poppy Seeds | Ornamental Pods & Cut Flowers | Sugar Oak Lane',
        seo_description: 'Grow Breadseed poppies — beautiful flowers and decorative seed pods for dried arrangements. Fall sow in Georgia. $3.95/packet from Sugar Oak Lane.',
        packet_quantity: 500,
        seed_details: {
          growing_instructions: 'Direct sow in fall or very early spring. Needs cold stratification — do not start indoors in warmth. Scatter over prepared soil and press in. Do not cover deeply.',
          days_to_maturity: '60–70 days from spring emergence (blooms April–May in Georgia)',
          plant_height: '3–4 feet',
          plant_spread: '12 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, moderately fertile soil; pH 6.0–7.0',
          spacing: '6–12 inches (thin seedlings)',
          sow_method: 'Direct sow in fall or early spring — needs cold to germinate well',
          hardiness_zones: 'Annual (self-sows freely)',
          best_uses: ['Cut flowers', 'Dried pod arrangements', 'Garden display', 'Dried florals'],
          harvest_tips: 'Flowers: harvest when just unfurling; sear stem end in flame. Pods: harvest when fully mature and rattling; hang to dry in bundles.',
          vase_life: '5–7 days (flowers); indefinite when dried (pods)',
          special_notes: 'Self-sows prolifically — scatter seeds where you want them to naturalize. Does not transplant well. Pods are highly decorative dried.'
        }
      },

      {
        name: 'Shirley Poppies Supreme',
        slug: 'poppy-shirley-supreme',
        sol_category: 'seeds-bulbs',
        subcategory: 'Poppies',
        flower_name: 'Poppy',
        flower_type: 'Cool Season Annual',
        short_description: 'Delicate silk-petaled Shirley poppies in a romantic mix of pink, red, white, and bicolor. ~500 seeds.',
        description: `Shirley Poppies Supreme (Papaver rhoeas) are the classic cottage garden poppies of Victorian England — delicate single blooms with silky, almost transparent petals in a romantic mix of soft pink, rosy red, white, and delicate bicolor picotees with contrasting edges. The name "Shirley" refers to the English village where Reverend William Wilks first selected the red field poppy for white-edged variants in the 1880s, and the Supreme strain carries on that tradition with larger, more refined blooms.\n\nIn the Southeast, sow Shirley poppies in fall (October through December) directly where they'll grow — cold winter temperatures help break dormancy, and the plants establish as low rosettes through winter before putting up flowering stems in early spring. Surface sow or cover very lightly with 1/8 inch of soil. Thin to 6–8 inches when seedlings are 2–3 inches tall.\n\nFor cut flowers, harvest in early morning when buds have just cracked — before petals unfurl fully. Sear stem ends in flame or hot water immediately. Vase life is 5–7 days. Shirley Poppies add irreplaceable movement and delicacy to spring arrangements — they can't be replicated or replaced by anything else in the flower world.\n\nKeywords: Shirley Poppy seeds, Papaver rhoeas, cottage garden poppy seeds, spring cut flower seeds, cool season annual, grow poppies Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['cool-season', 'spring', 'winter'],
        type_tags: ['cut-flower', 'cool-season', 'cottage-garden', 'self-sowing'],
        is_featured: false,
        sort_order: 27,
        seo_title: 'Shirley Poppies Supreme Seeds | Silk-Petal Spring Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Shirley Poppies Supreme — delicate silk petals in pink, red, white mix. Fall sow in Georgia for spring blooms. $3.95/packet from Sugar Oak Lane.',
        packet_quantity: 500,
        seed_details: {
          growing_instructions: 'Direct sow in fall or very early spring. Surface sow or cover with 1/8 inch of fine soil. Do not start indoors. Thin to 6–8 inches when established.',
          days_to_maturity: '60–70 days from spring emergence',
          plant_height: '18–24 inches',
          plant_spread: '8–10 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, average fertility soil; pH 6.0–7.0. Rich soil produces fewer flowers.',
          spacing: '6–8 inches (after thinning)',
          sow_method: 'Direct sow in fall or very early spring (does not transplant well)',
          hardiness_zones: 'Annual (self-sows readily)',
          best_uses: ['Cut flowers', 'Cottage garden', 'Spring arrangements', 'Dried petals'],
          harvest_tips: 'Harvest when bud just cracks open. Sear cut end in flame or hot water immediately. Handle gently — petals bruise easily.',
          vase_life: '5–7 days (with stem searing)',
          special_notes: 'Self-sows once established. Surface sow — seeds need light to germinate. Does not transplant — sow in final location.'
        }
      },

      // ─── COSMOS (4) ───────────────────────────────────────────────────────

      {
        name: 'Seashell Cosmos',
        slug: 'cosmos-seashell',
        sol_category: 'seeds-bulbs',
        subcategory: 'Cosmos',
        flower_name: 'Cosmos',
        flower_type: 'Annual',
        short_description: 'Unique tubular rolled petals in pink, rose, and white — cosmos unlike any other. Airy, graceful, and unusual. ~75 seeds.',
        description: `Seashell Cosmos is the cosmos that makes people stop and look twice — instead of the flat petals of standard cosmos, each petal is rolled into a tight tube, creating a flower that resembles a sea anemone or quilled paper flower. Colors span pink, rose, and white in the characteristic airy cosmos form, floating on wiry stems above feathery foliage. In arrangements, Seashell Cosmos adds movement, texture, and a quality of lightness that few other flowers can match.\n\nDirect sow after last frost in Georgia — cosmos thrives in full sun and actually prefers lean, average soil; too much fertilizer produces lush foliage but fewer flowers. Space 12–18 inches apart. Cosmos self-sows readily once established, and succession sowing every 3–4 weeks from last frost through June extends the season. Plants grow quickly, often reaching 3–4 feet and blooming 70–80 days from seed.\n\nHarvest stems when flowers are fully open — cosmos doesn't continue opening much after cutting. Cut in early morning, remove lower leaves, and place in clean water. Pairs beautifully with bupleurum, white baby's breath, and any of the zinnias for airy summer arrangements. Vase life 5–8 days.\n\nKeywords: Seashell Cosmos seeds, tubular petal cosmos, unusual cosmos, cut flower cosmos, grow cosmos from seed, Georgia annual flower seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'airy-filler', 'pollinator', 'self-sowing'],
        is_featured: false,
        sort_order: 28,
        seo_title: 'Seashell Cosmos Seeds | Tubular Petal Specialty Cosmos | Sugar Oak Lane',
        seo_description: 'Grow Seashell Cosmos — unique tubular rolled petals in pink, rose, white. Airy specialty cut flower. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 75,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun. Prefers lean soil — do not over-fertilize. Space 12–18 inches. Self-sows readily.',
          days_to_maturity: '70–80 days',
          plant_height: '3–4 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Average to lean, well-draining soil; pH 6.0–7.0. Over-rich soil reduces blooming.',
          spacing: '12–18 inches',
          sow_method: 'Direct sow (does not transplant well from pots)',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Airy arrangements', 'Pollinator garden', 'Cottage garden borders'],
          harvest_tips: 'Cut when flowers are fully open. Remove lower leaves. Place in clean water immediately. Does not continue opening much after cutting.',
          vase_life: '5–8 days',
          special_notes: 'Lean soil = more flowers. Self-sows once established. Stake in windy areas. Feathery foliage also useful as filler in arrangements.'
        }
      },

      {
        name: 'Sensation Singles Cosmos',
        slug: 'cosmos-sensation-singles',
        sol_category: 'seeds-bulbs',
        subcategory: 'Cosmos',
        flower_name: 'Cosmos',
        flower_type: 'Annual',
        short_description: 'Classic single cosmos in a full range of pink, carmine, rose, and white. Prolific, airy, and effortlessly beautiful. ~75 seeds.',
        description: `Sensation Singles Cosmos represents cosmos in its most classic form — single, open blooms with eight flat petals in a full range of pink, carmine red, rose, and white, floating on wiry stems above feathery fine-cut foliage. This is the cosmos that cottage gardeners and cut flower growers have grown for generations, and it remains irreplaceable for the lightness and movement it brings to any arrangement.\n\nCosmos thrives in Georgia's warmth and is remarkably easy to grow. Direct sow after last frost in full sun, spacing 12–18 inches. Cosmos actually prefers average to lean soil — rich, fertilized soil produces lush foliage but fewer blooms. It self-sows freely once established, creating naturalized stands that need little annual attention. Succession sow every 3–4 weeks from last frost through June for non-stop blooms.\n\nHarvest when flowers are newly opened, in the morning. Remove lower leaves and place in clean water. The airy, lightweight stems add movement to bouquets and pair with virtually any other cut flower. Mix with bupleurum, bachelor buttons, and zinnias for full summer market bouquets. Vase life 5–8 days.\n\nKeywords: Sensation Singles cosmos seeds, cosmos flowers from seed, pink cosmos, cut flower cosmos, easy annual flowers Georgia, cottage garden seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'airy-filler', 'self-sowing', 'easy-grow'],
        is_featured: false,
        sort_order: 29,
        seo_title: 'Sensation Singles Cosmos Seeds | Classic Cut Flower Mix | Sugar Oak Lane',
        seo_description: 'Grow Sensation Singles Cosmos — classic pink, carmine, rose, white mix. Easy, prolific, beautiful cut flower. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 75,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun. Average to lean soil is best. Do not over-fertilize. Thin to 12–18 inches. Self-sows freely.',
          days_to_maturity: '60–70 days',
          plant_height: '3–4 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Average, well-draining soil; pH 6.0–7.0. Lean soil = more blooms.',
          spacing: '12–18 inches',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Mixed bouquets', 'Cottage garden', 'Pollinator garden'],
          harvest_tips: 'Cut when newly open. Remove lower leaves immediately. Short vase life compared to zinnias — harvest fresh daily.',
          vase_life: '5–8 days',
          special_notes: 'One of the easiest flowers to grow from seed. Self-sows readily. Lean soil produces the most flowers. Excellent for beginners.'
        }
      },

      {
        name: 'Daydream Cosmos',
        slug: 'cosmos-daydream',
        sol_category: 'seeds-bulbs',
        subcategory: 'Cosmos',
        flower_name: 'Cosmos',
        flower_type: 'Annual',
        short_description: 'Romantic Daydream cosmos with white petals blushed rose-pink at the center — soft, dreamy, and irresistible. ~75 seeds.',
        description: `Daydream Cosmos is among the most captivating cosmos varieties — white petals that blush rose-pink at the heart of each flower, creating a soft gradient across every bloom. It's the kind of flower that looks painted rather than grown, and its gentle color combination works in virtually any arrangement from romantic wedding work to casual market bouquets. Daydream was bred specifically for this bicolor characteristic and produces it consistently and reliably.\n\nGrow like all cosmos: direct sow after last frost in full sun with lean to average soil. Rich soil produces large plants but fewer flowers — lean conditions push cosmos to bloom. Space 12–18 inches and thin promptly to avoid overcrowding. In Georgia's long growing season, succession plant every 3–4 weeks from last frost through June for continuous harvest through October.\n\nHarvest when newly opened, early morning. Daydream's soft color combination pairs exquisitely with blush lisianthus, white baby's breath, cream zinnias, and any greenery. For bridal work, it fills arrangements with a lightness that heavier flowers can't achieve. Vase life 5–8 days.\n\nKeywords: Daydream Cosmos seeds, bicolor cosmos, pink and white cosmos, wedding cosmos seeds, romantic cut flower seeds, grow cosmos Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'wedding', 'airy-filler', 'pollinator'],
        is_featured: false,
        sort_order: 30,
        seo_title: 'Daydream Cosmos Seeds | White & Pink Bicolor Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Daydream Cosmos — white petals blushed rose-pink at center. Romantic, airy cut flower. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 75,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun. Lean to average soil. Do not over-fertilize. Thin to 12–18 inches. Succession sow for extended harvest.',
          days_to_maturity: '60–70 days',
          plant_height: '3–4 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Average, well-draining soil. Lean conditions = more blooms.',
          spacing: '12–18 inches',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Romantic bouquets', 'Cut flowers', 'Airy arrangements'],
          harvest_tips: 'Cut when newly opened in early morning. The bicolor blush is most vivid on fresh blooms.',
          vase_life: '5–8 days',
          special_notes: 'Bicolor characteristic is consistent and reliable. Excellent for wedding work where lightness is essential.'
        }
      },

      {
        name: 'Purity White Cosmos',
        slug: 'cosmos-purity-white',
        sol_category: 'seeds-bulbs',
        subcategory: 'Cosmos',
        flower_name: 'Cosmos',
        flower_type: 'Annual',
        short_description: 'Pure white single cosmos — clean, luminous, and essential for any white or monochromatic bouquet. ~75 seeds.',
        description: `Purity White Cosmos delivers a clean, luminous white with a bright yellow center disk — simple, elegant, and utterly beautiful. White flowers are perennially in demand, and cosmos white is especially valuable because it adds the lightness and movement that no other white flower quite replicates. In mixed arrangements, it acts as a visual rest between colors; in white-only arrangements, it creates a cloud-like softness.\n\nGrow in full sun with direct sow after last frost. Cosmos prefers lean to average soil — over-fertilizing pushes foliage at the expense of flowers. Space 12–18 inches. Purity White is a reliable, fast-growing variety that begins blooming 60–70 days from seed. In Georgia, succession sow from last frost through early July for continuous white flowers through October.\n\nHarvest when newly opened. The clean white color holds beautifully in the vase without browning quickly. Pair with any color for impact — white cosmos against deep burgundy zinnias or amaranth creates stunning contrast; with blush and cream it creates soft, ethereal bridal work. Vase life 5–8 days. An indispensable variety for any serious cut flower garden.\n\nKeywords: Purity White Cosmos seeds, white cosmos, cosmos from seed, white cut flower seeds, airy white flower, grow cosmos Georgia Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'wedding', 'airy-filler', 'pollinator'],
        is_featured: false,
        sort_order: 31,
        seo_title: 'Purity White Cosmos Seeds | White Cut Flower Cosmos | Sugar Oak Lane',
        seo_description: 'Grow Purity White Cosmos — clean, luminous white single blooms, essential for bouquets. Easy and prolific. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 75,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun. Lean to average soil for best bloom production. Space 12–18 inches. Succession sow every 3–4 weeks.',
          days_to_maturity: '60–70 days',
          plant_height: '3–4 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Average, well-draining soil; pH 6.0–7.0',
          spacing: '12–18 inches',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'White arrangements', 'Mixed bouquets', 'Airy filler'],
          harvest_tips: 'Cut when newly opened. White holds well without browning. Pairs with any color for contrast or in white-only arrangements.',
          vase_life: '5–8 days',
          special_notes: 'Lean soil = more flowers. One of the most useful white annuals a cut flower grower can grow. Self-sows freely once established.'
        }
      },

      // ─── CELOSIA (4) ──────────────────────────────────────────────────────

      {
        name: 'Flamingo Feather Celosia',
        slug: 'celosia-flamingo-feather',
        sol_category: 'seeds-bulbs',
        subcategory: 'Celosia',
        flower_name: 'Celosia',
        flower_type: 'Annual',
        short_description: 'Elegant slender spikes of soft pink Celosia spicata — graceful, long-lasting fresh and dried. ~200 seeds.',
        description: `Flamingo Feather celosia (Celosia spicata) produces slender, tapering spikes of soft pink flowers on long, straight stems — a more refined alternative to the bold plumes and crests of other celosia types. The feathery texture is delicate and graceful, and florists prize Flamingo Feather for its ability to add vertical interest and soft pink color without overwhelming other flowers in an arrangement.\n\nThis is one of the best dual-use flowers for cut flower growers — fresh-cut, the soft pink spikes last 10–14 days in the vase; dried, they retain their color and form indefinitely, making Flamingo Feather valuable for dried floral work, wreaths, and permanent arrangements. The spikes air-dry beautifully when hung upside down in bundles.\n\nGrow in full sun after last frost. Celosia is heat-loving and will not tolerate cold — do not rush the season. Start indoors 4–6 weeks before last frost or direct sow after soil warms to 65°F. Space 12 inches apart. Harvest for fresh use when spikes are fully developed but before seeds set; harvest for drying when slightly more mature. Pairs beautifully with coral amaranth, Benary Giant Salmon Rose zinnia, and eucalyptus.\n\nKeywords: Flamingo Feather celosia seeds, Celosia spicata, pink celosia, cut flower celosia, dried flower seeds, feather celosia Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'dried-flower', 'vertical-interest'],
        is_featured: false,
        sort_order: 32,
        seo_title: 'Flamingo Feather Celosia Seeds | Spicata Pink Dried & Fresh | Sugar Oak Lane',
        seo_description: 'Grow Flamingo Feather Celosia spicata — elegant pink spikes, beautiful fresh or dried. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Start indoors 4–6 weeks before last frost or direct sow after soil reaches 65°F. Full sun. Do not rush — celosia hates cold. Space 12 inches.',
          days_to_maturity: '80–90 days',
          plant_height: '3–4 feet',
          plant_spread: '12 inches',
          sun_requirements: 'Full sun (8+ hours)',
          soil_preferences: 'Well-draining, fertile soil; pH 6.0–6.5',
          spacing: '12 inches',
          sow_method: 'Start indoors or direct sow after soil warms',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Dried arrangements', 'Wreaths', 'Farmers market'],
          harvest_tips: 'For fresh: harvest when spike is fully developed. For dried: harvest slightly more mature; hang upside down in bundles to dry.',
          vase_life: '10–14 days fresh; indefinite dried',
          special_notes: 'One of the best dual-use flowers — excellent fresh AND as a dried flower. Retains color beautifully when dried.'
        }
      },

      {
        name: 'Pampas Plume Celosia',
        slug: 'celosia-pampas-plume',
        sol_category: 'seeds-bulbs',
        subcategory: 'Celosia',
        flower_name: 'Celosia',
        flower_type: 'Annual',
        short_description: 'Feathery plume-type celosia in warm coral and salmon tones — lush texture for bold summer arrangements. ~200 seeds.',
        description: `Pampas Plume celosia produces the classic feathery plume form (Celosia argentea plumosa) in warm coral, salmon, and apricot tones — lush, velvety plumes that add rich texture and color to summer and fall arrangements. The plume form of celosia is more exuberant than the spicata type, with broader, showier flower heads that add a tropical, abundant quality to bouquets.\n\nCelosia is a true heat lover — the warmer and more humid, the better it performs, making it ideal for Georgia and Southeast growing conditions. Start indoors 4–6 weeks before last frost or direct sow after soil warms to 65°F. Full sun is non-negotiable. Space 12–15 inches apart. Once flowering begins, harvest regularly to keep plants producing new plumes.\n\nPampas Plume celosia is also excellent for drying — harvest when plumes are fully developed, strip foliage, and hang upside down in a warm, well-ventilated space. Dried plumes retain their coral-salmon color and add texture to fall wreaths and dried arrangements. Fresh vase life is 10–14 days. Pairs with sunflowers, amaranth, and rudbeckia for warm-palette summer arrangements.\n\nKeywords: Pampas Plume celosia seeds, plume celosia, coral celosia, Celosia argentea, dried flower seeds, cut flower celosia Georgia summer.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'dried-flower', 'tropical'],
        is_featured: false,
        sort_order: 33,
        seo_title: 'Pampas Plume Celosia Seeds | Coral Feather Plume Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Pampas Plume Celosia — lush feathery coral-salmon plumes, beautiful fresh or dried. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Start indoors 4–6 weeks before last frost or direct sow after soil reaches 65°F. Full sun required. Space 12–15 inches. Do not plant out until all frost risk has passed.',
          days_to_maturity: '80–85 days',
          plant_height: '2–3 feet',
          plant_spread: '12–15 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, fertile soil; pH 6.0–6.5',
          spacing: '12–15 inches',
          sow_method: 'Start indoors 4–6 weeks before last frost or direct sow after frost danger has passed',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Dried arrangements', 'Summer bouquets', 'Fall wreaths'],
          harvest_tips: 'Harvest for fresh use when plume is fully developed but before it starts to set seed. Strip lower foliage. For drying, hang upside down in bundles.',
          vase_life: '10–14 days fresh',
          special_notes: 'Heat and humidity improve performance — thrives in Georgia summers. Excellent for dried flower work.'
        }
      },

      {
        name: 'Penny Cress Celosia',
        slug: 'celosia-penny-cress',
        sol_category: 'seeds-bulbs',
        subcategory: 'Celosia',
        flower_name: 'Celosia',
        flower_type: 'Annual',
        short_description: 'Slender celosia spicata with soft rosy-pink spikes — a graceful, dainty filler for bouquets and fresh arrangements. ~200 seeds.',
        description: `Penny Cress celosia (Celosia spicata) produces slender, delicate flower spikes in soft rosy-pink on airy, branching stems — a dainty and graceful filler that adds lightness and texture to bouquets without the boldness of plume-type celosias. The narrow spikes and fine-textured foliage make Penny Cress one of the most useful bouquet fillers in the summer cut flower garden, bridging the gap between structural elements and airy cloud-like fillers.\n\nGrow in full sun after all frost danger has passed — celosia is sensitive to cold temperatures and will stall or die if planted too early. Start indoors 4–6 weeks before last frost or direct sow after soil reaches 65°F. Space 10–12 inches apart. Plants branch naturally and produce an abundance of spikes throughout the season with regular harvesting.\n\nPenny Cress dried beautifully and retains its soft pink color — a valuable bonus for mixed fresh-and-dried arrangements. Fresh vase life is 10–14 days. Pairs with Benary Giant zinnias, Queen Lime varieties, coral amaranth, and any soft-toned summer flowers for arrangements that feel complete and professionally finished.\n\nKeywords: Penny Cress celosia seeds, spicata celosia, pink celosia filler, cut flower celosia seeds, dried flower seeds, Georgia summer annual.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'dried-flower', 'filler'],
        is_featured: false,
        sort_order: 34,
        seo_title: 'Penny Cress Celosia Seeds | Spicata Pink Filler Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Penny Cress Celosia spicata — slender pink spikes, graceful filler for bouquets. Fresh and dried. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Start indoors 4–6 weeks before last frost or direct sow after soil reaches 65°F. Full sun. Space 10–12 inches. Regular harvesting promotes more spikes.',
          days_to_maturity: '80–90 days',
          plant_height: '2.5–3.5 feet',
          plant_spread: '10–12 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining fertile soil; pH 6.0–6.5',
          spacing: '10–12 inches',
          sow_method: 'Start indoors or direct sow after frost danger',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Bouquet filler', 'Cut flowers', 'Dried arrangements', 'Mixed bouquets'],
          harvest_tips: 'Harvest when spikes are fully developed. Strip lower leaves. Hang upside down for drying.',
          vase_life: '10–14 days fresh',
          special_notes: 'Excellent dual-use flower — fresh and dried. The slender spikes add elegant vertical texture to any arrangement.'
        }
      },

      {
        name: 'Supercress Celosia',
        slug: 'celosia-supercress',
        sol_category: 'seeds-bulbs',
        subcategory: 'Celosia',
        flower_name: 'Celosia',
        flower_type: 'Annual',
        short_description: 'Branching spicata celosia in creamy white-pink tones — prolific and stunning as filler or focal element. ~200 seeds.',
        description: `Supercress celosia is a vigorous, branching Celosia spicata type that produces an abundance of slender flower spikes in soft, creamy pink-to-white tones on well-branched plants. The branching habit means a single plant delivers multiple harvest-ready stems over an extended season — exceptional value for home gardens and small-scale cut flower production. The soft, neutral coloring works as both a filler and a gentle focal element in any arrangement.\n\nCelosia is among the most productive flowers for Georgia growers because it thrives in the heat and humidity that challenges other summer flowers. Plant in full sun after all frost danger has passed — soil temperature at 65°F or above. Space 12 inches for good air circulation and branching. Regular harvesting keeps plants productive through October.\n\nHarvest when spikes are fully elongated but before seeds begin to set. Supercress is also excellent for drying — hang upside down in bundles in a warm, well-ventilated area. Fresh vase life runs 10–14 days. The soft neutral color of Supercress makes it an ideal complement to any color palette, from bold jewel-toned to soft pastel.\n\nKeywords: Supercress celosia seeds, branching celosia, white celosia, spicata celosia, cut flower seeds, dried flower seeds, Georgia summer annual.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'dried-flower', 'filler', 'branching'],
        is_featured: false,
        sort_order: 35,
        seo_title: 'Supercress Celosia Seeds | Branching Spicata White-Pink | Sugar Oak Lane',
        seo_description: 'Grow Supercress Celosia — branching spicata with creamy pink-white spikes, prolific cut flower and dried. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Start indoors 4–6 weeks before last frost or direct sow after soil warms to 65°F. Full sun. Space 12 inches. Harvest regularly to maintain productivity.',
          days_to_maturity: '80–90 days',
          plant_height: '2.5–3.5 feet',
          plant_spread: '12 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining fertile soil; pH 6.0–6.5',
          spacing: '12 inches',
          sow_method: 'Start indoors or direct sow after frost danger',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flower filler', 'Dried arrangements', 'Mixed bouquets', 'Farmers market'],
          harvest_tips: 'Harvest when spikes are fully elongated. Regular harvesting encourages side branch production.',
          vase_life: '10–14 days fresh',
          special_notes: 'Branching habit makes it very productive. Neutral colors work with any palette. Excellent for drying.'
        }
      },

      // ─── AMARANTH (3) ─────────────────────────────────────────────────────

      {
        name: 'Coral Fountain Amaranth',
        slug: 'amaranth-coral-fountain',
        sol_category: 'seeds-bulbs',
        subcategory: 'Amaranth',
        flower_name: 'Amaranth',
        flower_type: 'Annual',
        short_description: 'Long draping coral-burgundy tassels of Amaranthus caudatus — cascading focal flowers for large arrangements. ~200 seeds.',
        description: `Coral Fountain amaranth (Amaranthus caudatus) produces the dramatic, draping tassels that have made love-lies-bleeding a garden classic — long, rope-like flower strings in deep coral-burgundy that cascade from tall stems in a way no other flower replicates. These draping strings, reaching 18–24 inches in length on plants 3–4 feet tall, add movement, drama, and architectural interest to large arrangements and floral installations.\n\nAmaranth is a heat lover that positively thrives in Georgia's summer conditions. Direct sow after last frost in full sun, spacing 18 inches apart to allow for the plant's large, spreading habit. The deep green foliage is also beautiful and provides additional harvest material. Plants begin producing draping tassels 75–90 days from seed and continue through frost if harvested regularly.\n\nHarvest when tassels are fully developed and draping freely. Cut stems long to maximize the cascading effect. Coral Fountain pairs magnificently with large-bloomed sunflowers, tall zinnias, and tropical foliage for statements pieces that look like professional installations. Also beautiful when draped over the edge of vases for a wild, romantic effect. Vase life 7–10 days.\n\nKeywords: Coral Fountain amaranth seeds, Amaranthus caudatus, draping amaranth, love-lies-bleeding, cut flower amaranth seeds, dramatic cut flowers Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'architectural', 'dried-flower', 'statement'],
        is_featured: false,
        sort_order: 36,
        seo_title: 'Coral Fountain Amaranth Seeds | Draping Tassels Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Coral Fountain Amaranthus caudatus — long draping coral tassels, dramatic cut flower. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun. Space 18 inches — plants get large. Water regularly until established. Full sun required for best tassel development.',
          days_to_maturity: '75–90 days',
          plant_height: '3–4 feet',
          plant_spread: '18–24 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, moderately fertile soil; pH 6.0–7.0',
          spacing: '18 inches',
          sow_method: 'Direct sow after last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Statement cut flowers', 'Large arrangements', 'Floral installations', 'Dried flower work'],
          harvest_tips: 'Cut when tassels are fully elongated and draping freely. Cut stems long. Remove lower foliage. Tassels also dry well hanging upside down.',
          vase_life: '7–10 days',
          special_notes: 'Allow tassels to fully develop before cutting — premature harvest produces limp results. Dramatic in large-scale installations and statement bouquets.'
        }
      },

      {
        name: 'Green Tails Amaranth',
        slug: 'amaranth-green-tails',
        sol_category: 'seeds-bulbs',
        subcategory: 'Amaranth',
        flower_name: 'Amaranth',
        flower_type: 'Annual',
        short_description: 'Vibrant lime-green draping tassels of Amaranthus caudatus viridis — the ultimate statement filler for modern bouquets. ~200 seeds.',
        description: `Green Tails amaranth (Amaranthus caudatus 'Viridis') produces the same dramatic draping tassels as Coral Fountain but in a vivid chartreuse-lime green that is absolutely invaluable to modern floral designers. Green cut flowers are always in high demand, and few flowers match Green Tails for sheer drama — long, cascading green ropes that add color, movement, and architectural interest simultaneously.\n\nThis variety is particularly sought after by florists working in editorial, fashion, and contemporary floral design where unusual plant material commands premium pricing. At farmers markets, Green Tails attracts experienced flower buyers who recognize its value immediately. Grow in full sun after last frost, spacing 18 inches to accommodate the large plants.\n\nHarvest when the green tassels are fully elongated and draping freely. The color is most vivid on fresh-cut stems — lime green fades slightly as it dries, transitioning to chartreuse-gold. Both stages have value. For dried work, hang upside down in bundles. Green Tails pairs with Chocolate Cherry sunflowers, burgundy dahlias, and white cosmos for high-contrast modern arrangements. Vase life 7–10 days fresh.\n\nKeywords: Green Tails amaranth seeds, green amaranth, lime green cut flower, Amaranthus caudatus viridis, dramatic cut flower seeds, modern floral design Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'architectural', 'specialty', 'dried-flower'],
        is_featured: true,
        sort_order: 37,
        seo_title: 'Green Tails Amaranth Seeds | Lime-Green Draping Tassels | Sugar Oak Lane',
        seo_description: 'Grow Green Tails Amaranth — vivid lime-green draping tassels, coveted by florists. $3.95/packet from Sugar Oak Lane Georgia farm.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Direct sow in full sun after last frost. Space 18 inches. Water at base; full sun required. Plants grow large — allow room.',
          days_to_maturity: '75–90 days',
          plant_height: '3–4 feet',
          plant_spread: '18–24 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, moderately fertile; pH 6.0–7.0',
          spacing: '18 inches',
          sow_method: 'Direct sow after last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Specialty cut flowers', 'Modern floral design', 'Statement arrangements', 'Dried florals'],
          harvest_tips: 'Cut when tassels are fully elongated. Cut stems long for maximum draping effect. Color is most vivid fresh-cut.',
          vase_life: '7–10 days fresh',
          special_notes: 'In high demand from florists — hard to source wholesale. Color transitions from lime-green when fresh to chartreuse-gold when dried — both beautiful.'
        }
      },

      {
        name: 'Hot Biscuit Amaranth',
        slug: 'amaranth-hot-biscuit',
        sol_category: 'seeds-bulbs',
        subcategory: 'Amaranth',
        flower_name: 'Amaranth',
        flower_type: 'Annual',
        short_description: 'Warm terra-cotta and buff-toned upright amaranth — rich, earthy color for fall and harvest-themed bouquets. ~200 seeds.',
        description: `Hot Biscuit amaranth (Amaranthus hybridus) produces upright, branching flower heads in warm terra-cotta, buff, and wheat tones — the color of late summer fields at golden hour. Unlike the draping types, Hot Biscuit's upright panicles create a more structured, architectural element in arrangements. The warm, earthy color palette makes it irreplaceable for fall harvest arrangements, Thanksgiving bouquets, and any design that celebrates the richness of autumn.\n\nGrow in full sun after last frost, spacing 18 inches apart. Hot Biscuit is vigorous and productive in Georgia's summer heat — this is an amaranth that embraces the conditions that challenge other flowers. Direct sow after soil warms, or start indoors 3–4 weeks before last frost. Harvest regularly to keep plants producing branching stems.\n\nFor cut flowers, harvest when the main flower head is fully developed and side branches are beginning to emerge. Cut the main stem to a strong side branch to encourage continued production. For dried work, harvest at the same stage and hang upside down to dry — the buff and terra-cotta tones hold beautifully. Vase life 7–10 days fresh. Pairs with rudbeckia, chocolate cherry sunflowers, and golden calendula.\n\nKeywords: Hot Biscuit amaranth seeds, terra cotta amaranth, fall harvest amaranth, cut flower amaranth seeds, warm-toned flowers, Georgia annual seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'dried-flower', 'architectural', 'fall-harvest'],
        is_featured: false,
        sort_order: 38,
        seo_title: 'Hot Biscuit Amaranth Seeds | Terra-Cotta Fall Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Hot Biscuit Amaranth — warm terra-cotta and buff upright blooms for fall arrangements. $3.95/packet from Sugar Oak Lane Georgia.',
        packet_quantity: 200,
        seed_details: {
          growing_instructions: 'Direct sow after last frost in full sun, or start indoors 3–4 weeks before. Space 18 inches. Harvest main stem to encourage side branching.',
          days_to_maturity: '75–85 days',
          plant_height: '3–4 feet',
          plant_spread: '18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining, moderately fertile; pH 6.0–7.0',
          spacing: '18 inches',
          sow_method: 'Direct sow or start indoors 3–4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Fall harvest arrangements', 'Dried florals', 'Cut flowers', 'Farmers market'],
          harvest_tips: 'Cut when main head is fully developed. Harvest to a side branch to encourage continued production. Dries beautifully — hang upside down.',
          vase_life: '7–10 days',
          special_notes: 'Warm earthy color is most prized for fall and harvest-themed work. Excellent for dried flower arrangements and wreaths.'
        }
      },

    ];

    for (const p of products) {
      await client.query(`
        INSERT INTO sol_products (
          name, slug, sol_category, subcategory, short_description, description,
          price, price_label, images, availability, season_tags, type_tags,
          is_featured, sort_order, flower_name, flower_type,
          seo_title, seo_description, packet_quantity, seed_details, is_active
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,true)
        ON CONFLICT (slug) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          short_description = EXCLUDED.short_description,
          price = EXCLUDED.price,
          packet_quantity = EXCLUDED.packet_quantity,
          seed_details = EXCLUDED.seed_details,
          seo_title = EXCLUDED.seo_title,
          seo_description = EXCLUDED.seo_description,
          season_tags = EXCLUDED.season_tags,
          type_tags = EXCLUDED.type_tags,
          flower_name = EXCLUDED.flower_name,
          flower_type = EXCLUDED.flower_type,
          updated_at = NOW()
      `, [
        p.name, p.slug, p.sol_category, p.subcategory, p.short_description, p.description,
        p.price, p.price_label, JSON.stringify([]), p.availability,
        p.season_tags, p.type_tags, p.is_featured, p.sort_order,
        p.flower_name, p.flower_type, p.seo_title, p.seo_description,
        p.packet_quantity, JSON.stringify(p.seed_details)
      ]);
    }

    console.log(`Seeded ${products.length} seed products (part 2)`);
  },
  down: async (client) => {
    const slugs = [
      'zinnia-benary-giant-orange','zinnia-benary-giant-golden-yellow','zinnia-benary-giant-wine',
      'zinnia-benary-giant-coral','zinnia-unicorn',
      'zinnia-queen-lime-peach','zinnia-queen-lime-blush','zinnia-queen-lime-orange','zinnia-queen-lime-red',
      'zinnia-luminosa','zinnia-isabellina',
      'poppy-iceland','poppy-breadseed','poppy-shirley-supreme',
      'cosmos-seashell','cosmos-sensation-singles','cosmos-daydream','cosmos-purity-white',
      'celosia-flamingo-feather','celosia-pampas-plume','celosia-penny-cress','celosia-supercress',
      'amaranth-coral-fountain','amaranth-green-tails','amaranth-hot-biscuit',
    ];
    await client.query(`DELETE FROM sol_products WHERE slug = ANY($1)`, [slugs]);
  }
};
