/**
 * Migration: Seed products catalog part 3 — sorts 39–54
 * Monarda, Basil (3), Clarkia, Sweet Williams, Rudbeckia (4), Calendula, Lupine (5)
 */

const products = [
  // ─── Monarda ───────────────────────────────────────────────────────────────
  {
    name: 'Lemon Mint Monarda',
    slug: 'monarda-lemon-mint',
    sol_category: 'seeds-bulbs',
    subcategory: 'Monarda',
    flower_name: 'Monarda',
    flower_type: 'Annual',
    short_description: 'Citrus-scented monarda with lavender-purple whorled blooms that draw pollinators all season long.',
    description: `Lemon Mint Monarda brings old-fashioned cottage charm and powerful pollinator appeal to the cut flower garden. The whorled flower heads feature lavender-purple tubular florets arranged in tiers along upright stems, creating an architectural beauty that stands out in fresh bouquets and dried arrangements alike.\n\nDespite the common name, this is a true annual monarda grown for both its ornamental blooms and its intensely lemony fragrance. Every leaf and stem releases a bright citrus scent when brushed, making it a sensory delight in garden paths and cutting beds. Bees, butterflies, and hummingbirds flock to the tubular flowers, making lemon mint monarda an essential inclusion in any pollinator garden in Georgia and throughout the Southeast.\n\nDirect sow seeds in early spring after last frost or in fall for winter-annual growth across USDA zones 7–9. Plants establish quickly and bloom prolifically through summer heat if given consistent moisture. Harvest stems when lower florets on the whorl begin to open for best vase life and fragrance retention. Stems dry beautifully — simply hang in small bundles in a warm, airy space for two to three weeks for long-lasting dried arrangements.\n\nAt Sugar Oak Lane we grow lemon mint monarda alongside sunflowers and cosmos, where its upright purple columns create striking contrast in both garden and vase. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'summer', 'warm-season'],
    type_tags: ['cut-flower', 'pollinator', 'fragrant', 'dried-flower', 'cottage-garden'],
    is_featured: false,
    sort_order: 39,
    seo_title: 'Lemon Mint Monarda Seeds | Pollinator Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow lemon mint monarda from seed — lavender whorled blooms, citrus fragrance, and irresistible to bees and butterflies. Perfect for Georgia cutting gardens.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Direct sow on soil surface after last frost — seeds need light to germinate. Or start indoors 6–8 weeks early. Thin to 12 inches apart. Keep soil consistently moist until established. Pinch early for bushier plants.',
      days_to_maturity: '70–80 days from transplant',
      plant_height: '24–36 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun to part shade (4–6+ hours daily)',
      soil_preferences: 'Moist, well-draining soil; pH 6.0–7.0; tolerates average fertility',
      spacing: '12 inches apart',
      sow_method: 'Direct sow (needs light) or transplant',
      hardiness_zones: 'Annual in all zones; self-sows in zones 6–9',
      best_uses: ['Cut flowers', 'Dried arrangements', 'Pollinator gardens', 'Herb gardens', 'Cottage borders'],
      harvest_tips: 'Harvest when lower whorled florets just begin to open. Strip lower leaves. Condition in cool water overnight.',
      vase_life: '7–10 days',
      special_notes: 'Strong lemon scent from all plant parts. Excellent dried — retains color and form. Edible flowers with minty-citrus flavor.'
    }
  },

  // ─── Basil ─────────────────────────────────────────────────────────────────
  {
    name: 'Bouquet Basil',
    slug: 'basil-bouquet',
    sol_category: 'seeds-bulbs',
    subcategory: 'Basil',
    flower_name: 'Basil',
    flower_type: 'Annual',
    short_description: 'Classic sweet basil with dense white flower spikes — a fragrant cut flower and culinary herb in one.',
    description: `Bouquet Basil is the florist's secret ingredient — an aromatic annual that doubles as a lush filler in fresh arrangements and a prized culinary herb in the kitchen. Unlike standard culinary basils, bouquet basil is selected specifically for its long, branching stems, dense white flower spikes, and outstanding vase longevity, making it a workhorse of the cut flower garden throughout Georgia's warm growing season.\n\nPlants grow vigorously once warm weather arrives, quickly producing bushy mounds of glossy deep-green leaves topped with elegant white flower spikes. The foliage releases a rich, classic sweet-basil fragrance with every touch, perfuming the cutting garden and the farmhouse alike. As a filler, bouquet basil adds incredible texture and an intoxicating scent to arrangements that no other foliage can match — wedding florists and farmers market vendors prize it for exactly this reason.\n\nStart seeds indoors 6–8 weeks before last frost, or direct sow after soil warms to at least 60°F. Transplant into full sun and rich soil amended with compost. Pinch flower spikes early to encourage more branching and delay bolting. Once you allow some flower spikes to develop for cutting, harvest regularly to keep plants productive through summer and into fall in the Southeast.\n\nEach packet contains approximately 250 seeds — enough to establish a generous planting for both cutting and kitchen use throughout the season.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'warm-season'],
    type_tags: ['cut-flower', 'fragrant', 'filler', 'herb', 'farmers-market'],
    is_featured: false,
    sort_order: 40,
    seo_title: 'Bouquet Basil Seeds | Fragrant Cut Flower Herb | Sugar Oak Lane',
    seo_description: 'Grow bouquet basil for fragrant white flower spikes perfect as cut flower filler. Dual-purpose — stunning in arrangements and delicious in the kitchen. Ships from Georgia.',
    packet_quantity: 250,
    seed_details: {
      growing_instructions: 'Start indoors 6–8 weeks before last frost at 70–75°F. Transplant after all frost danger passes when soil is warm. Or direct sow after last frost. Pinch flower tips early for bushier plants. Harvest regularly to extend productivity.',
      days_to_maturity: '60–75 days from transplant to first harvest',
      plant_height: '18–30 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Rich, well-draining soil amended with compost; pH 6.0–7.0; consistent moisture',
      spacing: '12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones; grows as tender perennial in zones 10+',
      best_uses: ['Cut flower filler', 'Fragrant arrangements', 'Herb gardens', 'Farmers markets', 'Wedding flowers'],
      harvest_tips: 'Harvest stem tips with flower spikes when about one-quarter of florets are open. Condition in warm water overnight. Remove foliage below waterline.',
      vase_life: '5–7 days',
      special_notes: 'Classic sweet basil fragrance perfumes any arrangement. Keep away from cold drafts — basil is cold-sensitive below 50°F.'
    }
  },
  {
    name: 'Lemon Basil',
    slug: 'basil-lemon',
    sol_category: 'seeds-bulbs',
    subcategory: 'Basil',
    flower_name: 'Basil',
    flower_type: 'Annual',
    short_description: 'Delicate white-flowered basil with intense lemon-citrus fragrance — a unique filler for summer bouquets.',
    description: `Lemon Basil is a treasure of the cutting garden — its delicate white flower spikes and small, slightly serrated leaves carry an unmistakably bright lemon-citrus fragrance that transforms any bouquet into a sensory experience. This charming annual brings both beauty and scent to summer arrangements, making it a sought-after specialty cut at farmers markets and florist studios across Georgia and the Southeast.\n\nSmaller and more refined than sweet bouquet basil, lemon basil develops airy branching stems topped with tiny white flowers that complement rather than compete with showier blooms. The citrusy foliage fragrance is released with the gentlest touch, making lemon basil an especially wonderful choice for wedding arrangements, bridal bouquets, and any flower composition where scent is as important as appearance.\n\nAs a culinary herb, lemon basil brings bright citrus notes to Thai cuisine, salads, and infused oils — making it a dual-purpose plant that earns its place in any kitchen garden as well as the cutting bed. Grow it alongside Thai basil and holy basil for a fragrant herb collection that doubles as a specialty cut flower display.\n\nSow seeds indoors 6–8 weeks before the last frost date, or direct sow after soil temperatures reach 65°F. Lemon basil thrives in Georgia's warm summers and produces continuously when harvested regularly. Each packet contains approximately 250 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'warm-season'],
    type_tags: ['cut-flower', 'fragrant', 'filler', 'herb', 'specialty'],
    is_featured: false,
    sort_order: 41,
    seo_title: 'Lemon Basil Seeds | Fragrant Citrus Cut Flower Filler | Sugar Oak Lane',
    seo_description: 'Grow lemon basil for its bright citrus fragrance and delicate white flower spikes — a specialty filler for summer bouquets and wedding flowers. Georgia-grown quality.',
    packet_quantity: 250,
    seed_details: {
      growing_instructions: 'Start indoors 6–8 weeks before last frost at 70°F. Transplant after last frost into warm soil. Or direct sow when soil reaches 65°F. Pinch to encourage branching. Harvest regularly to prevent bolting.',
      days_to_maturity: '65–75 days from transplant',
      plant_height: '12–18 inches',
      plant_spread: '10–14 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Rich, moist, well-draining soil; pH 6.0–7.0',
      spacing: '10–12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flower filler', 'Bridal bouquets', 'Fragrant arrangements', 'Herb gardens', 'Thai cooking'],
      harvest_tips: 'Harvest stem tips when first flower buds appear. Condition in warm water. Remove all foliage below waterline to prevent bacterial growth.',
      vase_life: '5–7 days',
      special_notes: 'More delicate than sweet basil; handles heat well but dislikes cold water. Excellent for edible flower garnishes — lemon flavor in leaves and flowers.'
    }
  },
  {
    name: 'Cinnamon Basil',
    slug: 'basil-cinnamon',
    sol_category: 'seeds-bulbs',
    subcategory: 'Basil',
    flower_name: 'Basil',
    flower_type: 'Annual',
    short_description: 'Striking purple-stemmed basil with pink flower spikes and warm cinnamon-spice fragrance.',
    description: `Cinnamon Basil is one of the most visually striking members of the basil family — its deep burgundy-purple stems, dark green leaves with purple veining, and rosy-pink flower spikes create a dramatic presence in both the garden and the vase. Add to this a warm, spicy cinnamon fragrance quite unlike any other plant, and you have a specialty cut flower that stops customers at the farmers market and elevates every arrangement it graces.\n\nThis ornamental-culinary basil produces tall, upright stems with dense branching and continuous flowering when harvested regularly through Georgia's long growing season. The contrast between the dark stems and the pink flower spikes makes cinnamon basil an exceptional filler for deep-toned arrangements — pair it with burgundy dahlias, wine cosmos, or chocolate sunflowers for a sumptuous late-summer bouquet with an intoxicating spicy-sweet scent.\n\nIn the kitchen, cinnamon basil adds a unique spicy warmth to fruit salads, desserts, teas, and Southeast Asian dishes. The flowers are edible and make beautiful garnishes with their subtle cinnamon-clove flavor. Grow a dedicated cutting patch alongside sweet and lemon basil for a complete spectrum of basil fragrances and stem colors that will delight florists and customers alike.\n\nSow seeds indoors 6–8 weeks before last frost, or direct sow after all frost danger has passed and soil is warm. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'warm-season'],
    type_tags: ['cut-flower', 'fragrant', 'filler', 'herb', 'specialty', 'dark-stems'],
    is_featured: false,
    sort_order: 42,
    seo_title: 'Cinnamon Basil Seeds | Fragrant Purple Stem Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow cinnamon basil — dramatic purple stems, pink flower spikes, and warm spice fragrance. A specialty cut flower filler for farmers markets and florists. Georgia-grown.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'Start indoors 6–8 weeks before last frost at 70–75°F. Transplant after last frost into warm, rich soil. Pinch for bushier growth. Harvest when 1/4 of flower spike is open.',
      days_to_maturity: '65–80 days from transplant',
      plant_height: '18–24 inches',
      plant_spread: '12–16 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Rich, well-draining soil with organic matter; pH 6.0–7.0; consistent moisture',
      spacing: '12 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flower filler', 'Dark-toned arrangements', 'Herb gardens', 'Farmers markets', 'Specialty bouquets'],
      harvest_tips: 'Cut when lower quarter of pink flower spike is open. Condition overnight in warm water. Purple stems hold color well in arrangements.',
      vase_life: '6–8 days',
      special_notes: 'Most ornamental of the basils with dramatic color. Edible flowers and leaves with cinnamon-clove flavor. Excellent dried — retains purple color.'
    }
  },

  // ─── Clarkia ───────────────────────────────────────────────────────────────
  {
    name: 'Farewell to Spring Clarkia',
    slug: 'clarkia-farewell-to-spring',
    sol_category: 'seeds-bulbs',
    subcategory: 'Clarkia',
    flower_name: 'Clarkia',
    flower_type: 'Cool Season Annual',
    short_description: 'Delicate ruffled blooms in shades of pink, lavender, and white on long cutting stems — a cool-season cut flower gem.',
    description: `Farewell to Spring Clarkia (Clarkia amoena) is one of the most charming cool-season cut flowers available for Georgia gardens, producing an abundance of delicate, tissue-paper-thin blooms in soft shades of pink, lavender, white, and bicolor blends that bring a romantic, cottage elegance to spring and early summer bouquets.\n\nNative to the Pacific Coast and named by early settlers who observed it blooming at season's end, clarkia thrives in cool weather and is best direct-sown in Georgia in early spring (February–March) or fall (September–October) for winter-annual growth. The tall, willowy stems — often reaching 24–30 inches — bear multiple buds that open sequentially over several weeks, making each stem a living bouquet in itself. This successive opening means a single harvest stem continues to provide fresh blooms for days in the vase.\n\nFor the cut flower grower, farewell to spring clarkia fills the critical gap between spring bulbs and summer annuals, providing refined pastel stems when the cutting garden needs them most. The crepe-paper blooms bring a whimsical, handcrafted quality to arrangements that resonates strongly with customers seeking natural, garden-style flowers at farmers markets and flower shares.\n\nDirect sow seeds on the soil surface (they need light to germinate) in prepared beds. Thin to 6–9 inches for best stem length. Direct sowing is strongly preferred over transplanting. Each packet contains approximately 300 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'cottage-garden', 'pastel', 'specialty'],
    is_featured: false,
    sort_order: 43,
    seo_title: 'Farewell to Spring Clarkia Seeds | Cool Season Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Farewell to Spring Clarkia for delicate ruffled blooms in spring. A beloved cool-season cut flower for Georgia gardens — direct sow in fall or early spring.',
    packet_quantity: 300,
    seed_details: {
      growing_instructions: 'Direct sow on soil surface (needs light) in early spring or fall. Barely cover with fine soil or vermiculite. Keep moist until germination. Thin to 6–9 inches. Does NOT transplant well. Prefers cool temps (50–65°F) for best bloom.',
      days_to_maturity: '70–90 days from sowing',
      plant_height: '18–30 inches',
      plant_spread: '8–12 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Well-draining, moderately fertile soil; pH 6.0–7.0; even moisture during growth',
      spacing: '6–9 inches apart',
      sow_method: 'Direct sow only (transplanting strongly discouraged)',
      hardiness_zones: 'Cool-season annual — zones 3–10; sow fall in zones 7–10',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Cottage arrangements', 'Farmers markets', 'Flower CSAs'],
      harvest_tips: 'Cut when 2–3 buds on the stem are showing color but not yet fully open. Buds continue to open in the vase. Condition in cool water overnight.',
      vase_life: '7–12 days (as buds continue to open)',
      special_notes: 'One of the best cut flowers for filling the spring gap. Do not direct sow in summer heat — bolts quickly. Excellent combined with ranunculus and sweet peas.'
    }
  },

  // ─── Sweet Williams ────────────────────────────────────────────────────────
  {
    name: 'Sweet Williams',
    slug: 'sweet-williams',
    sol_category: 'seeds-bulbs',
    subcategory: 'Sweet Williams',
    flower_name: 'Sweet William',
    flower_type: 'Cool Season Annual',
    short_description: 'Richly fragrant flat-topped clusters in crimson, pink, white, and bicolor — a classic cottage cut flower.',
    description: `Sweet Williams (Dianthus barbatus) have graced cottage gardens and cutting beds for centuries, and for good reason — their flat-topped clusters of richly fragrant blooms in deep crimson, hot pink, soft rose, snowy white, and striking bicolor combinations are among the most versatile and beloved flowers a grower can offer. Each compact flower head presents dozens of individually fringed florets packed together into a dense, colorful cushion that holds beautifully in arrangements for well over a week.\n\nThe carnation-spice fragrance of sweet williams is distinctive and deeply nostalgic, evoking grandmother's garden and old-fashioned flower shops. This scent, combined with the strong straight stems and outstanding vase life, makes sweet williams an exceptional cut flower for farmers markets, flower CSAs, and wedding florists seeking fragrant, long-lasting stems in spring and early summer.\n\nIn Georgia and the Southeast, sweet williams are best started from seed in late summer or early fall for overwintering and spring bloom. They tolerate light frosts beautifully and often bloom through February and March in zone 7–8, filling the cutting garden during the quiet season before summer annuals take hold. Alternatively, start seeds indoors 10–12 weeks before the last frost date for early spring transplants.\n\nThe mix includes a full range of the classic bicolor and solid varieties, providing a vibrant palette for spring arrangements. Each packet contains approximately 200 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season', 'winter'],
    type_tags: ['cut-flower', 'fragrant', 'cool-season', 'cottage-garden', 'bicolor'],
    is_featured: false,
    sort_order: 44,
    seo_title: 'Sweet Williams Seeds | Fragrant Cottage Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow fragrant Sweet Williams for spring cutting gardens. Richly scented bicolor clusters in crimson, pink, and white — ideal for Georgia fall planting and spring blooms.',
    packet_quantity: 200,
    seed_details: {
      growing_instructions: 'For Georgia: Start seeds in August–September; transplant to garden beds in October for spring bloom. Alternatively start indoors 10–12 weeks before last frost. Sow 1/8 inch deep at 65–70°F. Thin/transplant to 9 inches apart.',
      days_to_maturity: '150–180 days from fall sowing; 60–80 days from spring transplant',
      plant_height: '18–24 inches',
      plant_spread: '9–12 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining, moderately fertile soil; pH 6.0–7.5; avoid waterlogged soils',
      spacing: '9–12 inches apart',
      sow_method: 'Transplant (start indoors); fall sow for zones 7+',
      hardiness_zones: 'Biennial/cool annual — zones 3–9; overwinters in zones 6–9',
      best_uses: ['Cut flowers', 'Fragrant bouquets', 'Spring farmers markets', 'Cottage arrangements', 'Edging'],
      harvest_tips: 'Cut when 1/3 to 1/2 of florets in the cluster are open. Condition in warm water with flower food overnight. Strip all foliage below waterline.',
      vase_life: '10–14 days',
      special_notes: 'One of the longest-lasting cut flowers. Strong carnation-spice fragrance. Classic combination with ranunculus, tulips, and lisianthus in spring bouquets.'
    }
  },

  // ─── Rudbeckia ─────────────────────────────────────────────────────────────
  {
    name: 'Prairie Sun Rudbeckia',
    slug: 'rudbeckia-prairie-sun',
    sol_category: 'seeds-bulbs',
    subcategory: 'Rudbeckia',
    flower_name: 'Rudbeckia',
    flower_type: 'Annual',
    short_description: 'Large golden-yellow daisy blooms with a green center — a heat-loving, long-blooming cut flower for Southern gardens.',
    description: `Prairie Sun Rudbeckia is a showstopper in the late-summer cutting garden — its large, golden-yellow ray petals surrounding a distinctive chartreuse-green center create a cheerful, luminous flower that stands out in any bouquet and practically glows in afternoon light. Unlike many black-eyed Susans, Prairie Sun carries no dark central cone, giving it a lighter, more refined appearance that works beautifully in both rustic farmhouse and contemporary floral designs.\n\nAn All-America Selections winner, Prairie Sun produces an abundance of 3–4 inch blooms on strong, upright stems from midsummer through frost in Georgia's warm climate. The plants are remarkably heat-tolerant and continue blooming prolifically even during the most brutal Southern summers, making them invaluable for filling the cutting garden when other flowers struggle. Bees, butterflies, and other pollinators visit continuously, adding ecological value to the productive cutting bed.\n\nFor cut flower growers in Georgia and the Southeast, Prairie Sun rudbeckia represents exceptional value — direct sow after last frost and expect blooms in 90–100 days, with continuous cutting through fall. The sturdy stems hold well without florist support, and the flowers maintain excellent vase life when harvested at the right stage.\n\nGrow Prairie Sun alongside zinnias, sunflowers, and celosia for a classic summer farmhouse palette that customers love. Each packet contains approximately 50 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'long-blooming', 'daisy-type'],
    is_featured: false,
    sort_order: 45,
    seo_title: 'Prairie Sun Rudbeckia Seeds | Summer Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Prairie Sun Rudbeckia — golden-yellow blooms with green center on sturdy stems. Heat-tolerant summer cut flower for Georgia gardens. AAS winner.',
    packet_quantity: 50,
    seed_details: {
      growing_instructions: 'Start indoors 8–10 weeks before last frost at 70°F, or direct sow after last frost. Barely cover seeds — need light to germinate. Transplant 18 inches apart. Deadhead to encourage continuous blooming.',
      days_to_maturity: '90–100 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining soil of average fertility; pH 6.0–7.0; drought-tolerant once established',
      spacing: '18 inches apart',
      sow_method: 'Transplant or direct sow after last frost',
      hardiness_zones: 'Annual — all zones; short-lived perennial in zones 4–9',
      best_uses: ['Cut flowers', 'Summer bouquets', 'Pollinator gardens', 'Farmers markets', 'Fall arrangements'],
      harvest_tips: 'Cut when petals are fully reflexed and center cone is firm and green. Condition in cool water overnight. Excellent vase life — one of the most reliable summer cuts.',
      vase_life: '10–14 days',
      special_notes: 'Green center (no black cone) makes it more versatile than standard black-eyed Susans. Highly drought tolerant. Attractive to goldfinches in seed stage.'
    }
  },
  {
    name: 'Maya Rudbeckia',
    slug: 'rudbeckia-maya',
    sol_category: 'seeds-bulbs',
    subcategory: 'Rudbeckia',
    flower_name: 'Rudbeckia',
    flower_type: 'Annual',
    short_description: 'Compact dwarf rudbeckia with masses of golden-yellow blooms — perfect for container growing and small-space cutting gardens.',
    description: `Maya Rudbeckia delivers the cheerful golden energy of classic black-eyed Susans in a compact, dwarf form that's perfectly suited to small-space cutting gardens, container plantings, and front-of-border displays. Despite its petite stature, Maya produces masses of perfectly formed 2–3 inch golden-yellow blooms with dark chocolate centers from early summer through fall — a non-stop flowering performance that makes it one of the most productive dwarf cut flowers available.\n\nFor Georgia growers working with limited space or growing flowers on balconies, patios, or in raised beds, Maya rudbeckia is an essential variety. The compact plants rarely need staking, produce stems long enough for small bouquets and bud vases, and continue blooming enthusiastically through the hottest months of a Southern summer. Bees and butterflies visit constantly, making Maya equally valuable as a pollinator garden specimen.\n\nMaya works beautifully in mixed container plantings alongside petite zinnias, sweet alyssum, and compact cosmos for a full-season display that can be harvested continuously. In the ground, mass plantings of Maya create a solid carpet of gold that makes a stunning seasonal display while providing steady cutting material.\n\nDirect sow after last frost or start indoors 8 weeks early. Maya blooms more quickly than larger rudbeckia varieties, often reaching first bloom within 75–85 days from sowing. Each packet contains approximately 50 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'compact', 'container', 'heat-loving', 'pollinator'],
    is_featured: false,
    sort_order: 46,
    seo_title: 'Maya Rudbeckia Seeds | Dwarf Compact Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Maya Rudbeckia — compact dwarf golden-yellow blooms for small-space cutting gardens, containers, and borders. Heat-tolerant summer performer for Georgia.',
    packet_quantity: 50,
    seed_details: {
      growing_instructions: 'Start indoors 8 weeks before last frost at 68–72°F. Surface sow — seeds need light. Or direct sow after last frost. Transplant 10–12 inches apart. Deadhead to encourage non-stop blooming.',
      days_to_maturity: '75–85 days from sowing',
      plant_height: '12–18 inches',
      plant_spread: '12–15 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average to moderately fertile, well-draining soil; pH 6.0–7.0; moderate moisture',
      spacing: '10–12 inches apart',
      sow_method: 'Transplant or direct sow after last frost',
      hardiness_zones: 'Annual — all zones',
      best_uses: ['Cut flowers', 'Container gardens', 'Small space gardens', 'Bud vases', 'Pollinator borders'],
      harvest_tips: 'Cut when petals are fully open and dark center is firm. Stems may be shorter than full-size rudbeckia but excellent for small arrangements and bud vases.',
      vase_life: '8–12 days',
      special_notes: 'One of the most compact true cut-flower rudbeckias. Excellent for growers with limited space. Blooms faster than full-size varieties.'
    }
  },
  {
    name: 'Marmalade Rudbeckia',
    slug: 'rudbeckia-marmalade',
    sol_category: 'seeds-bulbs',
    subcategory: 'Rudbeckia',
    flower_name: 'Rudbeckia',
    flower_type: 'Annual',
    short_description: 'Warm golden-orange blooms with mahogany zones and dark centers — rich autumn color on strong cutting stems.',
    description: `Marmalade Rudbeckia earns its name with blooms in the warm, glowing orange of a perfectly ripe marmalade — a rich golden-orange with subtle mahogany banding near the dark central cone that catches the light like a sunset over a Georgia field. This mid-size rudbeckia variety produces an abundance of 2.5–3 inch blooms on strong, branching stems from midsummer through frost, providing some of the most sought-after autumn-tone cutting material of the season.\n\nThe warm orange color palette of Marmalade fills a specific design niche — it bridges the gap between pure golden-yellow rudbeckias and the deeper burgundy tones of late-summer dahlias and amaranths, making it an essential ingredient in fall harvest bouquets, Thanksgiving arrangements, and the rustic autumn farmhouse aesthetic that resonates so strongly with customers at fall farmers markets and harvest festivals in the South.\n\nMarmalade rudbeckia is exceptionally heat-tolerant and productive, thriving through Georgia's challenging late-summer conditions and continuing to produce cutting stems well into October and November in zones 7–8. The plants are sturdy and self-supporting, making them easy to manage in the cutting garden without the staking required by taller summer flowers.\n\nStart seeds indoors 8 weeks before last frost, or direct sow after soil warms. Succession planting every 2–3 weeks extends the harvest season. Each packet contains approximately 50 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'autumn-colors', 'daisy-type', 'long-blooming'],
    is_featured: false,
    sort_order: 47,
    seo_title: 'Marmalade Rudbeckia Seeds | Orange Autumn Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Marmalade Rudbeckia — warm golden-orange blooms with mahogany zones for fall harvest bouquets. Heat-tolerant summer cut flower for Georgia cutting gardens.',
    packet_quantity: 50,
    seed_details: {
      growing_instructions: 'Start indoors 8 weeks before last frost at 68–72°F, or direct sow after last frost. Surface sow — light aids germination. Transplant 15–18 inches apart. Deadhead spent blooms to extend season.',
      days_to_maturity: '80–90 days from sowing',
      plant_height: '18–24 inches',
      plant_spread: '15–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Well-draining average soil; pH 6.0–7.0; drought-tolerant once established',
      spacing: '15–18 inches apart',
      sow_method: 'Transplant or direct sow after last frost',
      hardiness_zones: 'Annual — all zones; short-lived perennial in zones 4–9',
      best_uses: ['Cut flowers', 'Fall harvest bouquets', 'Autumn arrangements', 'Thanksgiving displays', 'Farmers markets'],
      harvest_tips: 'Cut when petals are fully open and center is firm and dark. Harvest in the morning. Condition in cool water for 4–6 hours before arranging.',
      vase_life: '10–14 days',
      special_notes: 'Classic warm-orange for fall palette. Excellent companion to sunflowers, celosia, and amaranth for autumn harvest bouquets.'
    }
  },
  {
    name: 'Indian Summer Rudbeckia',
    slug: 'rudbeckia-indian-summer',
    sol_category: 'seeds-bulbs',
    subcategory: 'Rudbeckia',
    flower_name: 'Rudbeckia',
    flower_type: 'Annual',
    short_description: 'Extra-large golden-yellow blooms up to 6 inches across — an AAS winner with impressive cutting stems for dramatic arrangements.',
    description: `Indian Summer Rudbeckia commands attention in the garden and in the vase — its enormous blooms, measuring up to 5–6 inches across, are among the largest of any rudbeckia variety and produce the most dramatic visual impact in large-scale arrangements, event florals, and garden displays. This All-America Selections Gold Medal winner produces a profusion of single and semi-double golden-yellow blooms with classic chocolate-brown centers on long, strong stems from midsummer until frost.\n\nFor cut flower growers serving wedding and event florists, Indian Summer rudbeckia fills the gap between sunflowers and dahlias — it has the cheerful golden color of sunflowers with the more refined, daisy-like form that works in sophisticated floral compositions. The impressive stem length (often 24–30 inches) and the sheer size of the blooms make Indian Summer a premium offering at farmers markets and CSA bouquet subscriptions throughout Georgia and the Southeast.\n\nLike all rudbeckias, Indian Summer is remarkably heat-tolerant and continues performing through the hottest months of a Southern summer when more delicate flowers struggle. Plants are vigorous and productive, requiring only regular deadheading to maintain continuous bloom from July through October in most Georgia locations.\n\nStart seeds indoors 8–10 weeks before last frost for earliest blooms, or direct sow after all danger of frost has passed. Each packet contains approximately 50 seeds — enough for a generous cutting patch.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['summer', 'fall', 'warm-season'],
    type_tags: ['cut-flower', 'heat-loving', 'large-bloom', 'daisy-type', 'long-stem'],
    is_featured: true,
    sort_order: 48,
    seo_title: 'Indian Summer Rudbeckia Seeds | Extra-Large Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Indian Summer Rudbeckia — enormous 5–6 inch golden blooms on long cutting stems. AAS Gold Medal winner for Georgia summer cutting gardens.',
    packet_quantity: 50,
    seed_details: {
      growing_instructions: 'Start indoors 8–10 weeks before last frost at 70°F. Surface sow — light required for germination. Transplant 18–24 inches apart after last frost. Deadhead regularly for continuous bloom.',
      days_to_maturity: '90–100 days from sowing',
      plant_height: '24–36 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Moderately fertile, well-draining soil; pH 6.0–7.0; consistent moisture for largest blooms',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant preferred; direct sow after last frost',
      hardiness_zones: 'Annual — all zones; short-lived perennial in zones 4–9',
      best_uses: ['Cut flowers', 'Event florals', 'Large arrangements', 'Farmers markets', 'Pollinator gardens'],
      harvest_tips: 'Cut when outer petals are fully reflexed and center is firm. Blooms can reach 5–6 inches — condition in a tall bucket. Excellent vase life.',
      vase_life: '10–14 days',
      special_notes: 'AAS Gold Medal winner. Largest-bloomed rudbeckia — impressive in large-scale event florals. Semi-double forms add extra texture.'
    }
  },

  // ─── Calendula ─────────────────────────────────────────────────────────────
  {
    name: 'Summer Beauty Calendula',
    slug: 'calendula-summer-beauty',
    sol_category: 'seeds-bulbs',
    subcategory: 'Calendula',
    flower_name: 'Calendula',
    flower_type: 'Cool Season Annual',
    short_description: 'Vibrant orange and yellow daisy blooms with medicinal tradition — a cold-hardy cut flower for cool-season gardens.',
    description: `Summer Beauty Calendula is a garden classic with centuries of tradition behind it — grown equally for its cheerful orange and yellow blooms, its long cool-season cutting performance, and its well-documented medicinal properties. The Summer Beauty mix produces a range of daisy-like blooms in golden yellow, bright orange, and warm apricot, all with distinctive slightly sticky petals and a light resinous fragrance that's uniquely appealing and utterly distinctive.\n\nFor Georgia cut flower growers, calendula is an invaluable cool-season crop that bridges the gap between winter lulls and summer abundance. Direct sow in late September through November for blooms from December through April — calendula tolerates light frosts with ease and continues blooming through temperatures into the mid-20s°F in zone 7–8. This cold hardiness makes it one of the most reliable winter cut flowers available to Southern growers, filling farmers market tables when little else is blooming.\n\nBeyond its cutting value, calendula has a rich tradition in herbal medicine and natural beauty products. The petals are antifungal, antibacterial, and anti-inflammatory, widely used in salves, tinctures, and skin-care preparations. Growing calendula also provides botanical potpourri ingredients, dried petal confetti, and edible flower garnishes — the petals have a mildly spicy, herbal flavor that adds color and interest to salads and desserts.\n\nDirect sow 1/4 inch deep in fall or early spring. Thin to 9–12 inches. Harvest frequently to encourage continuous blooming. Each packet contains approximately 100 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['fall', 'winter', 'spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'medicinal', 'edible', 'pollinator'],
    is_featured: false,
    sort_order: 49,
    seo_title: 'Summer Beauty Calendula Seeds | Cool Season Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Summer Beauty Calendula for cheerful orange and yellow blooms all winter long in Georgia. Cold-hardy cut flower with medicinal herbal traditions.',
    packet_quantity: 100,
    seed_details: {
      growing_instructions: 'Direct sow 1/4 inch deep in fall (September–November in Georgia) for winter/spring bloom, or early spring. Thin to 9–12 inches. Deadhead spent blooms to encourage continuous flowering. Self-sows prolifically.',
      days_to_maturity: '50–70 days from sowing',
      plant_height: '18–24 inches',
      plant_spread: '12–18 inches',
      sun_requirements: 'Full sun (6+ hours daily)',
      soil_preferences: 'Average, well-draining soil; pH 5.5–7.0; tolerates poor soil; consistent moisture',
      spacing: '9–12 inches apart',
      sow_method: 'Direct sow (preferred) or transplant',
      hardiness_zones: 'Cool annual — all zones; frost-tolerant to mid-20s°F',
      best_uses: ['Cut flowers', 'Medicinal herb gardens', 'Edible flowers', 'Dried petals', 'Winter farmers markets'],
      harvest_tips: 'Cut when outer petals are fully open and center is tight. Resinous sap can stain — use gloves. Condition in cool water. Sap may irritate some skin.',
      vase_life: '8–12 days',
      special_notes: 'Edible and medicinal petals. Resinous sap — some people wear gloves when harvesting. Excellent self-sower — will return each year in mild climates.'
    }
  },

  // ─── Lupine ────────────────────────────────────────────────────────────────
  {
    name: 'Governor Lupine',
    slug: 'lupine-governor',
    sol_category: 'seeds-bulbs',
    subcategory: 'Lupine',
    flower_name: 'Lupine',
    flower_type: 'Cool Season Annual',
    short_description: 'Towering deep blue-violet flower spikes with a fresh sweet fragrance — a majestic cool-season cut flower.',
    description: `Governor Lupine produces magnificent towering spires of deep blue-violet flowers that command attention in both the garden and the vase. One of the tallest and most dramatic of the Russell Lupine hybrids, Governor grows to 3–4 feet with flower spikes reaching 18–24 inches in length — a truly impressive cut flower that creates vertical drama in large arrangements, event florals, and mixed bouquets.\n\nThe densely packed pea-family flowers carry a sweet, lightly honeyed fragrance that makes Governor lupine as much a sensory experience as a visual one. Bees absolutely adore lupines, visiting the spires continuously and building energy reserves during the critical spring pollination season. Growing lupines supports native bee populations in Georgia's spring landscape while providing spectacular cutting material from March through May.\n\nLupines require cool weather to perform at their best and are grown as a cool-season annual in Georgia. Sow seeds in fall (September–October) after scarifying or soaking overnight in warm water to improve germination. Transplant seedlings in November for spring bloom. The cool winter months allow lupines to establish deep root systems before flowering in late winter through spring.\n\nFor cut flower growers, Governor lupine is a premium specialty offering — the tall blue spires are rare in the spring marketplace and command premium prices at farmers markets and from florists seeking statement flowers for spring events. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'fragrant', 'tall', 'specialty', 'pollinator'],
    is_featured: true,
    sort_order: 50,
    seo_title: 'Governor Lupine Seeds | Blue Tall Cut Flower Spike | Sugar Oak Lane',
    seo_description: 'Grow Governor Lupine for towering deep blue-violet flower spikes — a rare and prized spring cut flower for Georgia gardens. Fragrant, majestic, and pollinator-friendly.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Scarify seeds by nicking with a knife or soaking 24 hours in warm water before sowing. Start indoors 6–8 weeks before transplanting or direct sow in fall. Sow 1/4 inch deep. Transplant carefully — dislikes root disturbance. Does NOT tolerate summer heat.',
      days_to_maturity: '150–180 days from fall sowing',
      plant_height: '36–48 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Well-draining, slightly acidic soil; pH 5.5–6.5; cool and moist; low fertility preferred (fixes own nitrogen)',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant or direct sow in fall; scarify seeds before sowing',
      hardiness_zones: 'Cool annual in zones 7+; perennial in zones 4–6',
      best_uses: ['Cut flowers', 'Vertical accent', 'Spring event florals', 'Specialty bouquets', 'Pollinator gardens'],
      harvest_tips: 'Cut when lower 1/3 of spike has open flowers and upper 2/3 are in bud. Remove side shoots promptly to elongate main stem. Condition in cool water overnight.',
      vase_life: '7–10 days',
      special_notes: 'Nitrogen-fixing legume — improves soil for future plantings. Seeds are toxic if ingested. Difficult to transplant — minimize root disturbance. Worth the extra care for the spectacular result.'
    }
  },
  {
    name: 'Chatelaine Lupine',
    slug: 'lupine-chatelaine',
    sol_category: 'seeds-bulbs',
    subcategory: 'Lupine',
    flower_name: 'Lupine',
    flower_type: 'Cool Season Annual',
    short_description: 'Soft rose-pink lupine spikes with cream and white tones — delicate elegance for spring cutting gardens.',
    description: `Chatelaine Lupine brings soft, feminine elegance to the spring cutting garden with its gentle rose-pink and cream bicolor flower spikes — a softer alternative to the bolder blue and red lupine varieties that creates a romantic, garden-party atmosphere in spring arrangements. The tall spires of densely packed pea-family blooms carry the characteristic lupine fragrance and provide exceptional vertical interest in mixed bouquets alongside ranunculus, sweet peas, and tulips.\n\nChatelaine is one of the classic Russell Lupine hybrids, selected for its refined color and long cutting stems that routinely reach 18–24 inches on plants growing to 3 feet tall. The soft pink tones are versatile — they complement both pale pastel spring arrangements and more saturated seasonal bouquets, making Chatelaine a workhorse variety for florists designing across multiple aesthetic directions.\n\nFor Georgia growers, Chatelaine lupine represents one of those special cool-season flowers that customers recognize as rare and beautiful — something they cannot easily find at grocery store flower departments or mass-market florists. Offering cutting-fresh lupine spires at a spring farmers market or in a CSA bouquet creates genuine excitement and builds customer loyalty for small flower farm operations throughout the South.\n\nFollow the same growing protocol as other lupine varieties: scarify seeds before sowing, direct sow or start indoors in fall, and transplant carefully to minimize root disturbance. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'fragrant', 'pastel', 'specialty'],
    is_featured: false,
    sort_order: 51,
    seo_title: 'Chatelaine Lupine Seeds | Pink Bicolor Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Chatelaine Lupine for soft rose-pink and cream flower spikes — a rare and elegant spring cut flower for Georgia cutting gardens and farmers markets.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Scarify or soak seeds 24 hours in warm water before sowing. Start indoors in fall 6–8 weeks before transplanting, or direct sow in fall. Sow 1/4 inch deep. Transplant with minimal root disturbance.',
      days_to_maturity: '150–180 days from fall sowing',
      plant_height: '30–36 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Well-draining, slightly acidic soil; pH 5.5–6.5; cool and moist; low fertility',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant or direct sow in fall; scarify seeds before sowing',
      hardiness_zones: 'Cool annual in zones 7+; perennial in zones 4–6',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Bridal florals', 'Farmers markets', 'Cottage arrangements'],
      harvest_tips: 'Cut when lower 1/3 of spike shows open flowers. Condition in cool water 4–6 hours minimum. Remove foliage below waterline.',
      vase_life: '7–10 days',
      special_notes: 'Soft rose-pink for pastel spring palette. Nitrogen-fixing — benefits soil. Seeds toxic if ingested; handle with care around children and pets.'
    }
  },
  {
    name: 'My Castle Lupine',
    slug: 'lupine-my-castle',
    sol_category: 'seeds-bulbs',
    subcategory: 'Lupine',
    flower_name: 'Lupine',
    flower_type: 'Cool Season Annual',
    short_description: 'Rich brick-red lupine spikes with warm earthy tones — a bold and unusual spring cut flower for dramatic arrangements.',
    description: `My Castle Lupine delivers rich brick-red flower spikes with warm reddish-brown undertones that are rare in the spring flower palette — a bold, distinctive color that creates immediate visual impact in arrangements and draws immediate attention at farmers markets where the more common pastel spring flowers can blend together. The tall, densely packed spires reach 18–24 inches on plants growing to 3–4 feet, providing commanding vertical structure in large-scale arrangements and event florals.\n\nThe warm brick-red tones of My Castle pair beautifully with the rich burgundy of anemones and ranunculus in early spring, then transition seamlessly into summer palette work alongside deep orange sunflowers, rust celosia, and chocolate cosmos as the seasons turn. This color versatility makes My Castle lupine a valuable addition to any cutting farm's spring lineup, providing rare tones that customers specifically seek out and remember.\n\nLike all Russell Lupine hybrids, My Castle has a delightful fragrance and is intensely attractive to bumblebees and other native pollinators during the critical spring pollination season. Growing lupines in or near the vegetable garden can improve yields of neighboring crops through nitrogen fixation and enhanced pollinator activity.\n\nSow My Castle lupine in fall in Georgia (September–October) for blooms in March through May. Scarify seeds before sowing for best germination rates. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'fragrant', 'bold-color', 'specialty'],
    is_featured: false,
    sort_order: 52,
    seo_title: 'My Castle Lupine Seeds | Red Brick Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow My Castle Lupine — rare brick-red flower spikes for bold spring arrangements. A distinctive specialty cut flower for Georgia cutting gardens and florists.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Scarify or soak seeds 24 hours before sowing. Direct sow or transplant in fall in Georgia. Sow 1/4 inch deep. Minimal root disturbance at transplant. Does not tolerate summer heat.',
      days_to_maturity: '150–180 days from fall sowing',
      plant_height: '36–48 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Well-draining, slightly acidic; pH 5.5–6.5; cool, moist; low fertility preferred',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant or direct sow in fall; scarify before sowing',
      hardiness_zones: 'Cool annual in zones 7+; perennial in zones 4–6',
      best_uses: ['Cut flowers', 'Spring event florals', 'Bold arrangements', 'Farmers markets', 'Specialty bouquets'],
      harvest_tips: 'Cut when lower 1/3 of spike is open. Condition in cool water overnight. Warm brick-red holds well without fading.',
      vase_life: '7–10 days',
      special_notes: 'Rare warm brick-red tone — unusual in spring palette. Nitrogen-fixing legume. Seeds toxic if ingested.'
    }
  },
  {
    name: 'Noble Maiden Lupine',
    slug: 'lupine-noble-maiden',
    sol_category: 'seeds-bulbs',
    subcategory: 'Lupine',
    flower_name: 'Lupine',
    flower_type: 'Cool Season Annual',
    short_description: 'Pure white lupine spires with the softest cream blush — the most elegant and versatile spring cut flower in the lupine family.',
    description: `Noble Maiden Lupine produces the purest, most elegant flower spikes in the lupine family — tall, stately white spires with the faintest cream blush at the center that make them simultaneously the most refined and the most versatile of the Russell Lupine hybrids. White lupines are prized above all other colors by wedding florists and event designers for their ability to work with any palette, any style, and any season — from bright spring celebrations to winter-white winter galas.\n\nThe creamy-white flower spikes reach 18–24 inches on plants growing to 3–4 feet, providing the commanding vertical presence that makes lupines so special in large-scale florals. In mixed bouquets, Noble Maiden white lupines create breathing room and elegance, allowing neighboring flowers to shine while contributing their own subtle beauty and fresh lupine fragrance. They work as beautifully in minimalist single-variety arrangements as in full, lush mixed spring bouquets.\n\nFor cut flower growers in Georgia, offering Noble Maiden white lupines in March and April CSA bouquets or at spring farmers markets creates genuine customer excitement — these are flowers people know from English cottage garden photographs and Pinterest boards but rarely encounter at their local market. Being the grower who brings this beauty to your community is one of the most satisfying experiences in small-scale flower farming.\n\nScarify seeds before sowing for best germination. Direct sow or start transplants in Georgia in fall. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'white', 'fragrant', 'specialty', 'wedding'],
    is_featured: true,
    sort_order: 53,
    seo_title: 'Noble Maiden White Lupine Seeds | Elegant Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Noble Maiden White Lupine — pure white-cream spires for weddings and spring arrangements. The most elegant and versatile spring cut flower for Georgia gardens.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Scarify or soak 24 hours before sowing. Direct sow or start indoors in fall in Georgia. Sow 1/4 inch deep. Transplant carefully — minimal root disturbance. Cannot tolerate summer heat.',
      days_to_maturity: '150–180 days from fall sowing',
      plant_height: '30–36 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun to light shade',
      soil_preferences: 'Well-draining, slightly acidic; pH 5.5–6.5; cool and moist; low fertility preferred',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant or direct sow in fall; scarify before sowing',
      hardiness_zones: 'Cool annual in zones 7+; perennial in zones 4–6',
      best_uses: ['Cut flowers', 'Wedding florals', 'White arrangements', 'Specialty bouquets', 'Spring events'],
      harvest_tips: 'Cut when lower 1/3 of spike is open. Condition in cool water. White petals show bruising — handle gently. One of the most prized spring specialty cuts.',
      vase_life: '7–10 days',
      special_notes: 'Most versatile lupine for florists — white works with any palette. Seeds toxic if ingested. Beloved by bees. Nitrogen-fixing — soil-improving.'
    }
  },
  {
    name: 'Chandelier Lupine',
    slug: 'lupine-chandelier',
    sol_category: 'seeds-bulbs',
    subcategory: 'Lupine',
    flower_name: 'Lupine',
    flower_type: 'Cool Season Annual',
    short_description: 'Warm yellow lupine spikes glowing with buttery golden tones — a rare and luminous spring cut flower.',
    description: `Chandelier Lupine glows like candlelight in the spring garden — its warm, buttery yellow flower spikes have a luminous quality that genuinely seems to radiate light, especially in the soft, golden hours of a spring morning or late afternoon. This Russell Lupine hybrid produces tall, densely packed spires in soft yellow with warm cream undertones on plants growing to 3–4 feet, filling the spring palette with a color that's rare, distinctive, and immediately noticed by customers at farmers markets and flower shares.\n\nYellow lupines occupy an unusual and valuable position in the spring flower palette — they bridge the gap between the pure whites and pastels of ranunculus, sweet peas, and anemones and the bold saturated tones of purple governor and red my castle lupines. In mixed spring bouquets, Chandelier yellow lupines bring warmth and brightness without competing with neighboring flowers, acting as a luminous accent that elevates every stem around it.\n\nPaired with spring blooms like 'Cafe au Lait' ranunculus, peach sweet peas, and white snapdragons, Chandelier lupine creates arrangements with a warm, sun-drenched quality that resonates powerfully in spring wedding work and farmers market bouquets aimed at customers who want something beyond the typical spring pastel.\n\nGrow Chandelier using standard lupine protocol — scarify seeds, direct sow or transplant in Georgia fall, and position where it won't be disturbed during summer cleanup. Each packet contains approximately 30 seeds.`,
    price: 3.95,
    price_label: '$3.95 per packet',
    images: '[]',
    availability: 'in_stock',
    season_tags: ['spring', 'cool-season'],
    type_tags: ['cut-flower', 'cool-season', 'fragrant', 'yellow', 'specialty'],
    is_featured: false,
    sort_order: 54,
    seo_title: 'Chandelier Yellow Lupine Seeds | Spring Cut Flower | Sugar Oak Lane',
    seo_description: 'Grow Chandelier Lupine — warm buttery yellow flower spikes that glow in spring arrangements. A rare and luminous spring cut flower for Georgia gardens and florists.',
    packet_quantity: 30,
    seed_details: {
      growing_instructions: 'Scarify or soak seeds 24 hours before sowing. Start indoors in fall or direct sow in fall in Georgia. Sow 1/4 inch deep. Transplant with great care to minimize root disturbance. Cannot tolerate summer heat.',
      days_to_maturity: '150–180 days from fall sowing',
      plant_height: '30–36 inches',
      plant_spread: '18–24 inches',
      sun_requirements: 'Full sun to light shade (4–6+ hours daily)',
      soil_preferences: 'Well-draining, slightly acidic; pH 5.5–6.5; cool and moist; low to moderate fertility',
      spacing: '18–24 inches apart',
      sow_method: 'Transplant or direct sow in fall; scarify before sowing',
      hardiness_zones: 'Cool annual in zones 7+; perennial in zones 4–6',
      best_uses: ['Cut flowers', 'Spring bouquets', 'Event florals', 'Farmers markets', 'Warm-palette arrangements'],
      harvest_tips: 'Cut when lower 1/3 of spike is fully open. Condition in cool water overnight. Yellow tones are luminous and hold well in the vase.',
      vase_life: '7–10 days',
      special_notes: 'One of the rarest lupine colors — highly sought-after by florists. Seeds toxic if ingested. Luminous yellow glows in photographs. Nitrogen-fixing legume.'
    }
  }
];

module.exports = {
  name: 'seed_products_catalog_3',
  up: async (client) => {
    for (const p of products) {
      await client.query(
        `INSERT INTO sol_products (
          name, slug, sol_category, subcategory, short_description, description,
          price, price_label, images, availability, season_tags, type_tags,
          is_featured, sort_order, flower_name, flower_type,
          seo_title, seo_description, packet_quantity, seed_details, is_active
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,true)
        ON CONFLICT (slug) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          short_description = EXCLUDED.short_description,
          price = EXCLUDED.price,
          packet_quantity = EXCLUDED.packet_quantity,
          seed_details = EXCLUDED.seed_details,
          seo_title = EXCLUDED.seo_title,
          seo_description = EXCLUDED.seo_description,
          season_tags = EXCLUDED.season_tags,
          type_tags = EXCLUDED.type_tags,
          flower_name = EXCLUDED.flower_name,
          flower_type = EXCLUDED.flower_type,
          subcategory = EXCLUDED.subcategory,
          is_featured = EXCLUDED.is_featured,
          sort_order = EXCLUDED.sort_order,
          updated_at = NOW()`,
        [
          p.name, p.slug, p.sol_category, p.subcategory, p.short_description, p.description,
          p.price, p.price_label, JSON.stringify([]), p.availability,
          p.season_tags, p.type_tags, p.is_featured, p.sort_order,
          p.flower_name, p.flower_type, p.seo_title, p.seo_description,
          p.packet_quantity, JSON.stringify(p.seed_details)
        ]
      );
    }
    console.log(`Seeded ${products.length} products (sorts 39–54)`);
  },
  down: async (client) => {
    const slugs = products.map(p => p.slug);
    await client.query(`DELETE FROM sol_products WHERE slug = ANY($1)`, [slugs]);
    console.log(`Removed ${slugs.length} products (sorts 39–54)`);
  }
};
