// Migration: Seed 70 flower/herb seed varieties for Sugar Oak Lane
// All priced at $3.95/packet with Floret-style growing detail

module.exports = {
  name: 'seed_products_catalog',
  up: async (client) => {
    const products = [

      // ─── SUNFLOWERS (7) ───────────────────────────────────────────────────

      {
        name: 'ProCut Orange Sunflower',
        slug: 'sunflower-procut-orange',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Pollen-free single-stem sunflower with rich golden-orange petals — the florist gold standard. ~30 seeds.',
        description: `ProCut Orange sunflower seeds produce the gold standard of cut flower sunflowers — a single-stem, pollen-free variety beloved by florists, farmers market growers, and home gardeners throughout the Southeast. Rich golden-orange petals surround a bold black seed-disk center, creating that classic, timeless sunflower look every customer recognizes and loves.\n\nBecause ProCut Orange is pollen-free, there's no yellow dust on hands, tablecloths, or finished arrangements — a must for wedding florists and event designers who need pristine blooms. At Sugar Oak Lane, we grow ProCut Orange as part of our succession-planted cut flower program, and it delivers season after season.\n\nDirect sow seeds 1 inch deep in full sun after your last frost date, spacing plants 6 inches apart for tight production-style single stems. In Georgia and across the Southeast, sow from April through July for blooms from June through September. With just 55–60 days from seed to bloom, ProCut Orange delivers a fast, reliable return. Harvest stems when the outermost ring of petals is fully unfurled but before the center fully opens — early morning is ideal. Expect 7–10 days of vase life with fresh water and a clean cut.\n\nKeywords: ProCut Orange sunflower seeds, pollen-free sunflower, cut flower sunflower seeds, grow sunflowers from seed, single stem sunflower Georgia Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'single-stem'],
        is_featured: true,
        sort_order: 1,
        seo_title: 'ProCut Orange Sunflower Seeds | Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow pollen-free ProCut Orange sunflowers from seed — rich golden blooms on long stems. Perfect for florists & farmers markets. $3.95/packet.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep after last frost when soil reaches 60°F. Firm soil over seeds. Water consistently until germination (7–10 days).',
          days_to_maturity: '55–60 days',
          plant_height: '4–5 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (6+ hours daily)',
          soil_preferences: 'Well-draining, fertile soil; pH 6.0–7.5. Amend with compost before planting.',
          spacing: '6 inches for single-stem production; 12–18 inches for branching side shoots',
          sow_method: 'Direct sow (can start indoors 2–3 weeks before last frost)',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Farmers market', 'Wedding bouquets', 'Centerpieces'],
          harvest_tips: 'Cut when outermost petals are fully open but center disk is still tight. Harvest in early morning. Recut stems and place in cool water immediately.',
          vase_life: '7–10 days',
          special_notes: 'Pollen-free variety — no yellow dust on petals, hands, or table linens. Ideal for allergy-sensitive events. Succession sow every 2 weeks for continuous harvest.'
        }
      },

      {
        name: 'ProCut White Nite Sunflower',
        slug: 'sunflower-procut-white-nite',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Creamy white, pollen-free single-stem sunflower with a striking dark center. Elegant in any bouquet. ~30 seeds.',
        description: `ProCut White Nite is the pale, sophisticated cousin in the ProCut family — a single-stem, pollen-free sunflower with creamy ivory-white petals and a dramatic near-black center disk. The contrast is stunning, and it photographs beautifully for editorial and wedding work. White sunflowers have become increasingly popular with modern florists seeking a softer palette, and ProCut White Nite delivers consistently long, straight stems perfect for large arrangements.\n\nGrow this variety just like any ProCut sunflower: direct sow in full sun after last frost, spacing 6 inches apart for single-stem production. In the Southeast, sow April through July for blooms from June through early September. Days to bloom run 55–60, making it one of the fastest sunflowers you'll grow. Being pollen-free means no messy yellow on petals or surfaces — critical for wedding work.\n\nHarvest when the outermost petals are fully open and reflexed but before the center opens. Condition overnight in cool water for maximum vase life of 7–10 days. White Nite pairs beautifully with blush zinnias, garden roses, and greenery for a romantic summer palette.\n\nKeywords: ProCut White Nite sunflower seeds, white sunflower seeds, pollen-free white sunflower, cut flower sunflower seeds, grow sunflowers from seed Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'single-stem'],
        is_featured: false,
        sort_order: 2,
        seo_title: 'ProCut White Nite Sunflower Seeds | Pollen-Free White | Sugar Oak Lane',
        seo_description: 'Grow creamy white ProCut White Nite sunflowers from seed — pollen-free, single stem, stunning dark center. $3.95/packet. Ships from Georgia.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep after last frost when soil reaches 60°F. Keep consistently moist until germination (7–10 days). Thin to 6 inches for single-stem production.',
          days_to_maturity: '55–60 days',
          plant_height: '4–5 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (6+ hours daily)',
          soil_preferences: 'Well-draining fertile soil; pH 6.0–7.5',
          spacing: '6 inches for single stems; 18 inches for branching',
          sow_method: 'Direct sow preferred',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding bouquets', 'Cut flowers', 'Farmers market', 'Romantic arrangements'],
          harvest_tips: 'Harvest when outer petals are fully open and reflexed but center disk remains closed. Recut stems at an angle and condition in cool water overnight.',
          vase_life: '7–10 days',
          special_notes: 'Pollen-free — perfect for allergies and white linen tablescapes. Pairs beautifully with blush zinnias, eucalyptus, and garden roses.'
        }
      },

      {
        name: 'ProCut Red Sunflower',
        slug: 'sunflower-procut-red',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Dramatic deep red, pollen-free single-stem sunflower. Rich burgundy-red petals on straight, strong stems. ~30 seeds.',
        description: `ProCut Red brings drama to the sunflower world — deep burgundy-red petals with a dark center create a striking, bold flower that commands attention in any arrangement. Florists love this pollen-free single-stem variety for fall bouquets, rustic weddings, and farmers market display where strong color sells quickly. The rich red tone pairs effortlessly with orange cosmos, chocolate amaranth, and deep purple zinnias for a harvest palette that looks incredible on any table.\n\nThis is an excellent sunflower for Southeast growers. Direct sow after last frost in a sunny spot with well-draining soil, spacing plants 6 inches apart for tight single-stem production. Sow successions every 2–3 weeks from April through July for continuous blooms. Days to first bloom average 55–60, making ProCut Red one of the faster season-extenders in your cut garden.\n\nHarvest when petals are fully open but the center disk is still firm and closed. Cut in early morning for maximum water uptake, and condition overnight in a cool bucket. Vase life runs 7–10 days with proper care. Pollen-free means no mess on linens — a professional detail customers notice.\n\nKeywords: ProCut Red sunflower seeds, red sunflower seeds, cut flower sunflower seeds, deep red sunflower grow from seed, Georgia flower farm seeds.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'single-stem'],
        is_featured: false,
        sort_order: 3,
        seo_title: 'ProCut Red Sunflower Seeds | Deep Burgundy Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow ProCut Red deep burgundy sunflowers from seed — pollen-free, single-stem, stunning for fall arrangements. $3.95/packet from Sugar Oak Lane.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep after last frost. Full sun required. Space 6 inches apart for single-stem production. Water regularly until established.',
          days_to_maturity: '55–60 days',
          plant_height: '4–5 feet',
          plant_spread: '12 inches',
          sun_requirements: 'Full sun (6+ hours)',
          soil_preferences: 'Well-draining fertile soil; pH 6.0–7.5',
          spacing: '6 inches for single stems; 18 inches for branching side shoots',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Fall arrangements', 'Farmers market', 'Rustic weddings'],
          harvest_tips: 'Harvest when petals are fully open but center disk is still closed and firm. Cut early morning. Recut stems and place in clean water.',
          vase_life: '7–10 days',
          special_notes: 'Pollen-free. Pairs beautifully with orange cosmos, chocolate amaranth, and burgundy zinnias for fall harvest palettes.'
        }
      },

      {
        name: 'ProCut Plum Sunflower',
        slug: 'sunflower-procut-plum',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Rare plum-purple bicolor sunflower — pollen-free single stems with golden tips fading to deep plum. ~30 seeds.',
        description: `ProCut Plum is the most distinctive variety in the ProCut series — a stunning bicolor sunflower with petals that transition from golden yellow tips to deep mahogany-plum at the base, surrounding a near-black center disk. This unusual color combination makes ProCut Plum a standout at farmers markets and an instant conversation piece at weddings and events. Florists seeking something unexpected will find this variety invaluable.\n\nAs with all ProCut varieties, this is a pollen-free, single-stem type bred specifically for cut flower production. Grow in full sun with rich, well-draining soil. Direct sow after last frost spacing 6 inches apart for single stems, or 18 inches for branching. In Georgia and the Southeast, sow April through July for summer and early fall blooms. Days to maturity run 55–65 — slightly longer than standard ProCut varieties as the more complex pigmentation develops.\n\nHarvest when petals are fully open and the bicolor patterning is at its most vibrant — before the center disk starts to shed. Cut in early morning, recut stems at an angle, and condition overnight in cool water. Pairs magnificently with Queen Lime zinnias, lisianthus, and chocolate amaranth for modern, fashion-forward arrangements.\n\nKeywords: ProCut Plum sunflower seeds, bicolor sunflower seeds, plum sunflower, unusual sunflower varieties, cut flower sunflower seeds Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'single-stem', 'unique-color'],
        is_featured: true,
        sort_order: 4,
        seo_title: 'ProCut Plum Sunflower Seeds | Bicolor Plum & Gold | Sugar Oak Lane',
        seo_description: 'Grow rare ProCut Plum bicolor sunflowers from seed — plum to gold petals, pollen-free, single stem. $3.95/packet. Georgia flower farm.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep after last frost in full sun. Space 6 inches for single stems. Keep soil moist until germination (7–10 days).',
          days_to_maturity: '55–65 days',
          plant_height: '4–5 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (6+ hours)',
          soil_preferences: 'Fertile, well-draining soil; pH 6.0–7.5. Compost amendment recommended.',
          spacing: '6 inches for single stems; 18 inches for branching',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Specialty market bouquets', 'Wedding flowers', 'Unique arrangements'],
          harvest_tips: 'Harvest when bicolor petals are fully extended and vibrant. Cut before center opens. Condition in cool water overnight.',
          vase_life: '7–10 days',
          special_notes: 'Pollen-free. The bicolor pattern is most vivid in cooler temperatures. Harvest promptly for best color intensity.'
        }
      },

      {
        name: 'Sunrich Gold Sunflower',
        slug: 'sunflower-sunrich-gold',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Pollen-free branching sunflower in pure golden yellow. Multiple stems per plant — perfect for home gardens. ~30 seeds.',
        description: `Sunrich Gold is a branching sunflower variety that produces multiple stems per plant — making it ideal for home cut gardens where you want to maximize production without planting an entire field. Rich, pure golden-yellow petals surround a lighter center for a cheery, classic sunflower appearance. Being pollen-free, Sunrich Gold is mess-free for indoor use and won't stain fabrics or cause sneezing.\n\nUnlike the single-stem ProCut series, Sunrich Gold branches freely when given adequate spacing. Plant 12–18 inches apart in full sun, direct sow after last frost, and watch the plant develop multiple flowering lateral shoots over the season. This makes it excellent for home gardeners who want a longer harvest window from fewer plants. In the Southeast, succession sow from April through June for blooms from mid-summer through October.\n\nWith 55–60 days to first bloom, Sunrich Gold is fast and productive. Harvest when petals are fully unfurled and the center disk is still firm. Side shoots will continue producing blooms throughout the season as you harvest. Vase life averages 7–10 days with regular water changes. Pair Sunrich Gold with warm-toned dahlias, orange celosia, and rudbeckia for summer abundance.\n\nKeywords: Sunrich Gold sunflower seeds, branching sunflower, pollen-free sunflower seeds, golden yellow sunflower, grow sunflowers from seed, Georgia cut flower garden.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'branching', 'pollinator'],
        is_featured: false,
        sort_order: 5,
        seo_title: 'Sunrich Gold Sunflower Seeds | Branching Pollen-Free | Sugar Oak Lane',
        seo_description: 'Grow Sunrich Gold branching sunflowers from seed — pure golden, pollen-free, multiple stems per plant. $3.95/packet. Ships from Georgia.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep after last frost in full sun. Space 12–18 inches apart to encourage branching. Water at base; avoid overhead watering on flowers.',
          days_to_maturity: '55–60 days',
          plant_height: '4–6 feet',
          plant_spread: '18–24 inches',
          sun_requirements: 'Full sun (6+ hours)',
          soil_preferences: 'Rich, well-draining soil; pH 6.0–7.5. Fertilize lightly mid-season.',
          spacing: '12–18 inches for branching production',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Home cut garden', 'Mixed bouquets', 'Pollinator garden', 'Farmers market'],
          harvest_tips: 'Harvest primary stem first to encourage side shoot production. Cut when petals are fully open. Regular harvesting keeps plants producing.',
          vase_life: '7–10 days',
          special_notes: 'Branching habit means more blooms per plant over a longer season. Excellent choice for small-space cut flower gardens.'
        }
      },

      {
        name: 'Sunrich Orange Sunflower',
        slug: 'sunflower-sunrich-orange',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Vivid orange pollen-free branching sunflower. Multiple stems per plant, rich warm color. Perfect for fall palettes. ~30 seeds.',
        description: `Sunrich Orange delivers the warmth and energy of vivid orange in a pollen-free, branching sunflower that's incredibly productive. Bright orange petals — deeper and richer than Sunrich Gold — surround a golden-brown center disk, creating flowers that photograph beautifully and sell fast at farmers markets. The branching habit means multiple stems per plant, giving home growers more blooms from fewer seeds.\n\nThis is a workhorse variety for the Southeast cut flower garden. Direct sow in full sun after last frost, spacing 12–18 inches apart to encourage the branching that makes this variety so productive. Sow successions April through June for blooms from mid-summer through October. Days to first bloom average 55–60. As you harvest primary stems, side branches activate and produce wave after wave of orange blooms.\n\nHarvest when petals are fully extended and reflexed but the center disk remains firm. Pollen-free means no orange dust on linens or skin. Sunrich Orange pairs perfectly with Chocolate Cherry sunflowers, amaranth, and fall-toned zinnias for rich harvest arrangements that capture the season.\n\nKeywords: Sunrich Orange sunflower seeds, orange sunflower seeds, branching sunflower, pollen-free sunflower, cut flower seeds, Georgia flower farm.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollen-free', 'branching'],
        is_featured: false,
        sort_order: 6,
        seo_title: 'Sunrich Orange Sunflower Seeds | Branching Pollen-Free | Sugar Oak Lane',
        seo_description: 'Grow vivid orange Sunrich Orange sunflowers from seed — pollen-free, branching, multiple stems per plant. $3.95/packet from Sugar Oak Lane.',
        packet_quantity: 30,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep in full sun after last frost. Space 12–18 inches for branching. Fertilize with balanced fertilizer at planting and again at 30 days.',
          days_to_maturity: '55–60 days',
          plant_height: '4–6 feet',
          plant_spread: '18–24 inches',
          sun_requirements: 'Full sun (6+ hours)',
          soil_preferences: 'Fertile, well-draining soil; pH 6.0–7.5',
          spacing: '12–18 inches',
          sow_method: 'Direct sow',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Fall bouquets', 'Farmers market', 'Harvest arrangements'],
          harvest_tips: 'Harvest when petals are fully open and reflexed. Cut primary stem to activate side branches. Change vase water every 2–3 days.',
          vase_life: '7–10 days',
          special_notes: 'Pollen-free. Particularly beautiful in fall-themed arrangements with amber, rust, and deep red tones.'
        }
      },

      {
        name: 'Chocolate Cherry Sunflower',
        slug: 'sunflower-chocolate-cherry',
        sol_category: 'seeds-bulbs',
        subcategory: 'Sunflowers',
        flower_name: 'Sunflower',
        flower_type: 'Annual',
        short_description: 'Stunning bicolor sunflower — deep chocolate-cherry petals with golden yellow tips and a dark center. Branching habit. ~25 seeds.',
        description: `Chocolate Cherry sunflower is arguably the most sought-after specialty sunflower for cut flower growers — a branching variety producing multiple stems with rich, chocolatey-burgundy petals edged in gold and surrounding a nearly black center disk. The combination is mesmerizing and completely unlike any standard sunflower. Florists, farmers market vendors, and home gardeners who discover this variety become devoted fans immediately.\n\nChocolate Cherry is a branching sunflower that produces abundantly when given proper spacing of 18–24 inches in full sun. The plants grow larger than single-stem varieties, reaching 4–6 feet, and deliver wave after wave of the distinctive bicolor blooms throughout the season. In Georgia and the Southeast, direct sow from April through late June. Days to first bloom average 60–70 days — slightly longer than ProCut types but absolutely worth the wait.\n\nNote that Chocolate Cherry does produce some pollen, so handle stems carefully for white fabric events. Harvest when petals are fully open and the bicolor pattern is vivid — before the center fully opens. Vase life runs 7–10 days. This variety pairs with nearly everything: coral cosmos, Queen Lime zinnias, Green Tails amaranth, and bupleurum for design that feels layered and sophisticated.\n\nKeywords: Chocolate Cherry sunflower seeds, bicolor sunflower, branching sunflower, dark sunflower seeds, cut flower sunflower, unique sunflower varieties Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'branching', 'unique-color', 'pollinator'],
        is_featured: true,
        sort_order: 7,
        seo_title: 'Chocolate Cherry Sunflower Seeds | Bicolor Dark Burgundy | Sugar Oak Lane',
        seo_description: 'Grow Chocolate Cherry bicolor sunflowers — deep burgundy-chocolate petals with gold tips. Branching, stunning, unique. $3.95/packet from Georgia.',
        packet_quantity: 25,
        seed_details: {
          growing_instructions: 'Direct sow 1 inch deep in full sun after last frost. Space 18–24 inches apart to encourage branching and air circulation. Stake in windy areas.',
          days_to_maturity: '60–70 days',
          plant_height: '4–6 feet',
          plant_spread: '18–24 inches',
          sun_requirements: 'Full sun (6+ hours)',
          soil_preferences: 'Rich, well-draining soil; pH 6.0–7.5. Heavy feeder — amend with compost.',
          spacing: '18–24 inches',
          sow_method: 'Direct sow (can start indoors 2–3 weeks before last frost)',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Specialty bouquets', 'Farmers market', 'Wedding flowers', 'Fall arrangements'],
          harvest_tips: 'Harvest when petals are fully open and bicolor pattern is vivid. Center should still be closed. Recut stems at an angle; condition in cool water overnight.',
          vase_life: '7–10 days',
          special_notes: 'Not pollen-free — use with care on white fabrics. Color intensity varies with temperature; cooler weather deepens the chocolate tones.'
        }
      },

      // ─── ZINNIAS (17) ─────────────────────────────────────────────────────

      {
        name: 'Benary Giant Scarlet Zinnia',
        slug: 'zinnia-benary-giant-scarlet',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Vivid scarlet Benary Giant zinnia with large 4–5 inch blooms and exceptional powdery mildew resistance. ~50 seeds.',
        description: `Benary Giant Scarlet zinnia is the backbone of any serious cut flower garden — vivid fire-engine scarlet blooms measuring 4–5 inches across on strong, straight stems perfectly suited for bouquets. The Benary Giant series was developed specifically for cut flower production, with exceptional disease resistance, long strong stems, and blooms that hold their color beautifully in the vase. Scarlet is the loudest and most impactful color in the series.\n\nThis is a hot-weather champion that thrives in the Georgia summer heat, producing prolifically from June through frost when succession planted. Direct sow after last frost or start indoors 4 weeks before your last frost date. Space 12–15 inches apart in full sun — closer spacing encourages longer stems as plants compete slightly for light. Pinch seedlings at 8–12 inches to encourage branching and more stems.\n\nHarvest zinnias at the "wiggle test" stage: hold the stem 8 inches below the bloom and wiggle gently — if the stem is limp, wait another day; if it's firm, harvest now. Cut to a lateral node just above a leaf set to encourage additional branching. Vase life runs 10–14 days with flower food and regular water changes. Succession plant every 2–3 weeks for continuous supply from June through October.\n\nKeywords: Benary Giant Scarlet zinnia seeds, red zinnia seeds, cut flower zinnia, zinnia from seed, Benary zinnia, heat-loving flowers Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'disease-resistant'],
        is_featured: false,
        sort_order: 8,
        seo_title: 'Benary Giant Scarlet Zinnia Seeds | Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Scarlet zinnias from seed — vivid red 4-5 inch blooms, disease-resistant, outstanding cut flower. $3.95/packet. Georgia farm.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow after last frost or start indoors 4 weeks prior. Sow 1/4 inch deep. Pinch at 8–12 inches for more stems. Do not over-water — zinnias prefer drier conditions once established.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (8+ hours for best performance)',
          soil_preferences: 'Well-draining soil; pH 5.5–7.0. Avoid overly rich soil which encourages foliage over flowers.',
          spacing: '12–15 inches (closer spacing = longer stems)',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones; thrives in heat',
          best_uses: ['Cut flowers', 'Farmers market', 'Pollinator gardens', 'Bouquets', 'Wedding flowers'],
          harvest_tips: 'Use the wiggle test: hold stem 8 inches below bloom — if firm, harvest now; if limp, wait a day. Cut above a leaf node to encourage branching.',
          vase_life: '10–14 days',
          special_notes: 'Highly powdery mildew resistant. Avoid overhead watering. Deadhead or harvest regularly to maximize bloom production through season.'
        }
      },

      {
        name: 'Benary Giant Deep Red Zinnia',
        slug: 'zinnia-benary-giant-deep-red',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Rich deep burgundy-red Benary Giant zinnia — darker and more sophisticated than scarlet. ~50 seeds.',
        description: `Benary Giant Deep Red offers the depth and sophistication that scarlet cannot — a true deep burgundy-red that photographs richly and pairs with blush, cream, and green for a timeless, elegant palette. Like all Benary Giants, these blooms measure 4–5 inches across on long strong stems with outstanding powdery mildew resistance, making them a reliable performer through Georgia's humid summers.\n\nGrow exactly like other Benary Giants: direct sow after last frost in full sun, spacing 12–15 inches apart. Start indoors 4 weeks before last frost for earlier blooms. The deep red coloring is most intense when grown in hot, direct sun — partial shade can cause the color to fade toward a lighter red. Pinch plants at 8–12 inches tall to encourage multiple branching stems for a bigger harvest.\n\nHarvest at the wiggle test stage (firm stem when held 8 inches below bloom). Cut just above a leaf node to promote reblooming. Vase life is 10–14 days with proper conditioning. Deep Red pairs beautifully with peach and salmon zinnias, coral cosmos, and green bupleurum for arrangements that feel rich and curated without being heavy.\n\nKeywords: Benary Giant Deep Red zinnia seeds, dark red zinnia, burgundy zinnia seeds, cut flower zinnia seeds, grow zinnias from seed Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'disease-resistant'],
        is_featured: false,
        sort_order: 9,
        seo_title: 'Benary Giant Deep Red Zinnia Seeds | Dark Burgundy Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Deep Red zinnias from seed — rich burgundy-red 4-5 inch blooms on long stems. Disease-resistant. $3.95/packet from Georgia.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Or start indoors 4 weeks before. Pinch at 8–12 inches tall. Avoid overhead watering.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun — 8+ hours for deepest color',
          soil_preferences: 'Well-draining soil; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Wedding flowers', 'Romantic bouquets', 'Farmers market'],
          harvest_tips: 'Wiggle test for harvest readiness. Cut above a leaf node. Condition in warm water first, then move to cool water overnight.',
          vase_life: '10–14 days',
          special_notes: 'Color deepens in hot, direct sun. Excellent mildew resistance. Pairs with blush, peach, cream, and lime-green tones.'
        }
      },

      {
        name: 'Benary Giant Bright Pink Zinnia',
        slug: 'zinnia-benary-giant-bright-pink',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Electric hot-pink Benary Giant zinnia — vivid, bold, and one of the best sellers at any farmers market. ~50 seeds.',
        description: `Benary Giant Bright Pink is the hot pink that stops traffic at farmers markets — electric, vivid, and completely irresistible. The 4–5 inch blooms are fully double with tightly packed petals in a neon-adjacent pink that photographs brilliantly and looks equally stunning in the garden and the vase. This is consistently among the fastest-selling zinnia colors at market.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches apart. Pinch seedlings at 8–12 inches for more branching and longer stems. Benary Giants are bred for disease resistance, which matters enormously in the humid Southeast summers — while other zinnias succumb to powdery mildew by August, Benary Giants keep producing. In Georgia, expect blooms from June through first frost with succession plantings every 3 weeks.\n\nHarvest at the wiggle test stage — stem firm when held 8 inches below bloom. Cut above a leaf node to encourage continued production. Hot pink pairs with lime green, coral, white, and purple for high-energy bouquets that sell immediately. Vase life is 10–14 days, longer than almost any other summer annual.\n\nKeywords: Benary Giant Bright Pink zinnia seeds, hot pink zinnia seeds, cut flower zinnia, pink zinnia seeds Georgia, farmers market flowers.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'pollinator', 'disease-resistant'],
        is_featured: true,
        sort_order: 10,
        seo_title: 'Benary Giant Bright Pink Zinnia Seeds | Hot Pink Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow electric hot-pink Benary Giant zinnias from seed — vivid 4-5 inch blooms, mildew-resistant, top farmers market seller. $3.95/packet.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost. Full sun required. Pinch at 8–12 inches for branching. Avoid wetting foliage to minimize disease.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (8+ hours)',
          soil_preferences: 'Well-draining soil; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'Farmers market', 'Bouquets', 'Garden borders', 'Pollinator garden'],
          harvest_tips: 'Use the wiggle test. Cut above a leaf node. Hot pink holds color well in the vase — does not fade quickly.',
          vase_life: '10–14 days',
          special_notes: 'Best color achieved in full sun. One of the top farmers market sellers. Excellent powdery mildew resistance.'
        }
      },

      {
        name: 'Benary Giant Salmon Rose Zinnia',
        slug: 'zinnia-benary-giant-salmon-rose',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Soft salmon-rose Benary Giant zinnia — gentle, romantic color for wedding and home arrangements. ~50 seeds.',
        description: `Benary Giant Salmon Rose is the soft, romantic alternative to bold pink — petals in a warm salmon-rose that bridges the gap between peach and pink, creating a color that works in nearly any arrangement and palette. This is the zinnia for wedding florists, boutique market stalls, and gardeners who prefer a more restrained, elegant tone without sacrificing the large 4–5 inch bloom size that makes Benary Giants unmistakable.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches. Pinch plants at 8–12 inches tall to encourage multiple branching stems. Like all Benary Giants, Salmon Rose has outstanding powdery mildew resistance — critical for the Southeast's humid growing season. In Georgia, expect continuous blooms from June through frost with successive plantings every 3 weeks.\n\nHarvest at the wiggle test stage. Salmon Rose pairs beautifully with Benary Giant Coral, blush lisianthus, cream ranunculus, and silvery foliage for a palette that photographs softly and appeals to a wide customer base. Vase life is 10–14 days — among the longest of any annual. Whether you're growing for a wedding, a subscription bouquet service, or your own home, this variety delivers.\n\nKeywords: Benary Giant Salmon Rose zinnia seeds, salmon zinnia, peach zinnia seeds, wedding zinnia, cut flower zinnia seeds Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'wedding'],
        is_featured: false,
        sort_order: 11,
        seo_title: 'Benary Giant Salmon Rose Zinnia Seeds | Soft Peach-Pink Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Salmon Rose zinnias — soft salmon-pink 4-5 inch blooms, mildew-resistant, perfect for wedding flowers. $3.95/packet Georgia.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches. Avoid overhead watering.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Subscription bouquets', 'Cut flowers', 'Farmers market'],
          harvest_tips: 'Wiggle test to confirm harvest readiness. Pairs best with other soft tones. Condition overnight before arranging.',
          vase_life: '10–14 days',
          special_notes: 'Color is most accurate and vibrant in full sun. Excellent for mixed romantic bouquets with blush and cream tones.'
        }
      },

      {
        name: 'Benary Giant Lilac Zinnia',
        slug: 'zinnia-benary-giant-lilac',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Soft lilac-lavender Benary Giant zinnia — rare in summer annuals. Stunning in pastel palettes. ~50 seeds.',
        description: `True lilac-toned annuals are rare, and Benary Giant Lilac delivers — soft lavender-pink blooms that shift toward lilac-gray as they age, creating a sophisticated, almost antique quality that modern florists love. These 4–5 inch blooms are a standout in any bouquet and especially prized in summer when true purples and lavenders are hard to source. This variety consistently draws comments from customers at farmers markets.\n\nGrow like all Benary Giants: full sun, direct sow after last frost, space 12–15 inches, pinch at 8–12 inches for more stems. The Benary series' disease resistance is critical in the Southeast's humid summers — Lilac maintains clean foliage when other zinnia varieties falter. Succession sow every 3 weeks from last frost through July for blooms into October.\n\nHarvest at the wiggle test stage. Lilac pairs magnificently with white, cream, soft green bupleurum, and deep purple bachelor buttons for an ethereal, romantic palette. It also makes a beautiful bridge color between pink and purple in mixed bouquets. Vase life runs 10–14 days.\n\nKeywords: Benary Giant Lilac zinnia seeds, lavender zinnia, lilac zinnia seeds, purple zinnia, soft color zinnia, cut flower zinnia seeds Georgia.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'unique-color'],
        is_featured: false,
        sort_order: 12,
        seo_title: 'Benary Giant Lilac Zinnia Seeds | Lavender Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Lilac zinnias — rare soft lavender 4-5 inch blooms, mildew-resistant, stunning in pastel bouquets. $3.95/packet Georgia farm.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost. Full sun. Pinch at 8–12 inches. Keep soil moist but not wet.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Wedding flowers', 'Pastel arrangements', 'Subscription bouquets', 'Cut flowers'],
          harvest_tips: 'Harvest using wiggle test. Color evolves as blooms age — both stages are beautiful. Cut early for longer display.',
          vase_life: '10–14 days',
          special_notes: 'Color shifts toward lilac-gray as it ages, adding antique character. Pairs with Bachelor Button Blue, white cosmos, and cream snapdragons.'
        }
      },

      {
        name: 'Benary Giant Purple Zinnia',
        slug: 'zinnia-benary-giant-purple',
        sol_category: 'seeds-bulbs',
        subcategory: 'Zinnias',
        flower_name: 'Zinnia',
        flower_type: 'Annual',
        short_description: 'Rich royal purple Benary Giant zinnia with large 4–5 inch blooms. Bold, saturated color for summer arrangements. ~50 seeds.',
        description: `Benary Giant Purple delivers what many summer gardens lack — a true, saturated purple in the form of a large-bloomed, disease-resistant zinnia. Deep royal purple petals in the classic fully-double zinnia form, measuring 4–5 inches across on long strong stems. This is one of the most dramatic colors in the Benary Giant lineup and a serious attention-getter in mixed bouquets.\n\nGrow in full sun with direct sow after last frost, spacing 12–15 inches. Pinch at 8–12 inches to encourage more branching and longer stem production. Benary Giants are bred for the conditions we face in Georgia — heat, humidity, and the powdery mildew that plagues other zinnia varieties — and they perform through it all. Succession sow every 3 weeks for continuous supply through October.\n\nHarvest at the wiggle test stage. Purple pairs with golden yellow (Benary Giant Golden Yellow or rudbeckia), white, lime green (Queen Lime or bupleurum), and orange for dynamic, high-contrast arrangements. It's also beautiful in monochromatic purple-to-lavender combinations with Benary Giant Lilac and purple bachelor buttons. Vase life 10–14 days.\n\nKeywords: Benary Giant Purple zinnia seeds, purple zinnia seeds, royal purple zinnia, cut flower zinnia seeds, grow zinnia Georgia Southeast.`,
        price: 3.95,
        price_label: '$3.95 per packet',
        images: '[]',
        availability: 'in_stock',
        season_tags: ['summer', 'warm-season', 'fall'],
        type_tags: ['cut-flower', 'heat-loving', 'disease-resistant', 'pollinator'],
        is_featured: false,
        sort_order: 13,
        seo_title: 'Benary Giant Purple Zinnia Seeds | Rich Royal Purple Cut Flower | Sugar Oak Lane',
        seo_description: 'Grow Benary Giant Purple zinnias from seed — deep royal purple 4-5 inch blooms, disease-resistant, bold summer cut flower. $3.95/packet Georgia.',
        packet_quantity: 50,
        seed_details: {
          growing_instructions: 'Direct sow 1/4 inch deep after last frost in full sun. Pinch at 8–12 inches. Succession sow every 3 weeks.',
          days_to_maturity: '70–75 days',
          plant_height: '2.5–3 feet',
          plant_spread: '12–18 inches',
          sun_requirements: 'Full sun (8+ hours for best color)',
          soil_preferences: 'Well-draining; pH 5.5–7.0',
          spacing: '12–15 inches',
          sow_method: 'Direct sow or start indoors 4 weeks before last frost',
          hardiness_zones: 'Annual — all zones',
          best_uses: ['Cut flowers', 'High-contrast arrangements', 'Farmers market', 'Pollinator garden'],
          harvest_tips: 'Wiggle test for harvest. Cut above leaf node to encourage reblooming. Color holds beautifully in the vase.',
          vase_life: '10–14 days',
          special_notes: 'Most vibrant in full sun. Excellent disease resistance. Pairs with golden yellow, lime green, and white for classic color contrast.'
        }
      },

    ];

    // Insert products
    for (const p of products) {
      await client.query(`
        INSERT INTO sol_products (
          name, slug, sol_category, subcategory, short_description, description,
          price, price_label, images, availability, season_tags, type_tags,
          is_featured, sort_order, flower_name, flower_type,
          seo_title, seo_description, packet_quantity, seed_details, is_active
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,true)
        ON CONFLICT (slug) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          short_description = EXCLUDED.short_description,
          price = EXCLUDED.price,
          packet_quantity = EXCLUDED.packet_quantity,
          seed_details = EXCLUDED.seed_details,
          seo_title = EXCLUDED.seo_title,
          seo_description = EXCLUDED.seo_description,
          season_tags = EXCLUDED.season_tags,
          type_tags = EXCLUDED.type_tags,
          flower_name = EXCLUDED.flower_name,
          flower_type = EXCLUDED.flower_type,
          updated_at = NOW()
      `, [
        p.name, p.slug, p.sol_category, p.subcategory, p.short_description, p.description,
        p.price, p.price_label, JSON.stringify(p.images ? [] : []), p.availability,
        p.season_tags, p.type_tags, p.is_featured, p.sort_order,
        p.flower_name, p.flower_type, p.seo_title, p.seo_description,
        p.packet_quantity, JSON.stringify(p.seed_details)
      ]);
    }

    console.log(`Seeded ${products.length} seed products (part 1)`);
  },
  down: async (client) => {
    const slugs = [
      'sunflower-procut-orange','sunflower-procut-white-nite','sunflower-procut-red',
      'sunflower-procut-plum','sunflower-sunrich-gold','sunflower-sunrich-orange',
      'sunflower-chocolate-cherry',
      'zinnia-benary-giant-scarlet','zinnia-benary-giant-deep-red','zinnia-benary-giant-bright-pink',
      'zinnia-benary-giant-salmon-rose','zinnia-benary-giant-lilac','zinnia-benary-giant-purple',
    ];
    await client.query(`DELETE FROM sol_products WHERE slug = ANY($1)`, [slugs]);
  }
};
