/** Final 14 source-backed listings not captured by the generic parser. */
const ITEMS=[
 {slug:'dahlia-belle-of-barmera',name:'Dahlia Belle of Barmera',short:'A peach and raspberry dahlia with informal decorative blooms.',desc:'Dahlia Belle of Barmera produces informal decorative blooms in a warm blend of peach and raspberry tones. The layered petals give each flower a loose, expressive form with rich color variation.',colors:['peach','raspberry'],form:'informal decorative'},
 {slug:'dahlia-bryn-terfel',name:'Dahlia Bryn Terfel',short:'A raspberry-toned dahlia with informal decorative blooms.',desc:'Dahlia Bryn Terfel produces raspberry-toned informal decorative blooms with a relaxed, layered petal arrangement and strong visual depth.',colors:['raspberry'],form:'informal decorative'},
 {slug:'dahlia-daisy-duke',name:'Dahlia Daisy Duke',short:'A muted raspberry dahlia with formal decorative blooms.',desc:'Dahlia Daisy Duke produces formal decorative blooms in a muted raspberry palette. Its orderly petal structure gives the flowers a refined shape while the softened coloring keeps the overall effect warm and nuanced.',colors:['muted raspberry'],form:'formal decorative'},
 {slug:'dahlia-foxy-lady',name:'Dahlia Foxy Lady',short:'A raspberry-toned dahlia with formal decorative blooms.',desc:'Dahlia Foxy Lady produces raspberry-toned formal decorative blooms with a balanced, symmetrical petal arrangement and saturated color.',colors:['raspberry'],form:'formal decorative'},
 {slug:'dahlia-ka-s-rosie-jo',name:'Dahlia KA’s Rosie Jo',short:'A pink and raspberry dahlia with formal decorative blooms.',desc:'Dahlia KA’s Rosie Jo produces formal decorative blooms in layered shades of pink and raspberry. The structured flower form gives the color a polished, full appearance.',colors:['pink','raspberry'],form:'formal decorative'},
 {slug:'dahlia-labyrinth',name:'Dahlia Labyrinth',short:'A peach and raspberry dahlia with informal decorative blooms.',desc:'Dahlia Labyrinth produces informal decorative blooms that blend peach and raspberry tones. Its looser petal arrangement creates a dimensional, swirling flower with a distinctive painterly look.',colors:['peach','raspberry'],form:'informal decorative'},
 {slug:'dahlia-mission-gypsy',name:'Dahlia Mission Gypsy',short:'A muted raspberry dahlia with formal decorative blooms.',desc:'Dahlia Mission Gypsy produces formal decorative blooms in a softened raspberry palette. The structured petal pattern and muted color create an elegant, understated flower.',colors:['muted raspberry'],form:'formal decorative'},
 {slug:'dahlia-mystique',name:'Dahlia Mystique',short:'A coral and raspberry dahlia with formal decorative blooms.',desc:'Dahlia Mystique produces formal decorative blooms in coral and raspberry tones. The warm color blend and orderly petals give the flower a rich, dimensional appearance.',colors:['coral','raspberry'],form:'formal decorative'},
 {slug:'dahlia-penhill-dark-monarch',name:'Dahlia Penhill Dark Monarch',short:'A pink-to-raspberry dahlia with informal decorative blooms.',desc:'Dahlia Penhill Dark Monarch produces informal decorative blooms in pink-to-raspberry tones. Its loose, layered petals create the dramatic movement associated with the Penhill style.',colors:['pink','raspberry'],form:'informal decorative'},
 {slug:'dahlia-salmon-runner',name:'Dahlia Salmon Runner',short:'A raspberry-toned dahlia with formal decorative blooms.',desc:'Dahlia Salmon Runner produces formal decorative blooms with raspberry-toned coloring and a full, orderly petal structure.',colors:['raspberry'],form:'formal decorative'},
 {slug:'dahlia-sonic-bloom',name:'Dahlia Sonic Bloom',short:'A muted raspberry dahlia with informal decorative blooms.',desc:'Dahlia Sonic Bloom produces informal decorative blooms in a muted raspberry palette. The relaxed petal arrangement adds movement and texture to the softened color.',colors:['muted raspberry'],form:'informal decorative'},
 {slug:'dahlia-tahoma-vivian',name:'Dahlia Tahoma Vivian',short:'A raspberry-toned dahlia with formal decorative blooms.',desc:'Dahlia Tahoma Vivian produces raspberry-toned formal decorative blooms with a clean, structured petal arrangement.',colors:['raspberry'],form:'formal decorative'},
 {slug:'dahlia-tempest',name:'Dahlia Tempest',short:'A raspberry-toned dahlia with formal decorative blooms.',desc:'Dahlia Tempest produces formal decorative blooms in a saturated raspberry tone. Its symmetrical petal structure gives the flower a crisp, polished shape.',colors:['raspberry'],form:'formal decorative'},
 {slug:'lace-flower-lacy-blue',name:'Lace Flower Lacy Blue',short:'An airy blue lace flower with delicate filler blooms and strong pollinator appeal.',desc:'Lace Flower Lacy Blue produces airy blue flower clusters with a light, lacy texture. The stems work well as a foliage-and-flower filler, and the blooms are attractive to pollinators.',colors:['blue'],form:'lace flower clusters',extra:{pollinator_friendly:true,foliage_filler:true}}
];
module.exports={name:'finalize_last_product_copy',up:async(client)=>{
 for(const p of ITEMS){
  const details={content_status:'variety_copy_ready',copy_method:'original_from_source_tags',extracted_color_terms:p.colors,extracted_form:p.form,fact_extraction_status:'ready',image_prompt_reference:`${p.colors.join(' and ')}; ${p.form}; sharp botanical portrait with a softly blurred flower-farm or garden background, natural light, shallow depth of field`,...(p.extra||{})};
  const type=p.slug.startsWith('dahlia-')?'dahlia tuber':'flower seeds';
  const seo=`${p.name} ${type} from Sugar Oak Lane. ${p.short}`.slice(0,220);
  await client.query(`UPDATE sol_products SET short_description=$1,description=$2,seo_description=$3,seed_details=COALESCE(seed_details,'{}'::jsonb)||$4::jsonb,updated_at=NOW() WHERE slug=$5 AND seed_details->>'catalog_status'='staging_ready'`,[p.short,p.desc,seo,JSON.stringify(details),p.slug]);
 }
 const r=await client.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE seed_details->>'content_status'='variety_copy_ready')::int ready FROM sol_products WHERE seed_details->>'catalog_status'='staging_ready'`);console.log('[final-copy]',r.rows[0]);
},down:async()=>{}};
